-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity nn_accelerator is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    S_AXIS_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    S_AXIS_TVALID : IN STD_LOGIC;
    S_AXIS_TREADY : OUT STD_LOGIC;
    S_AXIS_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
    S_AXIS_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
    S_AXIS_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    M_AXIS_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    M_AXIS_TVALID : OUT STD_LOGIC;
    M_AXIS_TREADY : IN STD_LOGIC;
    M_AXIS_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
    M_AXIS_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    M_AXIS_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0) );
end;


architecture behav of nn_accelerator is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "nn_accelerator_nn_accelerator,hls_ip_2025_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xck26-sfvc784-2LV-c,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=4.684063,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=1,HLS_SYN_DSP=0,HLS_SYN_FF=503,HLS_SYN_LUT=1109,HLS_VERSION=2025_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (17 downto 0) := "000000000000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (17 downto 0) := "000000000000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (17 downto 0) := "000000000000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (17 downto 0) := "000000000000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (17 downto 0) := "000000000000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (17 downto 0) := "000000000000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (17 downto 0) := "000000000001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (17 downto 0) := "000000000010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (17 downto 0) := "000000000100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (17 downto 0) := "000000001000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (17 downto 0) := "000000010000000000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (17 downto 0) := "000000100000000000";
    constant ap_ST_fsm_state13 : STD_LOGIC_VECTOR (17 downto 0) := "000001000000000000";
    constant ap_ST_fsm_state14 : STD_LOGIC_VECTOR (17 downto 0) := "000010000000000000";
    constant ap_ST_fsm_state15 : STD_LOGIC_VECTOR (17 downto 0) := "000100000000000000";
    constant ap_ST_fsm_state16 : STD_LOGIC_VECTOR (17 downto 0) := "001000000000000000";
    constant ap_ST_fsm_state17 : STD_LOGIC_VECTOR (17 downto 0) := "010000000000000000";
    constant ap_ST_fsm_state18 : STD_LOGIC_VECTOR (17 downto 0) := "100000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_11 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010001";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv64_1 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000001";
    constant ap_const_lv64_2 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000010";
    constant ap_const_lv64_3 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000011";
    constant ap_const_lv64_4 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000100";
    constant ap_const_lv64_5 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000101";
    constant ap_const_lv64_6 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000110";
    constant ap_const_lv64_7 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000111";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";
    constant ap_const_lv18_80FF : STD_LOGIC_VECTOR (17 downto 0) := "001000000011111111";
    constant ap_const_lv32_E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001110";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";

    signal ap_rst_n_inv : STD_LOGIC;
    signal M_AXIS_TDATA_blk_n : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (17 downto 0) := "000000000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state17 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state17 : signal is "none";
    signal ap_CS_fsm_state18 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state18 : signal is "none";
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal W_hidden_load_reg_591 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal W_hidden_1_load_reg_596 : STD_LOGIC_VECTOR (7 downto 0);
    signal W_hidden_load_1_reg_601 : STD_LOGIC_VECTOR (7 downto 0);
    signal W_hidden_1_load_1_reg_606 : STD_LOGIC_VECTOR (7 downto 0);
    signal W_hidden_load_2_reg_631 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal W_hidden_1_load_2_reg_636 : STD_LOGIC_VECTOR (7 downto 0);
    signal W_hidden_load_3_reg_641 : STD_LOGIC_VECTOR (7 downto 0);
    signal W_hidden_1_load_3_reg_646 : STD_LOGIC_VECTOR (7 downto 0);
    signal W_hidden_load_4_reg_671 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal W_hidden_1_load_4_reg_676 : STD_LOGIC_VECTOR (7 downto 0);
    signal W_hidden_load_5_reg_681 : STD_LOGIC_VECTOR (7 downto 0);
    signal W_hidden_1_load_5_reg_686 : STD_LOGIC_VECTOR (7 downto 0);
    signal acc_cast_fu_407_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal acc_cast_reg_711 : STD_LOGIC_VECTOR (16 downto 0);
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal p_0_0371716_cast_fu_411_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_0_0371716_cast_reg_716 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_0_0371_1718_cast_fu_415_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_0_0371_1718_cast_reg_721 : STD_LOGIC_VECTOR (15 downto 0);
    signal W_hidden_load_6_reg_726 : STD_LOGIC_VECTOR (7 downto 0);
    signal W_hidden_1_load_6_reg_731 : STD_LOGIC_VECTOR (7 downto 0);
    signal W_hidden_load_7_reg_736 : STD_LOGIC_VECTOR (7 downto 0);
    signal W_hidden_1_load_7_reg_741 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_CS_fsm_state13 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state13 : signal is "none";
    signal ap_CS_fsm_state14 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state14 : signal is "none";
    signal ap_CS_fsm_state16 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state16 : signal is "none";
    signal last_sample_loc_load_reg_782 : STD_LOGIC_VECTOR (0 downto 0);
    signal W_hidden_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal W_hidden_ce0 : STD_LOGIC;
    signal W_hidden_we0 : STD_LOGIC;
    signal W_hidden_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal W_hidden_q1 : STD_LOGIC_VECTOR (7 downto 0);
    signal W_hidden_1_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal W_hidden_1_ce0 : STD_LOGIC;
    signal W_hidden_1_we0 : STD_LOGIC;
    signal W_hidden_1_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal W_hidden_1_q1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_77_1_fu_310_ap_start : STD_LOGIC;
    signal grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_77_1_fu_310_ap_done : STD_LOGIC;
    signal grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_77_1_fu_310_ap_idle : STD_LOGIC;
    signal grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_77_1_fu_310_ap_ready : STD_LOGIC;
    signal grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_77_1_fu_310_W_hidden_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_77_1_fu_310_W_hidden_ce0 : STD_LOGIC;
    signal grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_77_1_fu_310_W_hidden_we0 : STD_LOGIC;
    signal grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_77_1_fu_310_W_hidden_d0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_77_1_fu_310_W_hidden_1_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_77_1_fu_310_W_hidden_1_ce0 : STD_LOGIC;
    signal grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_77_1_fu_310_W_hidden_1_we0 : STD_LOGIC;
    signal grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_77_1_fu_310_W_hidden_1_d0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_77_1_fu_310_S_AXIS_TREADY : STD_LOGIC;
    signal grp_nn_accelerator_Pipeline_read_output_weights_fu_324_ap_start : STD_LOGIC;
    signal grp_nn_accelerator_Pipeline_read_output_weights_fu_324_ap_done : STD_LOGIC;
    signal grp_nn_accelerator_Pipeline_read_output_weights_fu_324_ap_idle : STD_LOGIC;
    signal grp_nn_accelerator_Pipeline_read_output_weights_fu_324_ap_ready : STD_LOGIC;
    signal grp_nn_accelerator_Pipeline_read_output_weights_fu_324_S_AXIS_TREADY : STD_LOGIC;
    signal grp_nn_accelerator_Pipeline_read_output_weights_fu_324_p_0_0371_1718_out : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_nn_accelerator_Pipeline_read_output_weights_fu_324_p_0_0371_1718_out_ap_vld : STD_LOGIC;
    signal grp_nn_accelerator_Pipeline_read_output_weights_fu_324_p_0_0371716_out : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_nn_accelerator_Pipeline_read_output_weights_fu_324_p_0_0371716_out_ap_vld : STD_LOGIC;
    signal grp_nn_accelerator_Pipeline_read_output_weights_fu_324_p_0_0377714_out : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_nn_accelerator_Pipeline_read_output_weights_fu_324_p_0_0377714_out_ap_vld : STD_LOGIC;
    signal grp_nn_accelerator_Pipeline_read_features_fu_339_ap_start : STD_LOGIC;
    signal grp_nn_accelerator_Pipeline_read_features_fu_339_ap_done : STD_LOGIC;
    signal grp_nn_accelerator_Pipeline_read_features_fu_339_ap_idle : STD_LOGIC;
    signal grp_nn_accelerator_Pipeline_read_features_fu_339_ap_ready : STD_LOGIC;
    signal grp_nn_accelerator_Pipeline_read_features_fu_339_S_AXIS_TREADY : STD_LOGIC;
    signal grp_nn_accelerator_Pipeline_read_features_fu_339_x_row_6_out : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_nn_accelerator_Pipeline_read_features_fu_339_x_row_6_out_ap_vld : STD_LOGIC;
    signal grp_nn_accelerator_Pipeline_read_features_fu_339_x_row_5_out : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_nn_accelerator_Pipeline_read_features_fu_339_x_row_5_out_ap_vld : STD_LOGIC;
    signal grp_nn_accelerator_Pipeline_read_features_fu_339_x_row_4_out : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_nn_accelerator_Pipeline_read_features_fu_339_x_row_4_out_ap_vld : STD_LOGIC;
    signal grp_nn_accelerator_Pipeline_read_features_fu_339_x_row_3_out : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_nn_accelerator_Pipeline_read_features_fu_339_x_row_3_out_ap_vld : STD_LOGIC;
    signal grp_nn_accelerator_Pipeline_read_features_fu_339_x_row_2_out : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_nn_accelerator_Pipeline_read_features_fu_339_x_row_2_out_ap_vld : STD_LOGIC;
    signal grp_nn_accelerator_Pipeline_read_features_fu_339_x_row_1_out : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_nn_accelerator_Pipeline_read_features_fu_339_x_row_1_out_ap_vld : STD_LOGIC;
    signal grp_nn_accelerator_Pipeline_read_features_fu_339_x_row_out : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_nn_accelerator_Pipeline_read_features_fu_339_x_row_out_ap_vld : STD_LOGIC;
    signal grp_nn_accelerator_Pipeline_read_features_fu_339_last_sample_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_nn_accelerator_Pipeline_read_features_fu_339_last_sample_out_ap_vld : STD_LOGIC;
    signal grp_nn_accelerator_Pipeline_compute_hidden_fu_359_ap_start : STD_LOGIC;
    signal grp_nn_accelerator_Pipeline_compute_hidden_fu_359_ap_done : STD_LOGIC;
    signal grp_nn_accelerator_Pipeline_compute_hidden_fu_359_ap_idle : STD_LOGIC;
    signal grp_nn_accelerator_Pipeline_compute_hidden_fu_359_ap_ready : STD_LOGIC;
    signal grp_nn_accelerator_Pipeline_compute_hidden_fu_359_hidden_out_1_out : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_nn_accelerator_Pipeline_compute_hidden_fu_359_hidden_out_1_out_ap_vld : STD_LOGIC;
    signal grp_nn_accelerator_Pipeline_compute_hidden_fu_359_hidden_out_out : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_nn_accelerator_Pipeline_compute_hidden_fu_359_hidden_out_out_ap_vld : STD_LOGIC;
    signal grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_77_1_fu_310_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal grp_nn_accelerator_Pipeline_read_output_weights_fu_324_ap_start_reg : STD_LOGIC := '0';
    signal grp_nn_accelerator_Pipeline_read_features_fu_339_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal ap_CS_fsm_state10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state10 : signal is "none";
    signal grp_nn_accelerator_Pipeline_compute_hidden_fu_359_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state11 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state11 : signal is "none";
    signal ap_CS_fsm_state12 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state12 : signal is "none";
    signal W_hidden_ce1_local : STD_LOGIC;
    signal W_hidden_address1_local : STD_LOGIC_VECTOR (2 downto 0);
    signal W_hidden_ce0_local : STD_LOGIC;
    signal W_hidden_address0_local : STD_LOGIC_VECTOR (2 downto 0);
    signal W_hidden_1_ce1_local : STD_LOGIC;
    signal W_hidden_1_address1_local : STD_LOGIC_VECTOR (2 downto 0);
    signal W_hidden_1_ce0_local : STD_LOGIC;
    signal W_hidden_1_address0_local : STD_LOGIC_VECTOR (2 downto 0);
    signal acc_fu_399_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_478_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_fu_485_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal out_pkt_data_fu_468_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_478_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_478_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_478_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state15 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state15 : signal is "none";
    signal grp_fu_485_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_485_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_485_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_fu_485_ce : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (17 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_ST_fsm_state10_blk : STD_LOGIC;
    signal ap_ST_fsm_state11_blk : STD_LOGIC;
    signal ap_ST_fsm_state12_blk : STD_LOGIC;
    signal ap_ST_fsm_state13_blk : STD_LOGIC;
    signal ap_ST_fsm_state14_blk : STD_LOGIC;
    signal ap_ST_fsm_state15_blk : STD_LOGIC;
    signal ap_ST_fsm_state16_blk : STD_LOGIC;
    signal ap_ST_fsm_state17_blk : STD_LOGIC;
    signal regslice_both_M_AXIS_V_data_V_U_apdone_blk : STD_LOGIC;
    signal ap_block_state18 : BOOLEAN;
    signal ap_ST_fsm_state18_blk : STD_LOGIC;
    signal regslice_both_S_AXIS_V_data_V_U_apdone_blk : STD_LOGIC;
    signal S_AXIS_TDATA_int_regslice : STD_LOGIC_VECTOR (31 downto 0);
    signal S_AXIS_TVALID_int_regslice : STD_LOGIC;
    signal S_AXIS_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_S_AXIS_V_data_V_U_ack_in : STD_LOGIC;
    signal regslice_both_S_AXIS_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal S_AXIS_TKEEP_int_regslice : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_S_AXIS_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_S_AXIS_V_keep_V_U_ack_in : STD_LOGIC;
    signal regslice_both_S_AXIS_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal S_AXIS_TSTRB_int_regslice : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_S_AXIS_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_S_AXIS_V_strb_V_U_ack_in : STD_LOGIC;
    signal regslice_both_S_AXIS_V_last_V_U_apdone_blk : STD_LOGIC;
    signal S_AXIS_TLAST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_S_AXIS_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_S_AXIS_V_last_V_U_ack_in : STD_LOGIC;
    signal M_AXIS_TDATA_int_regslice : STD_LOGIC_VECTOR (31 downto 0);
    signal M_AXIS_TVALID_int_regslice : STD_LOGIC;
    signal M_AXIS_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_M_AXIS_V_data_V_U_vld_out : STD_LOGIC;
    signal regslice_both_M_AXIS_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_M_AXIS_V_keep_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_M_AXIS_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_M_AXIS_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_M_AXIS_V_strb_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_M_AXIS_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_M_AXIS_V_last_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_M_AXIS_V_last_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_M_AXIS_V_last_V_U_vld_out : STD_LOGIC;
    signal grp_fu_478_p00 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_485_p00 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_485_p20 : STD_LOGIC_VECTOR (17 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component nn_accelerator_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_77_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        S_AXIS_TVALID : IN STD_LOGIC;
        W_hidden_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        W_hidden_ce0 : OUT STD_LOGIC;
        W_hidden_we0 : OUT STD_LOGIC;
        W_hidden_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        W_hidden_1_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        W_hidden_1_ce0 : OUT STD_LOGIC;
        W_hidden_1_we0 : OUT STD_LOGIC;
        W_hidden_1_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        S_AXIS_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        S_AXIS_TREADY : OUT STD_LOGIC;
        S_AXIS_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
        S_AXIS_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
        S_AXIS_TLAST : IN STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component nn_accelerator_nn_accelerator_Pipeline_read_output_weights IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        S_AXIS_TVALID : IN STD_LOGIC;
        S_AXIS_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        S_AXIS_TREADY : OUT STD_LOGIC;
        S_AXIS_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
        S_AXIS_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
        S_AXIS_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
        p_0_0371_1718_out : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_0_0371_1718_out_ap_vld : OUT STD_LOGIC;
        p_0_0371716_out : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_0_0371716_out_ap_vld : OUT STD_LOGIC;
        p_0_0377714_out : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_0_0377714_out_ap_vld : OUT STD_LOGIC );
    end component;


    component nn_accelerator_nn_accelerator_Pipeline_read_features IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        S_AXIS_TVALID : IN STD_LOGIC;
        S_AXIS_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        S_AXIS_TREADY : OUT STD_LOGIC;
        S_AXIS_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
        S_AXIS_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
        S_AXIS_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
        x_row_6_out : OUT STD_LOGIC_VECTOR (7 downto 0);
        x_row_6_out_ap_vld : OUT STD_LOGIC;
        x_row_5_out : OUT STD_LOGIC_VECTOR (7 downto 0);
        x_row_5_out_ap_vld : OUT STD_LOGIC;
        x_row_4_out : OUT STD_LOGIC_VECTOR (7 downto 0);
        x_row_4_out_ap_vld : OUT STD_LOGIC;
        x_row_3_out : OUT STD_LOGIC_VECTOR (7 downto 0);
        x_row_3_out_ap_vld : OUT STD_LOGIC;
        x_row_2_out : OUT STD_LOGIC_VECTOR (7 downto 0);
        x_row_2_out_ap_vld : OUT STD_LOGIC;
        x_row_1_out : OUT STD_LOGIC_VECTOR (7 downto 0);
        x_row_1_out_ap_vld : OUT STD_LOGIC;
        x_row_out : OUT STD_LOGIC_VECTOR (7 downto 0);
        x_row_out_ap_vld : OUT STD_LOGIC;
        last_sample_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        last_sample_out_ap_vld : OUT STD_LOGIC );
    end component;


    component nn_accelerator_nn_accelerator_Pipeline_compute_hidden IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        W_hidden_1_load : IN STD_LOGIC_VECTOR (7 downto 0);
        W_hidden_load : IN STD_LOGIC_VECTOR (7 downto 0);
        W_hidden_1_load_1 : IN STD_LOGIC_VECTOR (7 downto 0);
        W_hidden_load_1 : IN STD_LOGIC_VECTOR (7 downto 0);
        W_hidden_1_load_2 : IN STD_LOGIC_VECTOR (7 downto 0);
        W_hidden_load_2 : IN STD_LOGIC_VECTOR (7 downto 0);
        W_hidden_1_load_3 : IN STD_LOGIC_VECTOR (7 downto 0);
        W_hidden_load_3 : IN STD_LOGIC_VECTOR (7 downto 0);
        W_hidden_1_load_4 : IN STD_LOGIC_VECTOR (7 downto 0);
        W_hidden_load_4 : IN STD_LOGIC_VECTOR (7 downto 0);
        W_hidden_1_load_5 : IN STD_LOGIC_VECTOR (7 downto 0);
        W_hidden_load_5 : IN STD_LOGIC_VECTOR (7 downto 0);
        W_hidden_1_load_6 : IN STD_LOGIC_VECTOR (7 downto 0);
        W_hidden_load_6 : IN STD_LOGIC_VECTOR (7 downto 0);
        W_hidden_1_load_7 : IN STD_LOGIC_VECTOR (7 downto 0);
        W_hidden_load_7 : IN STD_LOGIC_VECTOR (7 downto 0);
        zext_ln137 : IN STD_LOGIC_VECTOR (7 downto 0);
        x_row_5_cast : IN STD_LOGIC_VECTOR (7 downto 0);
        x_row_4_cast : IN STD_LOGIC_VECTOR (7 downto 0);
        x_row_3_cast : IN STD_LOGIC_VECTOR (7 downto 0);
        x_row_2_cast : IN STD_LOGIC_VECTOR (7 downto 0);
        x_row_1_cast : IN STD_LOGIC_VECTOR (7 downto 0);
        x_row_cast : IN STD_LOGIC_VECTOR (7 downto 0);
        hidden_out_1_out : OUT STD_LOGIC_VECTOR (7 downto 0);
        hidden_out_1_out_ap_vld : OUT STD_LOGIC;
        hidden_out_out : OUT STD_LOGIC_VECTOR (7 downto 0);
        hidden_out_out_ap_vld : OUT STD_LOGIC );
    end component;


    component nn_accelerator_mac_muladd_8ns_8ns_16ns_17_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        din2 : IN STD_LOGIC_VECTOR (15 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (16 downto 0) );
    end component;


    component nn_accelerator_mac_muladd_8ns_8ns_17ns_18_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        din2 : IN STD_LOGIC_VECTOR (16 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (17 downto 0) );
    end component;


    component nn_accelerator_W_hidden_RAM_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (2 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (7 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        address1 : IN STD_LOGIC_VECTOR (2 downto 0);
        ce1 : IN STD_LOGIC;
        q1 : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component nn_accelerator_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    W_hidden_U : component nn_accelerator_W_hidden_RAM_AUTO_1R1W
    generic map (
        DataWidth => 8,
        AddressRange => 8,
        AddressWidth => 3)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => W_hidden_address0,
        ce0 => W_hidden_ce0,
        we0 => W_hidden_we0,
        d0 => grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_77_1_fu_310_W_hidden_d0,
        q0 => W_hidden_q0,
        address1 => W_hidden_address1_local,
        ce1 => W_hidden_ce1_local,
        q1 => W_hidden_q1);

    W_hidden_1_U : component nn_accelerator_W_hidden_RAM_AUTO_1R1W
    generic map (
        DataWidth => 8,
        AddressRange => 8,
        AddressWidth => 3)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => W_hidden_1_address0,
        ce0 => W_hidden_1_ce0,
        we0 => W_hidden_1_we0,
        d0 => grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_77_1_fu_310_W_hidden_1_d0,
        q0 => W_hidden_1_q0,
        address1 => W_hidden_1_address1_local,
        ce1 => W_hidden_1_ce1_local,
        q1 => W_hidden_1_q1);

    grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_77_1_fu_310 : component nn_accelerator_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_77_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_77_1_fu_310_ap_start,
        ap_done => grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_77_1_fu_310_ap_done,
        ap_idle => grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_77_1_fu_310_ap_idle,
        ap_ready => grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_77_1_fu_310_ap_ready,
        S_AXIS_TVALID => S_AXIS_TVALID_int_regslice,
        W_hidden_address0 => grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_77_1_fu_310_W_hidden_address0,
        W_hidden_ce0 => grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_77_1_fu_310_W_hidden_ce0,
        W_hidden_we0 => grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_77_1_fu_310_W_hidden_we0,
        W_hidden_d0 => grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_77_1_fu_310_W_hidden_d0,
        W_hidden_1_address0 => grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_77_1_fu_310_W_hidden_1_address0,
        W_hidden_1_ce0 => grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_77_1_fu_310_W_hidden_1_ce0,
        W_hidden_1_we0 => grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_77_1_fu_310_W_hidden_1_we0,
        W_hidden_1_d0 => grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_77_1_fu_310_W_hidden_1_d0,
        S_AXIS_TDATA => S_AXIS_TDATA_int_regslice,
        S_AXIS_TREADY => grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_77_1_fu_310_S_AXIS_TREADY,
        S_AXIS_TKEEP => S_AXIS_TKEEP_int_regslice,
        S_AXIS_TSTRB => S_AXIS_TSTRB_int_regslice,
        S_AXIS_TLAST => S_AXIS_TLAST_int_regslice);

    grp_nn_accelerator_Pipeline_read_output_weights_fu_324 : component nn_accelerator_nn_accelerator_Pipeline_read_output_weights
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_nn_accelerator_Pipeline_read_output_weights_fu_324_ap_start,
        ap_done => grp_nn_accelerator_Pipeline_read_output_weights_fu_324_ap_done,
        ap_idle => grp_nn_accelerator_Pipeline_read_output_weights_fu_324_ap_idle,
        ap_ready => grp_nn_accelerator_Pipeline_read_output_weights_fu_324_ap_ready,
        S_AXIS_TVALID => S_AXIS_TVALID_int_regslice,
        S_AXIS_TDATA => S_AXIS_TDATA_int_regslice,
        S_AXIS_TREADY => grp_nn_accelerator_Pipeline_read_output_weights_fu_324_S_AXIS_TREADY,
        S_AXIS_TKEEP => S_AXIS_TKEEP_int_regslice,
        S_AXIS_TSTRB => S_AXIS_TSTRB_int_regslice,
        S_AXIS_TLAST => S_AXIS_TLAST_int_regslice,
        p_0_0371_1718_out => grp_nn_accelerator_Pipeline_read_output_weights_fu_324_p_0_0371_1718_out,
        p_0_0371_1718_out_ap_vld => grp_nn_accelerator_Pipeline_read_output_weights_fu_324_p_0_0371_1718_out_ap_vld,
        p_0_0371716_out => grp_nn_accelerator_Pipeline_read_output_weights_fu_324_p_0_0371716_out,
        p_0_0371716_out_ap_vld => grp_nn_accelerator_Pipeline_read_output_weights_fu_324_p_0_0371716_out_ap_vld,
        p_0_0377714_out => grp_nn_accelerator_Pipeline_read_output_weights_fu_324_p_0_0377714_out,
        p_0_0377714_out_ap_vld => grp_nn_accelerator_Pipeline_read_output_weights_fu_324_p_0_0377714_out_ap_vld);

    grp_nn_accelerator_Pipeline_read_features_fu_339 : component nn_accelerator_nn_accelerator_Pipeline_read_features
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_nn_accelerator_Pipeline_read_features_fu_339_ap_start,
        ap_done => grp_nn_accelerator_Pipeline_read_features_fu_339_ap_done,
        ap_idle => grp_nn_accelerator_Pipeline_read_features_fu_339_ap_idle,
        ap_ready => grp_nn_accelerator_Pipeline_read_features_fu_339_ap_ready,
        S_AXIS_TVALID => S_AXIS_TVALID_int_regslice,
        S_AXIS_TDATA => S_AXIS_TDATA_int_regslice,
        S_AXIS_TREADY => grp_nn_accelerator_Pipeline_read_features_fu_339_S_AXIS_TREADY,
        S_AXIS_TKEEP => S_AXIS_TKEEP_int_regslice,
        S_AXIS_TSTRB => S_AXIS_TSTRB_int_regslice,
        S_AXIS_TLAST => S_AXIS_TLAST_int_regslice,
        x_row_6_out => grp_nn_accelerator_Pipeline_read_features_fu_339_x_row_6_out,
        x_row_6_out_ap_vld => grp_nn_accelerator_Pipeline_read_features_fu_339_x_row_6_out_ap_vld,
        x_row_5_out => grp_nn_accelerator_Pipeline_read_features_fu_339_x_row_5_out,
        x_row_5_out_ap_vld => grp_nn_accelerator_Pipeline_read_features_fu_339_x_row_5_out_ap_vld,
        x_row_4_out => grp_nn_accelerator_Pipeline_read_features_fu_339_x_row_4_out,
        x_row_4_out_ap_vld => grp_nn_accelerator_Pipeline_read_features_fu_339_x_row_4_out_ap_vld,
        x_row_3_out => grp_nn_accelerator_Pipeline_read_features_fu_339_x_row_3_out,
        x_row_3_out_ap_vld => grp_nn_accelerator_Pipeline_read_features_fu_339_x_row_3_out_ap_vld,
        x_row_2_out => grp_nn_accelerator_Pipeline_read_features_fu_339_x_row_2_out,
        x_row_2_out_ap_vld => grp_nn_accelerator_Pipeline_read_features_fu_339_x_row_2_out_ap_vld,
        x_row_1_out => grp_nn_accelerator_Pipeline_read_features_fu_339_x_row_1_out,
        x_row_1_out_ap_vld => grp_nn_accelerator_Pipeline_read_features_fu_339_x_row_1_out_ap_vld,
        x_row_out => grp_nn_accelerator_Pipeline_read_features_fu_339_x_row_out,
        x_row_out_ap_vld => grp_nn_accelerator_Pipeline_read_features_fu_339_x_row_out_ap_vld,
        last_sample_out => grp_nn_accelerator_Pipeline_read_features_fu_339_last_sample_out,
        last_sample_out_ap_vld => grp_nn_accelerator_Pipeline_read_features_fu_339_last_sample_out_ap_vld);

    grp_nn_accelerator_Pipeline_compute_hidden_fu_359 : component nn_accelerator_nn_accelerator_Pipeline_compute_hidden
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_nn_accelerator_Pipeline_compute_hidden_fu_359_ap_start,
        ap_done => grp_nn_accelerator_Pipeline_compute_hidden_fu_359_ap_done,
        ap_idle => grp_nn_accelerator_Pipeline_compute_hidden_fu_359_ap_idle,
        ap_ready => grp_nn_accelerator_Pipeline_compute_hidden_fu_359_ap_ready,
        W_hidden_1_load => W_hidden_1_load_reg_596,
        W_hidden_load => W_hidden_load_reg_591,
        W_hidden_1_load_1 => W_hidden_1_load_1_reg_606,
        W_hidden_load_1 => W_hidden_load_1_reg_601,
        W_hidden_1_load_2 => W_hidden_1_load_2_reg_636,
        W_hidden_load_2 => W_hidden_load_2_reg_631,
        W_hidden_1_load_3 => W_hidden_1_load_3_reg_646,
        W_hidden_load_3 => W_hidden_load_3_reg_641,
        W_hidden_1_load_4 => W_hidden_1_load_4_reg_676,
        W_hidden_load_4 => W_hidden_load_4_reg_671,
        W_hidden_1_load_5 => W_hidden_1_load_5_reg_686,
        W_hidden_load_5 => W_hidden_load_5_reg_681,
        W_hidden_1_load_6 => W_hidden_1_load_6_reg_731,
        W_hidden_load_6 => W_hidden_load_6_reg_726,
        W_hidden_1_load_7 => W_hidden_1_load_7_reg_741,
        W_hidden_load_7 => W_hidden_load_7_reg_736,
        zext_ln137 => grp_nn_accelerator_Pipeline_read_features_fu_339_x_row_6_out,
        x_row_5_cast => grp_nn_accelerator_Pipeline_read_features_fu_339_x_row_5_out,
        x_row_4_cast => grp_nn_accelerator_Pipeline_read_features_fu_339_x_row_4_out,
        x_row_3_cast => grp_nn_accelerator_Pipeline_read_features_fu_339_x_row_3_out,
        x_row_2_cast => grp_nn_accelerator_Pipeline_read_features_fu_339_x_row_2_out,
        x_row_1_cast => grp_nn_accelerator_Pipeline_read_features_fu_339_x_row_1_out,
        x_row_cast => grp_nn_accelerator_Pipeline_read_features_fu_339_x_row_out,
        hidden_out_1_out => grp_nn_accelerator_Pipeline_compute_hidden_fu_359_hidden_out_1_out,
        hidden_out_1_out_ap_vld => grp_nn_accelerator_Pipeline_compute_hidden_fu_359_hidden_out_1_out_ap_vld,
        hidden_out_out => grp_nn_accelerator_Pipeline_compute_hidden_fu_359_hidden_out_out,
        hidden_out_out_ap_vld => grp_nn_accelerator_Pipeline_compute_hidden_fu_359_hidden_out_out_ap_vld);

    mac_muladd_8ns_8ns_16ns_17_4_1_U61 : component nn_accelerator_mac_muladd_8ns_8ns_16ns_17_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 16,
        dout_WIDTH => 17)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => grp_fu_478_p0,
        din1 => grp_fu_478_p1,
        din2 => grp_fu_478_p2,
        ce => ap_const_logic_1,
        dout => grp_fu_478_p3);

    mac_muladd_8ns_8ns_17ns_18_4_1_U62 : component nn_accelerator_mac_muladd_8ns_8ns_17ns_18_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 17,
        dout_WIDTH => 18)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => grp_fu_485_p0,
        din1 => grp_fu_485_p1,
        din2 => grp_fu_485_p2,
        ce => grp_fu_485_ce,
        dout => grp_fu_485_p3);

    regslice_both_S_AXIS_V_data_V_U : component nn_accelerator_regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => S_AXIS_TDATA,
        vld_in => S_AXIS_TVALID,
        ack_in => regslice_both_S_AXIS_V_data_V_U_ack_in,
        data_out => S_AXIS_TDATA_int_regslice,
        vld_out => S_AXIS_TVALID_int_regslice,
        ack_out => S_AXIS_TREADY_int_regslice,
        apdone_blk => regslice_both_S_AXIS_V_data_V_U_apdone_blk);

    regslice_both_S_AXIS_V_keep_V_U : component nn_accelerator_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => S_AXIS_TKEEP,
        vld_in => S_AXIS_TVALID,
        ack_in => regslice_both_S_AXIS_V_keep_V_U_ack_in,
        data_out => S_AXIS_TKEEP_int_regslice,
        vld_out => regslice_both_S_AXIS_V_keep_V_U_vld_out,
        ack_out => S_AXIS_TREADY_int_regslice,
        apdone_blk => regslice_both_S_AXIS_V_keep_V_U_apdone_blk);

    regslice_both_S_AXIS_V_strb_V_U : component nn_accelerator_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => S_AXIS_TSTRB,
        vld_in => S_AXIS_TVALID,
        ack_in => regslice_both_S_AXIS_V_strb_V_U_ack_in,
        data_out => S_AXIS_TSTRB_int_regslice,
        vld_out => regslice_both_S_AXIS_V_strb_V_U_vld_out,
        ack_out => S_AXIS_TREADY_int_regslice,
        apdone_blk => regslice_both_S_AXIS_V_strb_V_U_apdone_blk);

    regslice_both_S_AXIS_V_last_V_U : component nn_accelerator_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => S_AXIS_TLAST,
        vld_in => S_AXIS_TVALID,
        ack_in => regslice_both_S_AXIS_V_last_V_U_ack_in,
        data_out => S_AXIS_TLAST_int_regslice,
        vld_out => regslice_both_S_AXIS_V_last_V_U_vld_out,
        ack_out => S_AXIS_TREADY_int_regslice,
        apdone_blk => regslice_both_S_AXIS_V_last_V_U_apdone_blk);

    regslice_both_M_AXIS_V_data_V_U : component nn_accelerator_regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => M_AXIS_TDATA_int_regslice,
        vld_in => M_AXIS_TVALID_int_regslice,
        ack_in => M_AXIS_TREADY_int_regslice,
        data_out => M_AXIS_TDATA,
        vld_out => regslice_both_M_AXIS_V_data_V_U_vld_out,
        ack_out => M_AXIS_TREADY,
        apdone_blk => regslice_both_M_AXIS_V_data_V_U_apdone_blk);

    regslice_both_M_AXIS_V_keep_V_U : component nn_accelerator_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => ap_const_lv4_F,
        vld_in => M_AXIS_TVALID_int_regslice,
        ack_in => regslice_both_M_AXIS_V_keep_V_U_ack_in_dummy,
        data_out => M_AXIS_TKEEP,
        vld_out => regslice_both_M_AXIS_V_keep_V_U_vld_out,
        ack_out => M_AXIS_TREADY,
        apdone_blk => regslice_both_M_AXIS_V_keep_V_U_apdone_blk);

    regslice_both_M_AXIS_V_strb_V_U : component nn_accelerator_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => ap_const_lv4_F,
        vld_in => M_AXIS_TVALID_int_regslice,
        ack_in => regslice_both_M_AXIS_V_strb_V_U_ack_in_dummy,
        data_out => M_AXIS_TSTRB,
        vld_out => regslice_both_M_AXIS_V_strb_V_U_vld_out,
        ack_out => M_AXIS_TREADY,
        apdone_blk => regslice_both_M_AXIS_V_strb_V_U_apdone_blk);

    regslice_both_M_AXIS_V_last_V_U : component nn_accelerator_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => grp_nn_accelerator_Pipeline_read_features_fu_339_last_sample_out,
        vld_in => M_AXIS_TVALID_int_regslice,
        ack_in => regslice_both_M_AXIS_V_last_V_U_ack_in_dummy,
        data_out => M_AXIS_TLAST,
        vld_out => regslice_both_M_AXIS_V_last_V_U_vld_out,
        ack_out => M_AXIS_TREADY,
        apdone_blk => regslice_both_M_AXIS_V_last_V_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_nn_accelerator_Pipeline_compute_hidden_fu_359_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_nn_accelerator_Pipeline_compute_hidden_fu_359_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
                    grp_nn_accelerator_Pipeline_compute_hidden_fu_359_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_nn_accelerator_Pipeline_compute_hidden_fu_359_ap_ready = ap_const_logic_1)) then 
                    grp_nn_accelerator_Pipeline_compute_hidden_fu_359_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_nn_accelerator_Pipeline_read_features_fu_339_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_nn_accelerator_Pipeline_read_features_fu_339_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
                    grp_nn_accelerator_Pipeline_read_features_fu_339_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_nn_accelerator_Pipeline_read_features_fu_339_ap_ready = ap_const_logic_1)) then 
                    grp_nn_accelerator_Pipeline_read_features_fu_339_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_77_1_fu_310_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_77_1_fu_310_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
                    grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_77_1_fu_310_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_77_1_fu_310_ap_ready = ap_const_logic_1)) then 
                    grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_77_1_fu_310_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_nn_accelerator_Pipeline_read_output_weights_fu_324_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_nn_accelerator_Pipeline_read_output_weights_fu_324_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                    grp_nn_accelerator_Pipeline_read_output_weights_fu_324_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_nn_accelerator_Pipeline_read_output_weights_fu_324_ap_ready = ap_const_logic_1)) then 
                    grp_nn_accelerator_Pipeline_read_output_weights_fu_324_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
                W_hidden_1_load_1_reg_606 <= W_hidden_1_q0;
                W_hidden_1_load_reg_596 <= W_hidden_1_q1;
                W_hidden_load_1_reg_601 <= W_hidden_q0;
                W_hidden_load_reg_591 <= W_hidden_q1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state6)) then
                W_hidden_1_load_2_reg_636 <= W_hidden_1_q1;
                W_hidden_1_load_3_reg_646 <= W_hidden_1_q0;
                W_hidden_load_2_reg_631 <= W_hidden_q1;
                W_hidden_load_3_reg_641 <= W_hidden_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state7)) then
                W_hidden_1_load_4_reg_676 <= W_hidden_1_q1;
                W_hidden_1_load_5_reg_686 <= W_hidden_1_q0;
                W_hidden_load_4_reg_671 <= W_hidden_q1;
                W_hidden_load_5_reg_681 <= W_hidden_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state8)) then
                W_hidden_1_load_6_reg_731 <= W_hidden_1_q1;
                W_hidden_1_load_7_reg_741 <= W_hidden_1_q0;
                W_hidden_load_6_reg_726 <= W_hidden_q1;
                W_hidden_load_7_reg_736 <= W_hidden_q0;
                    acc_cast_reg_711(15 downto 8) <= acc_cast_fu_407_p1(15 downto 8);
                    p_0_0371716_cast_reg_716(7 downto 0) <= p_0_0371716_cast_fu_411_p1(7 downto 0);
                    p_0_0371_1718_cast_reg_721(7 downto 0) <= p_0_0371_1718_cast_fu_415_p1(7 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state17)) then
                last_sample_loc_load_reg_782 <= grp_nn_accelerator_Pipeline_read_features_fu_339_last_sample_out;
            end if;
        end if;
    end process;
    acc_cast_reg_711(7 downto 0) <= "00000000";
    acc_cast_reg_711(16) <= '0';
    p_0_0371716_cast_reg_716(15 downto 8) <= "00000000";
    p_0_0371_1718_cast_reg_721(15 downto 8) <= "00000000";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state17, ap_CS_fsm_state18, ap_CS_fsm_state5, last_sample_loc_load_reg_782, grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_77_1_fu_310_ap_done, grp_nn_accelerator_Pipeline_read_output_weights_fu_324_ap_done, grp_nn_accelerator_Pipeline_read_features_fu_339_ap_done, grp_nn_accelerator_Pipeline_compute_hidden_fu_359_ap_done, ap_CS_fsm_state3, ap_CS_fsm_state10, ap_CS_fsm_state12, ap_block_state18, M_AXIS_TREADY_int_regslice)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                ap_NS_fsm <= ap_ST_fsm_state2;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_77_1_fu_310_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                if (((grp_nn_accelerator_Pipeline_read_output_weights_fu_324_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                    ap_NS_fsm <= ap_ST_fsm_state6;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state10;
            when ap_ST_fsm_state10 => 
                if (((grp_nn_accelerator_Pipeline_read_features_fu_339_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then
                    ap_NS_fsm <= ap_ST_fsm_state11;
                else
                    ap_NS_fsm <= ap_ST_fsm_state10;
                end if;
            when ap_ST_fsm_state11 => 
                ap_NS_fsm <= ap_ST_fsm_state12;
            when ap_ST_fsm_state12 => 
                if (((grp_nn_accelerator_Pipeline_compute_hidden_fu_359_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state12))) then
                    ap_NS_fsm <= ap_ST_fsm_state13;
                else
                    ap_NS_fsm <= ap_ST_fsm_state12;
                end if;
            when ap_ST_fsm_state13 => 
                ap_NS_fsm <= ap_ST_fsm_state14;
            when ap_ST_fsm_state14 => 
                ap_NS_fsm <= ap_ST_fsm_state15;
            when ap_ST_fsm_state15 => 
                ap_NS_fsm <= ap_ST_fsm_state16;
            when ap_ST_fsm_state16 => 
                ap_NS_fsm <= ap_ST_fsm_state17;
            when ap_ST_fsm_state17 => 
                if (((ap_const_logic_1 = M_AXIS_TREADY_int_regslice) and (ap_const_logic_1 = ap_CS_fsm_state17))) then
                    ap_NS_fsm <= ap_ST_fsm_state18;
                else
                    ap_NS_fsm <= ap_ST_fsm_state17;
                end if;
            when ap_ST_fsm_state18 => 
                if (((ap_const_boolean_0 = ap_block_state18) and (ap_const_logic_1 = ap_CS_fsm_state18) and (last_sample_loc_load_reg_782 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                elsif (((ap_const_boolean_0 = ap_block_state18) and (ap_const_logic_1 = ap_CS_fsm_state18) and (last_sample_loc_load_reg_782 = ap_const_lv1_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state9;
                else
                    ap_NS_fsm <= ap_ST_fsm_state18;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXXXXXXXX";
        end case;
    end process;

    M_AXIS_TDATA_blk_n_assign_proc : process(ap_CS_fsm_state17, ap_CS_fsm_state18, M_AXIS_TREADY_int_regslice)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state18) or (ap_const_logic_1 = ap_CS_fsm_state17))) then 
            M_AXIS_TDATA_blk_n <= M_AXIS_TREADY_int_regslice;
        else 
            M_AXIS_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    M_AXIS_TDATA_int_regslice <= std_logic_vector(IEEE.numeric_std.resize(unsigned(out_pkt_data_fu_468_p2),32));
    M_AXIS_TVALID <= regslice_both_M_AXIS_V_data_V_U_vld_out;

    M_AXIS_TVALID_int_regslice_assign_proc : process(ap_CS_fsm_state17, M_AXIS_TREADY_int_regslice)
    begin
        if (((ap_const_logic_1 = M_AXIS_TREADY_int_regslice) and (ap_const_logic_1 = ap_CS_fsm_state17))) then 
            M_AXIS_TVALID_int_regslice <= ap_const_logic_1;
        else 
            M_AXIS_TVALID_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    S_AXIS_TREADY <= regslice_both_S_AXIS_V_data_V_U_ack_in;

    S_AXIS_TREADY_int_regslice_assign_proc : process(ap_CS_fsm_state5, grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_77_1_fu_310_S_AXIS_TREADY, grp_nn_accelerator_Pipeline_read_output_weights_fu_324_S_AXIS_TREADY, grp_nn_accelerator_Pipeline_read_features_fu_339_S_AXIS_TREADY, ap_CS_fsm_state3, ap_CS_fsm_state10)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            S_AXIS_TREADY_int_regslice <= grp_nn_accelerator_Pipeline_read_features_fu_339_S_AXIS_TREADY;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            S_AXIS_TREADY_int_regslice <= grp_nn_accelerator_Pipeline_read_output_weights_fu_324_S_AXIS_TREADY;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            S_AXIS_TREADY_int_regslice <= grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_77_1_fu_310_S_AXIS_TREADY;
        else 
            S_AXIS_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;


    W_hidden_1_address0_assign_proc : process(grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_77_1_fu_310_W_hidden_1_address0, ap_CS_fsm_state3, W_hidden_1_address0_local)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            W_hidden_1_address0 <= grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_77_1_fu_310_W_hidden_1_address0;
        else 
            W_hidden_1_address0 <= W_hidden_1_address0_local;
        end if; 
    end process;


    W_hidden_1_address0_local_assign_proc : process(ap_CS_fsm_state4, ap_CS_fsm_state5, ap_CS_fsm_state6, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            W_hidden_1_address0_local <= ap_const_lv64_7(3 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            W_hidden_1_address0_local <= ap_const_lv64_5(3 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            W_hidden_1_address0_local <= ap_const_lv64_3(3 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            W_hidden_1_address0_local <= ap_const_lv64_1(3 - 1 downto 0);
        else 
            W_hidden_1_address0_local <= "XXX";
        end if; 
    end process;


    W_hidden_1_address1_local_assign_proc : process(ap_CS_fsm_state4, ap_CS_fsm_state5, ap_CS_fsm_state6, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            W_hidden_1_address1_local <= ap_const_lv64_6(3 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            W_hidden_1_address1_local <= ap_const_lv64_4(3 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            W_hidden_1_address1_local <= ap_const_lv64_2(3 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            W_hidden_1_address1_local <= ap_const_lv64_0(3 - 1 downto 0);
        else 
            W_hidden_1_address1_local <= "XXX";
        end if; 
    end process;


    W_hidden_1_ce0_assign_proc : process(grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_77_1_fu_310_W_hidden_1_ce0, ap_CS_fsm_state3, W_hidden_1_ce0_local)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            W_hidden_1_ce0 <= grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_77_1_fu_310_W_hidden_1_ce0;
        else 
            W_hidden_1_ce0 <= W_hidden_1_ce0_local;
        end if; 
    end process;


    W_hidden_1_ce0_local_assign_proc : process(ap_CS_fsm_state4, ap_CS_fsm_state5, ap_CS_fsm_state6, ap_CS_fsm_state7, grp_nn_accelerator_Pipeline_read_output_weights_fu_324_ap_done)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state6) or (ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state7) or ((grp_nn_accelerator_Pipeline_read_output_weights_fu_324_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5)))) then 
            W_hidden_1_ce0_local <= ap_const_logic_1;
        else 
            W_hidden_1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;


    W_hidden_1_ce1_local_assign_proc : process(ap_CS_fsm_state4, ap_CS_fsm_state5, ap_CS_fsm_state6, ap_CS_fsm_state7, grp_nn_accelerator_Pipeline_read_output_weights_fu_324_ap_done)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state6) or (ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state7) or ((grp_nn_accelerator_Pipeline_read_output_weights_fu_324_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5)))) then 
            W_hidden_1_ce1_local <= ap_const_logic_1;
        else 
            W_hidden_1_ce1_local <= ap_const_logic_0;
        end if; 
    end process;


    W_hidden_1_we0_assign_proc : process(grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_77_1_fu_310_W_hidden_1_we0, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            W_hidden_1_we0 <= grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_77_1_fu_310_W_hidden_1_we0;
        else 
            W_hidden_1_we0 <= ap_const_logic_0;
        end if; 
    end process;


    W_hidden_address0_assign_proc : process(grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_77_1_fu_310_W_hidden_address0, ap_CS_fsm_state3, W_hidden_address0_local)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            W_hidden_address0 <= grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_77_1_fu_310_W_hidden_address0;
        else 
            W_hidden_address0 <= W_hidden_address0_local;
        end if; 
    end process;


    W_hidden_address0_local_assign_proc : process(ap_CS_fsm_state4, ap_CS_fsm_state5, ap_CS_fsm_state6, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            W_hidden_address0_local <= ap_const_lv64_7(3 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            W_hidden_address0_local <= ap_const_lv64_5(3 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            W_hidden_address0_local <= ap_const_lv64_3(3 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            W_hidden_address0_local <= ap_const_lv64_1(3 - 1 downto 0);
        else 
            W_hidden_address0_local <= "XXX";
        end if; 
    end process;


    W_hidden_address1_local_assign_proc : process(ap_CS_fsm_state4, ap_CS_fsm_state5, ap_CS_fsm_state6, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            W_hidden_address1_local <= ap_const_lv64_6(3 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            W_hidden_address1_local <= ap_const_lv64_4(3 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            W_hidden_address1_local <= ap_const_lv64_2(3 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            W_hidden_address1_local <= ap_const_lv64_0(3 - 1 downto 0);
        else 
            W_hidden_address1_local <= "XXX";
        end if; 
    end process;


    W_hidden_ce0_assign_proc : process(grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_77_1_fu_310_W_hidden_ce0, ap_CS_fsm_state3, W_hidden_ce0_local)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            W_hidden_ce0 <= grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_77_1_fu_310_W_hidden_ce0;
        else 
            W_hidden_ce0 <= W_hidden_ce0_local;
        end if; 
    end process;


    W_hidden_ce0_local_assign_proc : process(ap_CS_fsm_state4, ap_CS_fsm_state5, ap_CS_fsm_state6, ap_CS_fsm_state7, grp_nn_accelerator_Pipeline_read_output_weights_fu_324_ap_done)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state6) or (ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state7) or ((grp_nn_accelerator_Pipeline_read_output_weights_fu_324_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5)))) then 
            W_hidden_ce0_local <= ap_const_logic_1;
        else 
            W_hidden_ce0_local <= ap_const_logic_0;
        end if; 
    end process;


    W_hidden_ce1_local_assign_proc : process(ap_CS_fsm_state4, ap_CS_fsm_state5, ap_CS_fsm_state6, ap_CS_fsm_state7, grp_nn_accelerator_Pipeline_read_output_weights_fu_324_ap_done)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state6) or (ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state7) or ((grp_nn_accelerator_Pipeline_read_output_weights_fu_324_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5)))) then 
            W_hidden_ce1_local <= ap_const_logic_1;
        else 
            W_hidden_ce1_local <= ap_const_logic_0;
        end if; 
    end process;


    W_hidden_we0_assign_proc : process(grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_77_1_fu_310_W_hidden_we0, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            W_hidden_we0 <= grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_77_1_fu_310_W_hidden_we0;
        else 
            W_hidden_we0 <= ap_const_logic_0;
        end if; 
    end process;

    acc_cast_fu_407_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(acc_fu_399_p3),17));
    acc_fu_399_p3 <= (grp_nn_accelerator_Pipeline_read_output_weights_fu_324_p_0_0377714_out & ap_const_lv8_0);
    ap_CS_fsm_state10 <= ap_CS_fsm(9);
    ap_CS_fsm_state11 <= ap_CS_fsm(10);
    ap_CS_fsm_state12 <= ap_CS_fsm(11);
    ap_CS_fsm_state13 <= ap_CS_fsm(12);
    ap_CS_fsm_state14 <= ap_CS_fsm(13);
    ap_CS_fsm_state15 <= ap_CS_fsm(14);
    ap_CS_fsm_state16 <= ap_CS_fsm(15);
    ap_CS_fsm_state17 <= ap_CS_fsm(16);
    ap_CS_fsm_state18 <= ap_CS_fsm(17);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_CS_fsm_state9 <= ap_CS_fsm(8);

    ap_ST_fsm_state10_blk_assign_proc : process(grp_nn_accelerator_Pipeline_read_features_fu_339_ap_done)
    begin
        if ((grp_nn_accelerator_Pipeline_read_features_fu_339_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state10_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state10_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state11_blk <= ap_const_logic_0;

    ap_ST_fsm_state12_blk_assign_proc : process(grp_nn_accelerator_Pipeline_compute_hidden_fu_359_ap_done)
    begin
        if ((grp_nn_accelerator_Pipeline_compute_hidden_fu_359_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state12_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state12_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state13_blk <= ap_const_logic_0;
    ap_ST_fsm_state14_blk <= ap_const_logic_0;
    ap_ST_fsm_state15_blk <= ap_const_logic_0;
    ap_ST_fsm_state16_blk <= ap_const_logic_0;

    ap_ST_fsm_state17_blk_assign_proc : process(M_AXIS_TREADY_int_regslice)
    begin
        if ((ap_const_logic_0 = M_AXIS_TREADY_int_regslice)) then 
            ap_ST_fsm_state17_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state17_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state18_blk_assign_proc : process(ap_block_state18)
    begin
        if ((ap_const_boolean_1 = ap_block_state18)) then 
            ap_ST_fsm_state18_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state18_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state1_blk <= ap_const_logic_0;
    ap_ST_fsm_state2_blk <= ap_const_logic_0;

    ap_ST_fsm_state3_blk_assign_proc : process(grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_77_1_fu_310_ap_done)
    begin
        if ((grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_77_1_fu_310_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state4_blk <= ap_const_logic_0;

    ap_ST_fsm_state5_blk_assign_proc : process(grp_nn_accelerator_Pipeline_read_output_weights_fu_324_ap_done)
    begin
        if ((grp_nn_accelerator_Pipeline_read_output_weights_fu_324_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state5_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state5_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state6_blk <= ap_const_logic_0;
    ap_ST_fsm_state7_blk <= ap_const_logic_0;
    ap_ST_fsm_state8_blk <= ap_const_logic_0;
    ap_ST_fsm_state9_blk <= ap_const_logic_0;

    ap_block_state18_assign_proc : process(regslice_both_M_AXIS_V_data_V_U_apdone_blk, M_AXIS_TREADY_int_regslice)
    begin
                ap_block_state18 <= ((regslice_both_M_AXIS_V_data_V_U_apdone_blk = ap_const_logic_1) or (ap_const_logic_0 = M_AXIS_TREADY_int_regslice));
    end process;


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    grp_fu_478_p0 <= grp_fu_478_p00(8 - 1 downto 0);
    grp_fu_478_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(grp_nn_accelerator_Pipeline_compute_hidden_fu_359_hidden_out_1_out),16));
    grp_fu_478_p1 <= p_0_0371_1718_cast_reg_721(8 - 1 downto 0);
    grp_fu_478_p2 <= acc_cast_reg_711(16 - 1 downto 0);

    grp_fu_485_ce_assign_proc : process(ap_CS_fsm_state17, ap_CS_fsm_state14, ap_CS_fsm_state16, ap_CS_fsm_state15, M_AXIS_TREADY_int_regslice)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state15) or (ap_const_logic_1 = ap_CS_fsm_state16) or (ap_const_logic_1 = ap_CS_fsm_state14) or ((ap_const_logic_1 = M_AXIS_TREADY_int_regslice) and (ap_const_logic_1 = ap_CS_fsm_state17)))) then 
            grp_fu_485_ce <= ap_const_logic_1;
        else 
            grp_fu_485_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_485_p0 <= grp_fu_485_p00(8 - 1 downto 0);
    grp_fu_485_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(grp_nn_accelerator_Pipeline_compute_hidden_fu_359_hidden_out_out),16));
    grp_fu_485_p1 <= p_0_0371716_cast_reg_716(8 - 1 downto 0);
    grp_fu_485_p2 <= grp_fu_485_p20(17 - 1 downto 0);
    grp_fu_485_p20 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(grp_fu_478_p3),18));
    grp_nn_accelerator_Pipeline_compute_hidden_fu_359_ap_start <= grp_nn_accelerator_Pipeline_compute_hidden_fu_359_ap_start_reg;
    grp_nn_accelerator_Pipeline_read_features_fu_339_ap_start <= grp_nn_accelerator_Pipeline_read_features_fu_339_ap_start_reg;
    grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_77_1_fu_310_ap_start <= grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_77_1_fu_310_ap_start_reg;
    grp_nn_accelerator_Pipeline_read_output_weights_fu_324_ap_start <= grp_nn_accelerator_Pipeline_read_output_weights_fu_324_ap_start_reg;
    out_pkt_data_fu_468_p2 <= "1" when (unsigned(grp_fu_485_p3) > unsigned(ap_const_lv18_80FF)) else "0";
    p_0_0371716_cast_fu_411_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(grp_nn_accelerator_Pipeline_read_output_weights_fu_324_p_0_0371716_out),16));
    p_0_0371_1718_cast_fu_415_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(grp_nn_accelerator_Pipeline_read_output_weights_fu_324_p_0_0371_1718_out),16));
end behav;
