-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity nn_accelerator_nn_accelerator_Pipeline_compute_hidden is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    W_hidden_1_load : IN STD_LOGIC_VECTOR (7 downto 0);
    W_hidden_load : IN STD_LOGIC_VECTOR (7 downto 0);
    W_hidden_1_load_1 : IN STD_LOGIC_VECTOR (7 downto 0);
    W_hidden_load_1 : IN STD_LOGIC_VECTOR (7 downto 0);
    W_hidden_1_load_2 : IN STD_LOGIC_VECTOR (7 downto 0);
    W_hidden_load_2 : IN STD_LOGIC_VECTOR (7 downto 0);
    W_hidden_1_load_3 : IN STD_LOGIC_VECTOR (7 downto 0);
    W_hidden_load_3 : IN STD_LOGIC_VECTOR (7 downto 0);
    W_hidden_1_load_4 : IN STD_LOGIC_VECTOR (7 downto 0);
    W_hidden_load_4 : IN STD_LOGIC_VECTOR (7 downto 0);
    W_hidden_1_load_5 : IN STD_LOGIC_VECTOR (7 downto 0);
    W_hidden_load_5 : IN STD_LOGIC_VECTOR (7 downto 0);
    W_hidden_1_load_6 : IN STD_LOGIC_VECTOR (7 downto 0);
    W_hidden_load_6 : IN STD_LOGIC_VECTOR (7 downto 0);
    W_hidden_1_load_7 : IN STD_LOGIC_VECTOR (7 downto 0);
    W_hidden_load_7 : IN STD_LOGIC_VECTOR (7 downto 0);
    zext_ln137 : IN STD_LOGIC_VECTOR (7 downto 0);
    x_row_5_cast : IN STD_LOGIC_VECTOR (7 downto 0);
    x_row_4_cast : IN STD_LOGIC_VECTOR (7 downto 0);
    x_row_3_cast : IN STD_LOGIC_VECTOR (7 downto 0);
    x_row_2_cast : IN STD_LOGIC_VECTOR (7 downto 0);
    x_row_1_cast : IN STD_LOGIC_VECTOR (7 downto 0);
    x_row_cast : IN STD_LOGIC_VECTOR (7 downto 0);
    hidden_out_1_out : OUT STD_LOGIC_VECTOR (7 downto 0);
    hidden_out_1_out_ap_vld : OUT STD_LOGIC;
    hidden_out_out : OUT STD_LOGIC_VECTOR (7 downto 0);
    hidden_out_out_ap_vld : OUT STD_LOGIC );
end;


architecture behav of nn_accelerator_nn_accelerator_Pipeline_compute_hidden is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_12 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010010";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln137_fu_313_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal sigmoid_lut_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal sigmoid_lut_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal x_row_cast_cast_fu_277_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal x_row_cast_cast_reg_699 : STD_LOGIC_VECTOR (15 downto 0);
    signal x_row_3_cast_cast_fu_289_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal x_row_3_cast_cast_reg_714 : STD_LOGIC_VECTOR (15 downto 0);
    signal x_row_4_cast_cast_fu_293_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal x_row_4_cast_cast_reg_719 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln137_reg_734 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln137_reg_734_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln137_reg_734_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln141_fu_325_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln141_reg_738 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln141_reg_738_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln150_fu_379_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln150_reg_766 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln150_reg_766_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln150_reg_766_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln150_reg_766_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln54_fu_555_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal j_fu_100 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal add_ln137_fu_319_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_j_2 : STD_LOGIC_VECTOR (1 downto 0);
    signal hidden_out_fu_104 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal hidden_out_2_fu_573_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal hidden_out_1_fu_108 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal hidden_out_3_fu_566_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal sigmoid_lut_ce0_local : STD_LOGIC;
    signal select_ln145_1_fu_331_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln145_2_fu_343_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln145_5_fu_355_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln145_6_fu_367_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln141_fu_390_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal acc_fu_395_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln145_fu_407_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln145_3_fu_416_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln145_4_fu_425_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln145_2_fu_434_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln145_2_fu_434_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln145_2_fu_434_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln145_3_fu_443_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln145_3_fu_443_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln145_3_fu_443_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln145_6_fu_452_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln145_6_fu_452_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln145_6_fu_452_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_608_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_fu_618_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal zext_ln145_15_fu_464_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal zext_ln145_14_fu_461_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal add_ln145_7_fu_467_p2 : STD_LOGIC_VECTOR (16 downto 0);
    attribute use_dsp48 : string;
    attribute use_dsp48 of add_ln145_7_fu_467_p2 : signal is "no";
    signal add_ln145_2_fu_471_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal grp_fu_628_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_fu_598_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal zext_ln145_18_fu_488_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal zext_ln145_17_fu_485_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal add_ln145_8_fu_491_p2 : STD_LOGIC_VECTOR (16 downto 0);
    attribute use_dsp48 of add_ln145_8_fu_491_p2 : signal is "no";
    signal add_ln145_5_fu_495_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal trunc_ln145_1_fu_501_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln145_fu_477_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln145_19_fu_505_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal zext_ln145_16_fu_481_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal acc_1_fu_515_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal tmp_fu_521_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln145_6_fu_509_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln149_fu_531_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln1_fu_537_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal idx_fu_547_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_598_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_598_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_598_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_608_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_608_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_608_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_618_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_618_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_618_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_628_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_628_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_628_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal grp_fu_598_p00 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_598_p10 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_598_p20 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_fu_608_p00 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_608_p10 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_608_p20 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_fu_618_p00 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_618_p10 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_618_p20 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_fu_628_p00 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_628_p10 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_628_p20 : STD_LOGIC_VECTOR (16 downto 0);
    signal mul_ln145_2_fu_434_p00 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln145_3_fu_443_p00 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln145_6_fu_452_p00 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component nn_accelerator_mul_8ns_8ns_16_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        dout : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component nn_accelerator_mac_muladd_8ns_8ns_16ns_17_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        din2 : IN STD_LOGIC_VECTOR (15 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (16 downto 0) );
    end component;


    component nn_accelerator_nn_accelerator_Pipeline_compute_hidden_sigmoid_lut_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (7 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component nn_accelerator_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    sigmoid_lut_U : component nn_accelerator_nn_accelerator_Pipeline_compute_hidden_sigmoid_lut_ROM_AUTO_1R
    generic map (
        DataWidth => 8,
        AddressRange => 256,
        AddressWidth => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => sigmoid_lut_address0,
        ce0 => sigmoid_lut_ce0_local,
        q0 => sigmoid_lut_q0);

    mul_8ns_8ns_16_1_1_U26 : component nn_accelerator_mul_8ns_8ns_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        dout_WIDTH => 16)
    port map (
        din0 => mul_ln145_2_fu_434_p0,
        din1 => mul_ln145_2_fu_434_p1,
        dout => mul_ln145_2_fu_434_p2);

    mul_8ns_8ns_16_1_1_U27 : component nn_accelerator_mul_8ns_8ns_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        dout_WIDTH => 16)
    port map (
        din0 => mul_ln145_3_fu_443_p0,
        din1 => mul_ln145_3_fu_443_p1,
        dout => mul_ln145_3_fu_443_p2);

    mul_8ns_8ns_16_1_1_U28 : component nn_accelerator_mul_8ns_8ns_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        dout_WIDTH => 16)
    port map (
        din0 => mul_ln145_6_fu_452_p0,
        din1 => mul_ln145_6_fu_452_p1,
        dout => mul_ln145_6_fu_452_p2);

    mac_muladd_8ns_8ns_16ns_17_4_1_U29 : component nn_accelerator_mac_muladd_8ns_8ns_16ns_17_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 16,
        dout_WIDTH => 17)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_598_p0,
        din1 => grp_fu_598_p1,
        din2 => grp_fu_598_p2,
        ce => ap_const_logic_1,
        dout => grp_fu_598_p3);

    mac_muladd_8ns_8ns_16ns_17_4_1_U30 : component nn_accelerator_mac_muladd_8ns_8ns_16ns_17_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 16,
        dout_WIDTH => 17)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_608_p0,
        din1 => grp_fu_608_p1,
        din2 => grp_fu_608_p2,
        ce => ap_const_logic_1,
        dout => grp_fu_608_p3);

    mac_muladd_8ns_8ns_16ns_17_4_1_U31 : component nn_accelerator_mac_muladd_8ns_8ns_16ns_17_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 16,
        dout_WIDTH => 17)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_618_p0,
        din1 => grp_fu_618_p1,
        din2 => grp_fu_618_p2,
        ce => ap_const_logic_1,
        dout => grp_fu_618_p3);

    mac_muladd_8ns_8ns_16ns_17_4_1_U32 : component nn_accelerator_mac_muladd_8ns_8ns_16ns_17_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 16,
        dout_WIDTH => 17)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_628_p0,
        din1 => grp_fu_628_p1,
        din2 => grp_fu_628_p2,
        ce => ap_const_logic_1,
        dout => grp_fu_628_p3);

    flow_control_loop_pipe_sequential_init_U : component nn_accelerator_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter3_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    j_fu_100_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln137_fu_313_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    j_fu_100 <= add_ln137_fu_319_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    j_fu_100 <= ap_const_lv2_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                icmp_ln137_reg_734 <= icmp_ln137_fu_313_p2;
                icmp_ln137_reg_734_pp0_iter1_reg <= icmp_ln137_reg_734;
                icmp_ln141_reg_738 <= icmp_ln141_fu_325_p2;
                icmp_ln141_reg_738_pp0_iter1_reg <= icmp_ln141_reg_738;
                icmp_ln150_reg_766 <= icmp_ln150_fu_379_p2;
                icmp_ln150_reg_766_pp0_iter1_reg <= icmp_ln150_reg_766;
                    x_row_3_cast_cast_reg_714(7 downto 0) <= x_row_3_cast_cast_fu_289_p1(7 downto 0);
                    x_row_4_cast_cast_reg_719(7 downto 0) <= x_row_4_cast_cast_fu_293_p1(7 downto 0);
                    x_row_cast_cast_reg_699(7 downto 0) <= x_row_cast_cast_fu_277_p1(7 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                icmp_ln137_reg_734_pp0_iter2_reg <= icmp_ln137_reg_734_pp0_iter1_reg;
                icmp_ln150_reg_766_pp0_iter2_reg <= icmp_ln150_reg_766_pp0_iter1_reg;
                icmp_ln150_reg_766_pp0_iter3_reg <= icmp_ln150_reg_766_pp0_iter2_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then
                hidden_out_1_fu_108 <= hidden_out_3_fu_566_p3;
                hidden_out_fu_104 <= hidden_out_2_fu_573_p3;
            end if;
        end if;
    end process;
    x_row_cast_cast_reg_699(15 downto 8) <= "00000000";
    x_row_3_cast_cast_reg_714(15 downto 8) <= "00000000";
    x_row_4_cast_cast_reg_719(15 downto 8) <= "00000000";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    acc_1_fu_515_p2 <= std_logic_vector(unsigned(zext_ln145_19_fu_505_p1) + unsigned(zext_ln145_16_fu_481_p1));
    acc_fu_395_p3 <= (select_ln141_fu_390_p3 & ap_const_lv8_0);
    add_ln137_fu_319_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_j_2) + unsigned(ap_const_lv2_1));
    add_ln145_2_fu_471_p2 <= std_logic_vector(unsigned(zext_ln145_15_fu_464_p1) + unsigned(zext_ln145_14_fu_461_p1));
    add_ln145_5_fu_495_p2 <= std_logic_vector(unsigned(zext_ln145_18_fu_488_p1) + unsigned(zext_ln145_17_fu_485_p1));
    add_ln145_6_fu_509_p2 <= std_logic_vector(unsigned(trunc_ln145_1_fu_501_p1) + unsigned(trunc_ln145_fu_477_p1));
    add_ln145_7_fu_467_p2 <= std_logic_vector(unsigned(grp_fu_618_p3) + unsigned(grp_fu_608_p3));
    add_ln145_8_fu_491_p2 <= std_logic_vector(unsigned(grp_fu_598_p3) + unsigned(grp_fu_628_p3));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_01001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln137_fu_313_p2)
    begin
        if (((icmp_ln137_fu_313_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_loop_exit_ready_pp0_iter3_reg, ap_done_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter3_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_j_2_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, j_fu_100, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_j_2 <= ap_const_lv2_0;
        else 
            ap_sig_allocacmp_j_2 <= j_fu_100;
        end if; 
    end process;

    grp_fu_598_p0 <= grp_fu_598_p00(8 - 1 downto 0);
    grp_fu_598_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln145_6_fu_367_p3),16));
    grp_fu_598_p1 <= grp_fu_598_p10(8 - 1 downto 0);
    grp_fu_598_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln137),16));
    grp_fu_598_p2 <= grp_fu_598_p20(16 - 1 downto 0);
    grp_fu_598_p20 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(acc_fu_395_p3),17));
    grp_fu_608_p0 <= grp_fu_608_p00(8 - 1 downto 0);
    grp_fu_608_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln145_5_fu_355_p3),16));
    grp_fu_608_p1 <= grp_fu_608_p10(8 - 1 downto 0);
    grp_fu_608_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(x_row_5_cast),16));
    grp_fu_608_p2 <= grp_fu_608_p20(16 - 1 downto 0);
    grp_fu_608_p20 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(mul_ln145_2_fu_434_p2),17));
    grp_fu_618_p0 <= grp_fu_618_p00(8 - 1 downto 0);
    grp_fu_618_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln145_2_fu_343_p3),16));
    grp_fu_618_p1 <= grp_fu_618_p10(8 - 1 downto 0);
    grp_fu_618_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(x_row_2_cast),16));
    grp_fu_618_p2 <= grp_fu_618_p20(16 - 1 downto 0);
    grp_fu_618_p20 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(mul_ln145_3_fu_443_p2),17));
    grp_fu_628_p0 <= grp_fu_628_p00(8 - 1 downto 0);
    grp_fu_628_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln145_1_fu_331_p3),16));
    grp_fu_628_p1 <= grp_fu_628_p10(8 - 1 downto 0);
    grp_fu_628_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(x_row_1_cast),16));
    grp_fu_628_p2 <= grp_fu_628_p20(16 - 1 downto 0);
    grp_fu_628_p20 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(mul_ln145_6_fu_452_p2),17));
    hidden_out_1_out <= hidden_out_1_fu_108;

    hidden_out_1_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln137_reg_734_pp0_iter2_reg, ap_loop_exit_ready_pp0_iter3_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter3_reg = ap_const_logic_1) and (icmp_ln137_reg_734_pp0_iter2_reg = ap_const_lv1_1))) then 
            hidden_out_1_out_ap_vld <= ap_const_logic_1;
        else 
            hidden_out_1_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    hidden_out_2_fu_573_p3 <= 
        sigmoid_lut_q0 when (icmp_ln150_reg_766_pp0_iter3_reg(0) = '1') else 
        hidden_out_fu_104;
    hidden_out_3_fu_566_p3 <= 
        hidden_out_1_fu_108 when (icmp_ln150_reg_766_pp0_iter3_reg(0) = '1') else 
        sigmoid_lut_q0;
    hidden_out_out <= hidden_out_fu_104;

    hidden_out_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln137_reg_734_pp0_iter2_reg, ap_loop_exit_ready_pp0_iter3_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter3_reg = ap_const_logic_1) and (icmp_ln137_reg_734_pp0_iter2_reg = ap_const_lv1_1))) then 
            hidden_out_out_ap_vld <= ap_const_logic_1;
        else 
            hidden_out_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln137_fu_313_p2 <= "1" when (ap_sig_allocacmp_j_2 = ap_const_lv2_2) else "0";
    icmp_ln141_fu_325_p2 <= "1" when (ap_sig_allocacmp_j_2 = ap_const_lv2_1) else "0";
    icmp_ln149_fu_531_p2 <= "0" when (tmp_fu_521_p4 = ap_const_lv3_0) else "1";
    icmp_ln150_fu_379_p2 <= "1" when (ap_sig_allocacmp_j_2 = ap_const_lv2_0) else "0";
    idx_fu_547_p3 <= 
        ap_const_lv8_FF when (icmp_ln149_fu_531_p2(0) = '1') else 
        trunc_ln1_fu_537_p4;
    mul_ln145_2_fu_434_p0 <= mul_ln145_2_fu_434_p00(8 - 1 downto 0);
    mul_ln145_2_fu_434_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln145_4_fu_425_p3),16));
    mul_ln145_2_fu_434_p1 <= x_row_4_cast_cast_reg_719(8 - 1 downto 0);
    mul_ln145_3_fu_443_p0 <= mul_ln145_3_fu_443_p00(8 - 1 downto 0);
    mul_ln145_3_fu_443_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln145_3_fu_416_p3),16));
    mul_ln145_3_fu_443_p1 <= x_row_3_cast_cast_reg_714(8 - 1 downto 0);
    mul_ln145_6_fu_452_p0 <= mul_ln145_6_fu_452_p00(8 - 1 downto 0);
    mul_ln145_6_fu_452_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln145_fu_407_p3),16));
    mul_ln145_6_fu_452_p1 <= x_row_cast_cast_reg_699(8 - 1 downto 0);
    select_ln141_fu_390_p3 <= 
        W_hidden_1_load when (icmp_ln141_reg_738_pp0_iter1_reg(0) = '1') else 
        W_hidden_load;
    select_ln145_1_fu_331_p3 <= 
        W_hidden_1_load_2 when (icmp_ln141_fu_325_p2(0) = '1') else 
        W_hidden_load_2;
    select_ln145_2_fu_343_p3 <= 
        W_hidden_1_load_3 when (icmp_ln141_fu_325_p2(0) = '1') else 
        W_hidden_load_3;
    select_ln145_3_fu_416_p3 <= 
        W_hidden_1_load_4 when (icmp_ln141_reg_738_pp0_iter1_reg(0) = '1') else 
        W_hidden_load_4;
    select_ln145_4_fu_425_p3 <= 
        W_hidden_1_load_5 when (icmp_ln141_reg_738_pp0_iter1_reg(0) = '1') else 
        W_hidden_load_5;
    select_ln145_5_fu_355_p3 <= 
        W_hidden_1_load_6 when (icmp_ln141_fu_325_p2(0) = '1') else 
        W_hidden_load_6;
    select_ln145_6_fu_367_p3 <= 
        W_hidden_1_load_7 when (icmp_ln141_fu_325_p2(0) = '1') else 
        W_hidden_load_7;
    select_ln145_fu_407_p3 <= 
        W_hidden_1_load_1 when (icmp_ln141_reg_738_pp0_iter1_reg(0) = '1') else 
        W_hidden_load_1;
    sigmoid_lut_address0 <= zext_ln54_fu_555_p1(8 - 1 downto 0);

    sigmoid_lut_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            sigmoid_lut_ce0_local <= ap_const_logic_1;
        else 
            sigmoid_lut_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    tmp_fu_521_p4 <= acc_1_fu_515_p2(18 downto 16);
    trunc_ln145_1_fu_501_p1 <= add_ln145_8_fu_491_p2(16 - 1 downto 0);
    trunc_ln145_fu_477_p1 <= add_ln145_7_fu_467_p2(16 - 1 downto 0);
    trunc_ln1_fu_537_p4 <= add_ln145_6_fu_509_p2(15 downto 8);
    x_row_3_cast_cast_fu_289_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(x_row_3_cast),16));
    x_row_4_cast_cast_fu_293_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(x_row_4_cast),16));
    x_row_cast_cast_fu_277_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(x_row_cast),16));
    zext_ln145_14_fu_461_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(grp_fu_608_p3),18));
    zext_ln145_15_fu_464_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(grp_fu_618_p3),18));
    zext_ln145_16_fu_481_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln145_2_fu_471_p2),19));
    zext_ln145_17_fu_485_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(grp_fu_628_p3),18));
    zext_ln145_18_fu_488_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(grp_fu_598_p3),18));
    zext_ln145_19_fu_505_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln145_5_fu_495_p2),19));
    zext_ln54_fu_555_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(idx_fu_547_p3),64));
end behav;
