-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity nn_accelerator_nn_accelerator_Pipeline_hidden_layer_VITIS_LOOP_106_4 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    X_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    X_ce0 : OUT STD_LOGIC;
    X_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    X_1_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    X_1_ce0 : OUT STD_LOGIC;
    X_1_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    X_2_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    X_2_ce0 : OUT STD_LOGIC;
    X_2_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    X_3_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    X_3_ce0 : OUT STD_LOGIC;
    X_3_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    X_4_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    X_4_ce0 : OUT STD_LOGIC;
    X_4_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    X_5_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    X_5_ce0 : OUT STD_LOGIC;
    X_5_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    X_6_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    X_6_ce0 : OUT STD_LOGIC;
    X_6_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    hidden_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    hidden_ce0 : OUT STD_LOGIC;
    hidden_we0 : OUT STD_LOGIC;
    hidden_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    W_hidden_1_load : IN STD_LOGIC_VECTOR (7 downto 0);
    W_hidden_load : IN STD_LOGIC_VECTOR (7 downto 0);
    W_hidden_1_load_1 : IN STD_LOGIC_VECTOR (7 downto 0);
    W_hidden_load_1 : IN STD_LOGIC_VECTOR (7 downto 0);
    W_hidden_1_load_2 : IN STD_LOGIC_VECTOR (7 downto 0);
    W_hidden_load_2 : IN STD_LOGIC_VECTOR (7 downto 0);
    W_hidden_1_load_3 : IN STD_LOGIC_VECTOR (7 downto 0);
    W_hidden_load_3 : IN STD_LOGIC_VECTOR (7 downto 0);
    W_hidden_1_load_4 : IN STD_LOGIC_VECTOR (7 downto 0);
    W_hidden_load_4 : IN STD_LOGIC_VECTOR (7 downto 0);
    W_hidden_1_load_5 : IN STD_LOGIC_VECTOR (7 downto 0);
    W_hidden_load_5 : IN STD_LOGIC_VECTOR (7 downto 0);
    W_hidden_1_load_6 : IN STD_LOGIC_VECTOR (7 downto 0);
    W_hidden_load_6 : IN STD_LOGIC_VECTOR (7 downto 0);
    W_hidden_1_load_7 : IN STD_LOGIC_VECTOR (7 downto 0);
    W_hidden_load_7 : IN STD_LOGIC_VECTOR (7 downto 0) );
end;


architecture behav of nn_accelerator_nn_accelerator_Pipeline_hidden_layer_VITIS_LOOP_106_4 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv8_80 : STD_LOGIC_VECTOR (7 downto 0) := "10000000";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv7_1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln105_fu_342_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal sigmoid_lut_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal sigmoid_lut_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal and_ln73_fu_382_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln73_reg_734 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln73_reg_734_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln73_reg_734_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln73_reg_734_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln73_reg_734_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln105_fu_396_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal trunc_ln105_reg_747 : STD_LOGIC_VECTOR (5 downto 0);
    signal trunc_ln105_reg_747_pp0_iter1_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal trunc_ln105_reg_747_pp0_iter2_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal trunc_ln105_reg_747_pp0_iter3_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal trunc_ln105_reg_747_pp0_iter4_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal zext_ln105_fu_400_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln105_reg_752 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln105_reg_752_pp0_iter1_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal mul_ln111_1_fu_535_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln111_3_fu_541_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln111_5_fu_547_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln55_fu_577_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln116_fu_588_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal j_fu_98 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal select_ln106_fu_408_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_j_load : STD_LOGIC_VECTOR (1 downto 0);
    signal i_fu_102 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    signal select_ln105_fu_388_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_sig_allocacmp_i_load : STD_LOGIC_VECTOR (6 downto 0);
    signal indvar_flatten13_fu_106 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal add_ln105_1_fu_348_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_sig_allocacmp_indvar_flatten13_load : STD_LOGIC_VECTOR (7 downto 0);
    signal X_ce0_local : STD_LOGIC;
    signal X_2_ce0_local : STD_LOGIC;
    signal X_4_ce0_local : STD_LOGIC;
    signal X_6_ce0_local : STD_LOGIC;
    signal X_1_ce0_local : STD_LOGIC;
    signal X_3_ce0_local : STD_LOGIC;
    signal X_5_ce0_local : STD_LOGIC;
    signal sigmoid_lut_ce0_local : STD_LOGIC;
    signal hidden_we0_local : STD_LOGIC;
    signal hidden_ce0_local : STD_LOGIC;
    signal icmp_ln106_fu_370_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln73_fu_360_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln73_fu_376_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln105_fu_364_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal select_ln111_fu_447_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln111_2_fu_456_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln111_4_fu_465_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln111_6_fu_474_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln108_fu_495_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln111_1_fu_508_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln111_3_fu_517_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln111_5_fu_526_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln111_1_fu_535_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln111_1_fu_535_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln111_3_fu_541_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln111_3_fu_541_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln111_5_fu_547_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln111_5_fu_547_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_611_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_620_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_593_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_602_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln111_5_fu_557_p2 : STD_LOGIC_VECTOR (15 downto 0);
    attribute use_dsp48 : string;
    attribute use_dsp48 of add_ln111_5_fu_557_p2 : signal is "no";
    signal add_ln111_2_fu_553_p2 : STD_LOGIC_VECTOR (15 downto 0);
    attribute use_dsp48 of add_ln111_2_fu_553_p2 : signal is "no";
    signal acc_fu_561_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal acc_7_fu_567_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln_fu_582_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_fu_593_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_593_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_602_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_602_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_611_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_611_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_620_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_620_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_620_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal grp_fu_593_p00 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_593_p10 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_602_p00 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_602_p10 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_611_p00 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_611_p10 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_620_p00 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_620_p10 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln111_1_fu_535_p00 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln111_1_fu_535_p10 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln111_3_fu_541_p00 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln111_3_fu_541_p10 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln111_5_fu_547_p00 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln111_5_fu_547_p10 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component nn_accelerator_mul_8ns_8ns_16_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        dout : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component nn_accelerator_mac_muladd_8ns_8ns_16ns_16_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        din2 : IN STD_LOGIC_VECTOR (15 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component nn_accelerator_nn_accelerator_Pipeline_hidden_layer_VITIS_LOOP_106_4_sigmoid_lut_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (7 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component nn_accelerator_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    sigmoid_lut_U : component nn_accelerator_nn_accelerator_Pipeline_hidden_layer_VITIS_LOOP_106_4_sigmoid_lut_ROM_AUTO_1R
    generic map (
        DataWidth => 8,
        AddressRange => 256,
        AddressWidth => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => sigmoid_lut_address0,
        ce0 => sigmoid_lut_ce0_local,
        q0 => sigmoid_lut_q0);

    mul_8ns_8ns_16_1_1_U25 : component nn_accelerator_mul_8ns_8ns_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        dout_WIDTH => 16)
    port map (
        din0 => mul_ln111_1_fu_535_p0,
        din1 => mul_ln111_1_fu_535_p1,
        dout => mul_ln111_1_fu_535_p2);

    mul_8ns_8ns_16_1_1_U26 : component nn_accelerator_mul_8ns_8ns_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        dout_WIDTH => 16)
    port map (
        din0 => mul_ln111_3_fu_541_p0,
        din1 => mul_ln111_3_fu_541_p1,
        dout => mul_ln111_3_fu_541_p2);

    mul_8ns_8ns_16_1_1_U27 : component nn_accelerator_mul_8ns_8ns_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        dout_WIDTH => 16)
    port map (
        din0 => mul_ln111_5_fu_547_p0,
        din1 => mul_ln111_5_fu_547_p1,
        dout => mul_ln111_5_fu_547_p2);

    mac_muladd_8ns_8ns_16ns_16_4_1_U28 : component nn_accelerator_mac_muladd_8ns_8ns_16ns_16_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 16,
        dout_WIDTH => 16)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_593_p0,
        din1 => grp_fu_593_p1,
        din2 => mul_ln111_1_fu_535_p2,
        ce => ap_const_logic_1,
        dout => grp_fu_593_p3);

    mac_muladd_8ns_8ns_16ns_16_4_1_U29 : component nn_accelerator_mac_muladd_8ns_8ns_16ns_16_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 16,
        dout_WIDTH => 16)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_602_p0,
        din1 => grp_fu_602_p1,
        din2 => mul_ln111_3_fu_541_p2,
        ce => ap_const_logic_1,
        dout => grp_fu_602_p3);

    mac_muladd_8ns_8ns_16ns_16_4_1_U30 : component nn_accelerator_mac_muladd_8ns_8ns_16ns_16_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 16,
        dout_WIDTH => 16)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_611_p0,
        din1 => grp_fu_611_p1,
        din2 => mul_ln111_5_fu_547_p2,
        ce => ap_const_logic_1,
        dout => grp_fu_611_p3);

    mac_muladd_8ns_8ns_16ns_16_4_1_U31 : component nn_accelerator_mac_muladd_8ns_8ns_16ns_16_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 16,
        dout_WIDTH => 16)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_620_p0,
        din1 => grp_fu_620_p1,
        din2 => grp_fu_620_p2,
        ce => ap_const_logic_1,
        dout => grp_fu_620_p3);

    flow_control_loop_pipe_sequential_init_U : component nn_accelerator_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter4_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    i_fu_102_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln105_fu_342_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    i_fu_102 <= select_ln105_fu_388_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_102 <= ap_const_lv7_0;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten13_fu_106_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln105_fu_342_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    indvar_flatten13_fu_106 <= add_ln105_1_fu_348_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten13_fu_106 <= ap_const_lv8_0;
                end if;
            end if; 
        end if;
    end process;

    j_fu_98_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln105_fu_342_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    j_fu_98 <= select_ln106_fu_408_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    j_fu_98 <= ap_const_lv2_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                and_ln73_reg_734 <= and_ln73_fu_382_p2;
                and_ln73_reg_734_pp0_iter1_reg <= and_ln73_reg_734;
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                trunc_ln105_reg_747 <= trunc_ln105_fu_396_p1;
                trunc_ln105_reg_747_pp0_iter1_reg <= trunc_ln105_reg_747;
                    zext_ln105_reg_752(6 downto 0) <= zext_ln105_fu_400_p1(6 downto 0);
                    zext_ln105_reg_752_pp0_iter1_reg(6 downto 0) <= zext_ln105_reg_752(6 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                and_ln73_reg_734_pp0_iter2_reg <= and_ln73_reg_734_pp0_iter1_reg;
                and_ln73_reg_734_pp0_iter3_reg <= and_ln73_reg_734_pp0_iter2_reg;
                and_ln73_reg_734_pp0_iter4_reg <= and_ln73_reg_734_pp0_iter3_reg;
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                trunc_ln105_reg_747_pp0_iter2_reg <= trunc_ln105_reg_747_pp0_iter1_reg;
                trunc_ln105_reg_747_pp0_iter3_reg <= trunc_ln105_reg_747_pp0_iter2_reg;
                trunc_ln105_reg_747_pp0_iter4_reg <= trunc_ln105_reg_747_pp0_iter3_reg;
            end if;
        end if;
    end process;
    zext_ln105_reg_752(63 downto 7) <= "000000000000000000000000000000000000000000000000000000000";
    zext_ln105_reg_752_pp0_iter1_reg(63 downto 7) <= "000000000000000000000000000000000000000000000000000000000";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    X_1_address0 <= zext_ln105_reg_752_pp0_iter1_reg(6 - 1 downto 0);
    X_1_ce0 <= X_1_ce0_local;

    X_1_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            X_1_ce0_local <= ap_const_logic_1;
        else 
            X_1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    X_2_address0 <= zext_ln105_fu_400_p1(6 - 1 downto 0);
    X_2_ce0 <= X_2_ce0_local;

    X_2_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            X_2_ce0_local <= ap_const_logic_1;
        else 
            X_2_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    X_3_address0 <= zext_ln105_reg_752_pp0_iter1_reg(6 - 1 downto 0);
    X_3_ce0 <= X_3_ce0_local;

    X_3_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            X_3_ce0_local <= ap_const_logic_1;
        else 
            X_3_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    X_4_address0 <= zext_ln105_fu_400_p1(6 - 1 downto 0);
    X_4_ce0 <= X_4_ce0_local;

    X_4_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            X_4_ce0_local <= ap_const_logic_1;
        else 
            X_4_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    X_5_address0 <= zext_ln105_reg_752_pp0_iter1_reg(6 - 1 downto 0);
    X_5_ce0 <= X_5_ce0_local;

    X_5_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            X_5_ce0_local <= ap_const_logic_1;
        else 
            X_5_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    X_6_address0 <= zext_ln105_fu_400_p1(6 - 1 downto 0);
    X_6_ce0 <= X_6_ce0_local;

    X_6_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            X_6_ce0_local <= ap_const_logic_1;
        else 
            X_6_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    X_address0 <= zext_ln105_fu_400_p1(6 - 1 downto 0);
    X_ce0 <= X_ce0_local;

    X_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            X_ce0_local <= ap_const_logic_1;
        else 
            X_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    acc_7_fu_567_p4 <= acc_fu_561_p2(15 downto 8);
    acc_fu_561_p2 <= std_logic_vector(unsigned(add_ln111_5_fu_557_p2) + unsigned(add_ln111_2_fu_553_p2));
    add_ln105_1_fu_348_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten13_load) + unsigned(ap_const_lv8_1));
    add_ln105_fu_364_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i_load) + unsigned(ap_const_lv7_1));
    add_ln111_2_fu_553_p2 <= std_logic_vector(unsigned(grp_fu_611_p3) + unsigned(grp_fu_620_p3));
    add_ln111_5_fu_557_p2 <= std_logic_vector(unsigned(grp_fu_593_p3) + unsigned(grp_fu_602_p3));
    add_ln_fu_582_p3 <= (trunc_ln105_reg_747_pp0_iter4_reg & and_ln73_reg_734_pp0_iter4_reg);
    and_ln73_fu_382_p2 <= (xor_ln73_fu_376_p2 and trunc_ln73_fu_360_p1);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln105_fu_342_p2)
    begin
        if (((icmp_ln105_fu_342_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter4_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter4_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5)
    begin
        if (((ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, i_fu_102)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_i_load <= ap_const_lv7_0;
        else 
            ap_sig_allocacmp_i_load <= i_fu_102;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten13_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, indvar_flatten13_fu_106)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_indvar_flatten13_load <= ap_const_lv8_0;
        else 
            ap_sig_allocacmp_indvar_flatten13_load <= indvar_flatten13_fu_106;
        end if; 
    end process;


    ap_sig_allocacmp_j_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, j_fu_98, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_j_load <= ap_const_lv2_0;
        else 
            ap_sig_allocacmp_j_load <= j_fu_98;
        end if; 
    end process;

    grp_fu_593_p0 <= grp_fu_593_p00(8 - 1 downto 0);
    grp_fu_593_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln111_6_fu_474_p3),16));
    grp_fu_593_p1 <= grp_fu_593_p10(8 - 1 downto 0);
    grp_fu_593_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(X_6_q0),16));
    grp_fu_602_p0 <= grp_fu_602_p00(8 - 1 downto 0);
    grp_fu_602_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln111_4_fu_465_p3),16));
    grp_fu_602_p1 <= grp_fu_602_p10(8 - 1 downto 0);
    grp_fu_602_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(X_4_q0),16));
    grp_fu_611_p0 <= grp_fu_611_p00(8 - 1 downto 0);
    grp_fu_611_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln111_2_fu_456_p3),16));
    grp_fu_611_p1 <= grp_fu_611_p10(8 - 1 downto 0);
    grp_fu_611_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(X_2_q0),16));
    grp_fu_620_p0 <= grp_fu_620_p00(8 - 1 downto 0);
    grp_fu_620_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln111_fu_447_p3),16));
    grp_fu_620_p1 <= grp_fu_620_p10(8 - 1 downto 0);
    grp_fu_620_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(X_q0),16));
    grp_fu_620_p2 <= (select_ln108_fu_495_p3 & ap_const_lv8_0);
    hidden_address0 <= zext_ln116_fu_588_p1(7 - 1 downto 0);
    hidden_ce0 <= hidden_ce0_local;

    hidden_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter5, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1))) then 
            hidden_ce0_local <= ap_const_logic_1;
        else 
            hidden_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    hidden_d0 <= sigmoid_lut_q0;
    hidden_we0 <= hidden_we0_local;

    hidden_we0_local_assign_proc : process(ap_enable_reg_pp0_iter5, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1))) then 
            hidden_we0_local <= ap_const_logic_1;
        else 
            hidden_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln105_fu_342_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten13_load = ap_const_lv8_80) else "0";
    icmp_ln106_fu_370_p2 <= "1" when (ap_sig_allocacmp_j_load = ap_const_lv2_2) else "0";
    mul_ln111_1_fu_535_p0 <= mul_ln111_1_fu_535_p00(8 - 1 downto 0);
    mul_ln111_1_fu_535_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln111_5_fu_526_p3),16));
    mul_ln111_1_fu_535_p1 <= mul_ln111_1_fu_535_p10(8 - 1 downto 0);
    mul_ln111_1_fu_535_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(X_5_q0),16));
    mul_ln111_3_fu_541_p0 <= mul_ln111_3_fu_541_p00(8 - 1 downto 0);
    mul_ln111_3_fu_541_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln111_3_fu_517_p3),16));
    mul_ln111_3_fu_541_p1 <= mul_ln111_3_fu_541_p10(8 - 1 downto 0);
    mul_ln111_3_fu_541_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(X_3_q0),16));
    mul_ln111_5_fu_547_p0 <= mul_ln111_5_fu_547_p00(8 - 1 downto 0);
    mul_ln111_5_fu_547_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln111_1_fu_508_p3),16));
    mul_ln111_5_fu_547_p1 <= mul_ln111_5_fu_547_p10(8 - 1 downto 0);
    mul_ln111_5_fu_547_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(X_1_q0),16));
    select_ln105_fu_388_p3 <= 
        add_ln105_fu_364_p2 when (icmp_ln106_fu_370_p2(0) = '1') else 
        ap_sig_allocacmp_i_load;
    select_ln106_fu_408_p3 <= 
        ap_const_lv2_2 when (and_ln73_fu_382_p2(0) = '1') else 
        ap_const_lv2_1;
    select_ln108_fu_495_p3 <= 
        W_hidden_1_load when (and_ln73_reg_734_pp0_iter2_reg(0) = '1') else 
        W_hidden_load;
    select_ln111_1_fu_508_p3 <= 
        W_hidden_1_load_2 when (and_ln73_reg_734_pp0_iter2_reg(0) = '1') else 
        W_hidden_load_2;
    select_ln111_2_fu_456_p3 <= 
        W_hidden_1_load_3 when (and_ln73_reg_734(0) = '1') else 
        W_hidden_load_3;
    select_ln111_3_fu_517_p3 <= 
        W_hidden_1_load_4 when (and_ln73_reg_734_pp0_iter2_reg(0) = '1') else 
        W_hidden_load_4;
    select_ln111_4_fu_465_p3 <= 
        W_hidden_1_load_5 when (and_ln73_reg_734(0) = '1') else 
        W_hidden_load_5;
    select_ln111_5_fu_526_p3 <= 
        W_hidden_1_load_6 when (and_ln73_reg_734_pp0_iter2_reg(0) = '1') else 
        W_hidden_load_6;
    select_ln111_6_fu_474_p3 <= 
        W_hidden_1_load_7 when (and_ln73_reg_734(0) = '1') else 
        W_hidden_load_7;
    select_ln111_fu_447_p3 <= 
        W_hidden_1_load_1 when (and_ln73_reg_734(0) = '1') else 
        W_hidden_load_1;
    sigmoid_lut_address0 <= zext_ln55_fu_577_p1(8 - 1 downto 0);

    sigmoid_lut_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            sigmoid_lut_ce0_local <= ap_const_logic_1;
        else 
            sigmoid_lut_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    trunc_ln105_fu_396_p1 <= select_ln105_fu_388_p3(6 - 1 downto 0);
    trunc_ln73_fu_360_p1 <= ap_sig_allocacmp_j_load(1 - 1 downto 0);
    xor_ln73_fu_376_p2 <= (icmp_ln106_fu_370_p2 xor ap_const_lv1_1);
    zext_ln105_fu_400_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln105_fu_388_p3),64));
    zext_ln116_fu_588_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln_fu_582_p3),64));
    zext_ln55_fu_577_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(acc_7_fu_567_p4),64));
end behav;
