-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity nn_accelerator_nn_accelerator_Pipeline_output_layer is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    hidden_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    hidden_ce0 : OUT STD_LOGIC;
    hidden_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    hidden_address1 : OUT STD_LOGIC_VECTOR (6 downto 0);
    hidden_ce1 : OUT STD_LOGIC;
    hidden_q1 : IN STD_LOGIC_VECTOR (7 downto 0);
    output_data_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    output_data_ce0 : OUT STD_LOGIC;
    output_data_we0 : OUT STD_LOGIC;
    output_data_d0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    conv3_i_i85 : IN STD_LOGIC_VECTOR (7 downto 0);
    conv3_i_i85_1 : IN STD_LOGIC_VECTOR (7 downto 0);
    acc : IN STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of nn_accelerator_nn_accelerator_Pipeline_output_layer is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv7_40 : STD_LOGIC_VECTOR (6 downto 0) := "1000000";
    constant ap_const_lv7_1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv16_8100 : STD_LOGIC_VECTOR (15 downto 0) := "1000000100000000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv8_80 : STD_LOGIC_VECTOR (7 downto 0) := "10000000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln121_fu_132_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal conv3_i_i85_1_cast_fu_116_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal conv3_i_i85_1_cast_reg_254 : STD_LOGIC_VECTOR (15 downto 0);
    signal conv3_i_i85_cast_fu_120_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal conv3_i_i85_cast_reg_259 : STD_LOGIC_VECTOR (15 downto 0);
    signal i_2_reg_264 : STD_LOGIC_VECTOR (6 downto 0);
    signal i_2_reg_264_pp0_iter1_reg : STD_LOGIC_VECTOR (6 downto 0);
    signal i_2_reg_264_pp0_iter2_reg : STD_LOGIC_VECTOR (6 downto 0);
    signal i_2_reg_264_pp0_iter3_reg : STD_LOGIC_VECTOR (6 downto 0);
    signal i_2_reg_264_pp0_iter4_reg : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_fu_227_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln127_3_fu_156_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln127_2_fu_171_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln121_fu_184_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal i_fu_56 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    signal add_ln121_fu_138_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_i_2 : STD_LOGIC_VECTOR (6 downto 0);
    signal hidden_ce1_local : STD_LOGIC;
    signal hidden_ce0_local : STD_LOGIC;
    signal output_data_we0_local : STD_LOGIC;
    signal or_ln134_fu_220_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal output_data_ce0_local : STD_LOGIC;
    signal trunc_ln121_fu_144_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_2_fu_148_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal shl_ln127_fu_166_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_fu_233_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln132_fu_197_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln2_fu_188_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal acc_2_fu_202_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln133_fu_214_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln75_fu_210_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_227_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_227_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_233_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_233_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal grp_fu_227_p00 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_233_p00 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component nn_accelerator_mac_muladd_8ns_8ns_16ns_16_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        din2 : IN STD_LOGIC_VECTOR (15 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component nn_accelerator_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    mac_muladd_8ns_8ns_16ns_16_4_1_U59 : component nn_accelerator_mac_muladd_8ns_8ns_16ns_16_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 16,
        dout_WIDTH => 16)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_227_p0,
        din1 => grp_fu_227_p1,
        din2 => acc,
        ce => ap_const_logic_1,
        dout => grp_fu_227_p3);

    mac_muladd_8ns_8ns_16ns_16_4_1_U60 : component nn_accelerator_mac_muladd_8ns_8ns_16ns_16_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 16,
        dout_WIDTH => 16)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_233_p0,
        din1 => grp_fu_233_p1,
        din2 => grp_fu_227_p3,
        ce => ap_const_logic_1,
        dout => grp_fu_233_p3);

    flow_control_loop_pipe_sequential_init_U : component nn_accelerator_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter4_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    i_fu_56_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln121_fu_132_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    i_fu_56 <= add_ln121_fu_138_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_56 <= ap_const_lv7_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                    conv3_i_i85_1_cast_reg_254(7 downto 0) <= conv3_i_i85_1_cast_fu_116_p1(7 downto 0);
                    conv3_i_i85_cast_reg_259(7 downto 0) <= conv3_i_i85_cast_fu_120_p1(7 downto 0);
                i_2_reg_264 <= ap_sig_allocacmp_i_2;
                i_2_reg_264_pp0_iter1_reg <= i_2_reg_264;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                i_2_reg_264_pp0_iter2_reg <= i_2_reg_264_pp0_iter1_reg;
                i_2_reg_264_pp0_iter3_reg <= i_2_reg_264_pp0_iter2_reg;
                i_2_reg_264_pp0_iter4_reg <= i_2_reg_264_pp0_iter3_reg;
            end if;
        end if;
    end process;
    conv3_i_i85_1_cast_reg_254(15 downto 8) <= "00000000";
    conv3_i_i85_cast_reg_259(15 downto 8) <= "00000000";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    acc_2_fu_202_p3 <= 
        ap_const_lv8_0 when (icmp_ln132_fu_197_p2(0) = '1') else 
        trunc_ln2_fu_188_p4;
    add_ln121_fu_138_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i_2) + unsigned(ap_const_lv7_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln121_fu_132_p2)
    begin
        if (((icmp_ln121_fu_132_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter4_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter4_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5)
    begin
        if (((ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_2_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, i_fu_56, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_i_2 <= ap_const_lv7_0;
        else 
            ap_sig_allocacmp_i_2 <= i_fu_56;
        end if; 
    end process;

    conv3_i_i85_1_cast_fu_116_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(conv3_i_i85_1),16));
    conv3_i_i85_cast_fu_120_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(conv3_i_i85),16));
    grp_fu_227_p0 <= grp_fu_227_p00(8 - 1 downto 0);
    grp_fu_227_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(hidden_q1),16));
    grp_fu_227_p1 <= conv3_i_i85_1_cast_reg_254(8 - 1 downto 0);
    grp_fu_233_p0 <= grp_fu_233_p00(8 - 1 downto 0);
    grp_fu_233_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(hidden_q0),16));
    grp_fu_233_p1 <= conv3_i_i85_cast_reg_259(8 - 1 downto 0);
    hidden_address0 <= zext_ln127_2_fu_171_p1(7 - 1 downto 0);
    hidden_address1 <= zext_ln127_3_fu_156_p1(7 - 1 downto 0);
    hidden_ce0 <= hidden_ce0_local;

    hidden_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            hidden_ce0_local <= ap_const_logic_1;
        else 
            hidden_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    hidden_ce1 <= hidden_ce1_local;

    hidden_ce1_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            hidden_ce1_local <= ap_const_logic_1;
        else 
            hidden_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln121_fu_132_p2 <= "1" when (ap_sig_allocacmp_i_2 = ap_const_lv7_40) else "0";
    icmp_ln132_fu_197_p2 <= "1" when (unsigned(grp_fu_233_p3) < unsigned(ap_const_lv16_8100)) else "0";
    icmp_ln133_fu_214_p2 <= "1" when (unsigned(acc_2_fu_202_p3) > unsigned(ap_const_lv8_80)) else "0";
    or_ln134_fu_220_p2 <= (trunc_ln75_fu_210_p1 or icmp_ln133_fu_214_p2);
    output_data_address0 <= zext_ln121_fu_184_p1(6 - 1 downto 0);
    output_data_ce0 <= output_data_ce0_local;

    output_data_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter5, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1))) then 
            output_data_ce0_local <= ap_const_logic_1;
        else 
            output_data_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    output_data_d0 <= or_ln134_fu_220_p2;
    output_data_we0 <= output_data_we0_local;

    output_data_we0_local_assign_proc : process(ap_enable_reg_pp0_iter5, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1))) then 
            output_data_we0_local <= ap_const_logic_1;
        else 
            output_data_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    shl_ln127_fu_166_p2 <= std_logic_vector(shift_left(unsigned(i_2_reg_264),to_integer(unsigned('0' & ap_const_lv7_1(7-1 downto 0)))));
    tmp_2_fu_148_p3 <= (trunc_ln121_fu_144_p1 & ap_const_lv1_1);
    trunc_ln121_fu_144_p1 <= ap_sig_allocacmp_i_2(6 - 1 downto 0);
    trunc_ln2_fu_188_p4 <= grp_fu_233_p3(15 downto 8);
    trunc_ln75_fu_210_p1 <= acc_2_fu_202_p3(1 - 1 downto 0);
    zext_ln121_fu_184_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i_2_reg_264_pp0_iter4_reg),64));
    zext_ln127_2_fu_171_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln127_fu_166_p2),64));
    zext_ln127_3_fu_156_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_2_fu_148_p3),64));
end behav;
