-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity nn_accelerator_nn_accelerator_Pipeline_read_input_data_VITIS_LOOP_97_3 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    S_AXIS_TVALID : IN STD_LOGIC;
    X_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    X_ce0 : OUT STD_LOGIC;
    X_we0 : OUT STD_LOGIC;
    X_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    X_1_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    X_1_ce0 : OUT STD_LOGIC;
    X_1_we0 : OUT STD_LOGIC;
    X_1_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    X_2_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    X_2_ce0 : OUT STD_LOGIC;
    X_2_we0 : OUT STD_LOGIC;
    X_2_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    X_3_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    X_3_ce0 : OUT STD_LOGIC;
    X_3_we0 : OUT STD_LOGIC;
    X_3_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    X_4_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    X_4_ce0 : OUT STD_LOGIC;
    X_4_we0 : OUT STD_LOGIC;
    X_4_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    X_5_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    X_5_ce0 : OUT STD_LOGIC;
    X_5_we0 : OUT STD_LOGIC;
    X_5_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    X_6_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    X_6_ce0 : OUT STD_LOGIC;
    X_6_we0 : OUT STD_LOGIC;
    X_6_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    S_AXIS_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    S_AXIS_TREADY : OUT STD_LOGIC;
    S_AXIS_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
    S_AXIS_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
    S_AXIS_TLAST : IN STD_LOGIC_VECTOR (0 downto 0) );
end;


architecture behav of nn_accelerator_nn_accelerator_Pipeline_read_input_data_VITIS_LOOP_97_3 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv3_5 : STD_LOGIC_VECTOR (2 downto 0) := "101";
    constant ap_const_lv3_4 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv3_3 : STD_LOGIC_VECTOR (2 downto 0) := "011";
    constant ap_const_lv3_2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv3_7 : STD_LOGIC_VECTOR (2 downto 0) := "111";
    constant ap_const_lv3_6 : STD_LOGIC_VECTOR (2 downto 0) := "110";
    constant ap_const_lv9_1C0 : STD_LOGIC_VECTOR (8 downto 0) := "111000000";
    constant ap_const_lv9_1 : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    constant ap_const_lv7_1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln96_fu_213_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal S_AXIS_TDATA_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_grp1 : BOOLEAN;
    signal zext_ln96_fu_264_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal j_fu_80 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    signal add_ln97_fu_306_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_block_pp0_stage0_11001_grp1 : BOOLEAN;
    signal ap_loop_init : STD_LOGIC;
    signal i_fu_84 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    signal select_ln96_fu_256_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal indvar_flatten6_fu_88 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    signal add_ln96_1_fu_219_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal ap_sig_allocacmp_indvar_flatten6_load : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal X_5_we0_local : STD_LOGIC;
    signal select_ln73_fu_248_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln100_fu_279_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal X_5_ce0_local : STD_LOGIC;
    signal X_4_we0_local : STD_LOGIC;
    signal X_4_ce0_local : STD_LOGIC;
    signal X_3_we0_local : STD_LOGIC;
    signal X_3_ce0_local : STD_LOGIC;
    signal X_2_we0_local : STD_LOGIC;
    signal X_2_ce0_local : STD_LOGIC;
    signal X_1_we0_local : STD_LOGIC;
    signal X_1_ce0_local : STD_LOGIC;
    signal X_we0_local : STD_LOGIC;
    signal X_ce0_local : STD_LOGIC;
    signal X_6_we0_local : STD_LOGIC;
    signal X_6_ce0_local : STD_LOGIC;
    signal icmp_ln97_fu_242_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln96_fu_236_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component nn_accelerator_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component nn_accelerator_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    i_fu_84_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_84 <= ap_const_lv7_0;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    i_fu_84 <= select_ln96_fu_256_p3;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten6_fu_88_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln96_fu_213_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    indvar_flatten6_fu_88 <= add_ln96_1_fu_219_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten6_fu_88 <= ap_const_lv9_0;
                end if;
            end if; 
        end if;
    end process;

    j_fu_80_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    j_fu_80 <= ap_const_lv3_0;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    j_fu_80 <= add_ln97_fu_306_p2;
                end if;
            end if; 
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;

    S_AXIS_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, S_AXIS_TVALID, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            S_AXIS_TDATA_blk_n <= S_AXIS_TVALID;
        else 
            S_AXIS_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    S_AXIS_TREADY_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            S_AXIS_TREADY <= ap_const_logic_1;
        else 
            S_AXIS_TREADY <= ap_const_logic_0;
        end if; 
    end process;

    X_1_address0 <= zext_ln96_fu_264_p1(6 - 1 downto 0);
    X_1_ce0 <= X_1_ce0_local;

    X_1_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            X_1_ce0_local <= ap_const_logic_1;
        else 
            X_1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    X_1_d0 <= trunc_ln100_fu_279_p1;
    X_1_we0 <= X_1_we0_local;

    X_1_we0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001_grp1, select_ln73_fu_248_p3)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (select_ln73_fu_248_p3 = ap_const_lv3_1))) then 
            X_1_we0_local <= ap_const_logic_1;
        else 
            X_1_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    X_2_address0 <= zext_ln96_fu_264_p1(6 - 1 downto 0);
    X_2_ce0 <= X_2_ce0_local;

    X_2_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            X_2_ce0_local <= ap_const_logic_1;
        else 
            X_2_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    X_2_d0 <= trunc_ln100_fu_279_p1;
    X_2_we0 <= X_2_we0_local;

    X_2_we0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001_grp1, select_ln73_fu_248_p3)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (select_ln73_fu_248_p3 = ap_const_lv3_2))) then 
            X_2_we0_local <= ap_const_logic_1;
        else 
            X_2_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    X_3_address0 <= zext_ln96_fu_264_p1(6 - 1 downto 0);
    X_3_ce0 <= X_3_ce0_local;

    X_3_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            X_3_ce0_local <= ap_const_logic_1;
        else 
            X_3_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    X_3_d0 <= trunc_ln100_fu_279_p1;
    X_3_we0 <= X_3_we0_local;

    X_3_we0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001_grp1, select_ln73_fu_248_p3)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (select_ln73_fu_248_p3 = ap_const_lv3_3))) then 
            X_3_we0_local <= ap_const_logic_1;
        else 
            X_3_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    X_4_address0 <= zext_ln96_fu_264_p1(6 - 1 downto 0);
    X_4_ce0 <= X_4_ce0_local;

    X_4_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            X_4_ce0_local <= ap_const_logic_1;
        else 
            X_4_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    X_4_d0 <= trunc_ln100_fu_279_p1;
    X_4_we0 <= X_4_we0_local;

    X_4_we0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001_grp1, select_ln73_fu_248_p3)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (select_ln73_fu_248_p3 = ap_const_lv3_4))) then 
            X_4_we0_local <= ap_const_logic_1;
        else 
            X_4_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    X_5_address0 <= zext_ln96_fu_264_p1(6 - 1 downto 0);
    X_5_ce0 <= X_5_ce0_local;

    X_5_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            X_5_ce0_local <= ap_const_logic_1;
        else 
            X_5_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    X_5_d0 <= trunc_ln100_fu_279_p1;
    X_5_we0 <= X_5_we0_local;

    X_5_we0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001_grp1, select_ln73_fu_248_p3)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (select_ln73_fu_248_p3 = ap_const_lv3_5))) then 
            X_5_we0_local <= ap_const_logic_1;
        else 
            X_5_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    X_6_address0 <= zext_ln96_fu_264_p1(6 - 1 downto 0);
    X_6_ce0 <= X_6_ce0_local;

    X_6_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            X_6_ce0_local <= ap_const_logic_1;
        else 
            X_6_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    X_6_d0 <= trunc_ln100_fu_279_p1;
    X_6_we0 <= X_6_we0_local;

    X_6_we0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001_grp1, select_ln73_fu_248_p3)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and ((select_ln73_fu_248_p3 = ap_const_lv3_6) or (select_ln73_fu_248_p3 = ap_const_lv3_7)))) then 
            X_6_we0_local <= ap_const_logic_1;
        else 
            X_6_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    X_address0 <= zext_ln96_fu_264_p1(6 - 1 downto 0);
    X_ce0 <= X_ce0_local;

    X_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            X_ce0_local <= ap_const_logic_1;
        else 
            X_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    X_d0 <= trunc_ln100_fu_279_p1;
    X_we0 <= X_we0_local;

    X_we0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001_grp1, select_ln73_fu_248_p3)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (select_ln73_fu_248_p3 = ap_const_lv3_0))) then 
            X_we0_local <= ap_const_logic_1;
        else 
            X_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    add_ln96_1_fu_219_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten6_load) + unsigned(ap_const_lv9_1));
    add_ln96_fu_236_p2 <= std_logic_vector(unsigned(i_fu_84) + unsigned(ap_const_lv7_1));
    add_ln97_fu_306_p2 <= std_logic_vector(unsigned(select_ln73_fu_248_p3) + unsigned(ap_const_lv3_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, S_AXIS_TVALID)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_const_logic_0 = S_AXIS_TVALID) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;


    ap_block_pp0_stage0_11001_grp1_assign_proc : process(ap_enable_reg_pp0_iter1, S_AXIS_TVALID)
    begin
                ap_block_pp0_stage0_11001_grp1 <= ((ap_const_logic_0 = S_AXIS_TVALID) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;

        ap_block_pp0_stage0_grp1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, S_AXIS_TVALID)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_const_logic_0 = S_AXIS_TVALID) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln96_fu_213_p2)
    begin
        if (((icmp_ln96_fu_213_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten6_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_loop_init, indvar_flatten6_fu_88, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_indvar_flatten6_load <= ap_const_lv9_0;
        else 
            ap_sig_allocacmp_indvar_flatten6_load <= indvar_flatten6_fu_88;
        end if; 
    end process;

    icmp_ln96_fu_213_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten6_load = ap_const_lv9_1C0) else "0";
    icmp_ln97_fu_242_p2 <= "1" when (j_fu_80 = ap_const_lv3_7) else "0";
    select_ln73_fu_248_p3 <= 
        ap_const_lv3_0 when (icmp_ln97_fu_242_p2(0) = '1') else 
        j_fu_80;
    select_ln96_fu_256_p3 <= 
        add_ln96_fu_236_p2 when (icmp_ln97_fu_242_p2(0) = '1') else 
        i_fu_84;
    trunc_ln100_fu_279_p1 <= S_AXIS_TDATA(8 - 1 downto 0);
    zext_ln96_fu_264_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln96_fu_256_p3),64));
end behav;
