// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="nn_accelerator_nn_accelerator,hls_ip_2025_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xck26-sfvc784-2LV-c,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=4.684063,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=1,HLS_SYN_DSP=0,HLS_SYN_FF=503,HLS_SYN_LUT=1109,HLS_VERSION=2025_1}" *)

module nn_accelerator (
        ap_clk,
        ap_rst_n,
        S_AXIS_TDATA,
        S_AXIS_TVALID,
        S_AXIS_TREADY,
        S_AXIS_TKEEP,
        S_AXIS_TSTRB,
        S_AXIS_TLAST,
        M_AXIS_TDATA,
        M_AXIS_TVALID,
        M_AXIS_TREADY,
        M_AXIS_TKEEP,
        M_AXIS_TSTRB,
        M_AXIS_TLAST
);

parameter    ap_ST_fsm_state1 = 18'd1;
parameter    ap_ST_fsm_state2 = 18'd2;
parameter    ap_ST_fsm_state3 = 18'd4;
parameter    ap_ST_fsm_state4 = 18'd8;
parameter    ap_ST_fsm_state5 = 18'd16;
parameter    ap_ST_fsm_state6 = 18'd32;
parameter    ap_ST_fsm_state7 = 18'd64;
parameter    ap_ST_fsm_state8 = 18'd128;
parameter    ap_ST_fsm_state9 = 18'd256;
parameter    ap_ST_fsm_state10 = 18'd512;
parameter    ap_ST_fsm_state11 = 18'd1024;
parameter    ap_ST_fsm_state12 = 18'd2048;
parameter    ap_ST_fsm_state13 = 18'd4096;
parameter    ap_ST_fsm_state14 = 18'd8192;
parameter    ap_ST_fsm_state15 = 18'd16384;
parameter    ap_ST_fsm_state16 = 18'd32768;
parameter    ap_ST_fsm_state17 = 18'd65536;
parameter    ap_ST_fsm_state18 = 18'd131072;

input   ap_clk;
input   ap_rst_n;
input  [31:0] S_AXIS_TDATA;
input   S_AXIS_TVALID;
output   S_AXIS_TREADY;
input  [3:0] S_AXIS_TKEEP;
input  [3:0] S_AXIS_TSTRB;
input  [0:0] S_AXIS_TLAST;
output  [31:0] M_AXIS_TDATA;
output   M_AXIS_TVALID;
input   M_AXIS_TREADY;
output  [3:0] M_AXIS_TKEEP;
output  [3:0] M_AXIS_TSTRB;
output  [0:0] M_AXIS_TLAST;

 reg    ap_rst_n_inv;
reg    M_AXIS_TDATA_blk_n;
(* fsm_encoding = "none" *) reg   [17:0] ap_CS_fsm;
wire    ap_CS_fsm_state17;
wire    ap_CS_fsm_state18;
wire    ap_CS_fsm_state4;
reg   [7:0] W_hidden_load_reg_591;
wire    ap_CS_fsm_state5;
reg   [7:0] W_hidden_1_load_reg_596;
reg   [7:0] W_hidden_load_1_reg_601;
reg   [7:0] W_hidden_1_load_1_reg_606;
reg   [7:0] W_hidden_load_2_reg_631;
wire    ap_CS_fsm_state6;
reg   [7:0] W_hidden_1_load_2_reg_636;
reg   [7:0] W_hidden_load_3_reg_641;
reg   [7:0] W_hidden_1_load_3_reg_646;
reg   [7:0] W_hidden_load_4_reg_671;
wire    ap_CS_fsm_state7;
reg   [7:0] W_hidden_1_load_4_reg_676;
reg   [7:0] W_hidden_load_5_reg_681;
reg   [7:0] W_hidden_1_load_5_reg_686;
wire   [16:0] acc_cast_fu_407_p1;
reg   [16:0] acc_cast_reg_711;
wire    ap_CS_fsm_state8;
wire   [15:0] p_0_0371716_cast_fu_411_p1;
reg   [15:0] p_0_0371716_cast_reg_716;
wire   [15:0] p_0_0371_1718_cast_fu_415_p1;
reg   [15:0] p_0_0371_1718_cast_reg_721;
reg   [7:0] W_hidden_load_6_reg_726;
reg   [7:0] W_hidden_1_load_6_reg_731;
reg   [7:0] W_hidden_load_7_reg_736;
reg   [7:0] W_hidden_1_load_7_reg_741;
wire    ap_CS_fsm_state13;
wire    ap_CS_fsm_state14;
wire    ap_CS_fsm_state16;
reg   [0:0] last_sample_loc_load_reg_782;
reg   [2:0] W_hidden_address0;
reg    W_hidden_ce0;
reg    W_hidden_we0;
wire   [7:0] W_hidden_q0;
wire   [7:0] W_hidden_q1;
reg   [2:0] W_hidden_1_address0;
reg    W_hidden_1_ce0;
reg    W_hidden_1_we0;
wire   [7:0] W_hidden_1_q0;
wire   [7:0] W_hidden_1_q1;
wire    grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_77_1_fu_310_ap_start;
wire    grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_77_1_fu_310_ap_done;
wire    grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_77_1_fu_310_ap_idle;
wire    grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_77_1_fu_310_ap_ready;
wire   [2:0] grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_77_1_fu_310_W_hidden_address0;
wire    grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_77_1_fu_310_W_hidden_ce0;
wire    grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_77_1_fu_310_W_hidden_we0;
wire   [7:0] grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_77_1_fu_310_W_hidden_d0;
wire   [2:0] grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_77_1_fu_310_W_hidden_1_address0;
wire    grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_77_1_fu_310_W_hidden_1_ce0;
wire    grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_77_1_fu_310_W_hidden_1_we0;
wire   [7:0] grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_77_1_fu_310_W_hidden_1_d0;
wire    grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_77_1_fu_310_S_AXIS_TREADY;
wire    grp_nn_accelerator_Pipeline_read_output_weights_fu_324_ap_start;
wire    grp_nn_accelerator_Pipeline_read_output_weights_fu_324_ap_done;
wire    grp_nn_accelerator_Pipeline_read_output_weights_fu_324_ap_idle;
wire    grp_nn_accelerator_Pipeline_read_output_weights_fu_324_ap_ready;
wire    grp_nn_accelerator_Pipeline_read_output_weights_fu_324_S_AXIS_TREADY;
wire   [7:0] grp_nn_accelerator_Pipeline_read_output_weights_fu_324_p_0_0371_1718_out;
wire    grp_nn_accelerator_Pipeline_read_output_weights_fu_324_p_0_0371_1718_out_ap_vld;
wire   [7:0] grp_nn_accelerator_Pipeline_read_output_weights_fu_324_p_0_0371716_out;
wire    grp_nn_accelerator_Pipeline_read_output_weights_fu_324_p_0_0371716_out_ap_vld;
wire   [7:0] grp_nn_accelerator_Pipeline_read_output_weights_fu_324_p_0_0377714_out;
wire    grp_nn_accelerator_Pipeline_read_output_weights_fu_324_p_0_0377714_out_ap_vld;
wire    grp_nn_accelerator_Pipeline_read_features_fu_339_ap_start;
wire    grp_nn_accelerator_Pipeline_read_features_fu_339_ap_done;
wire    grp_nn_accelerator_Pipeline_read_features_fu_339_ap_idle;
wire    grp_nn_accelerator_Pipeline_read_features_fu_339_ap_ready;
wire    grp_nn_accelerator_Pipeline_read_features_fu_339_S_AXIS_TREADY;
wire   [7:0] grp_nn_accelerator_Pipeline_read_features_fu_339_x_row_6_out;
wire    grp_nn_accelerator_Pipeline_read_features_fu_339_x_row_6_out_ap_vld;
wire   [7:0] grp_nn_accelerator_Pipeline_read_features_fu_339_x_row_5_out;
wire    grp_nn_accelerator_Pipeline_read_features_fu_339_x_row_5_out_ap_vld;
wire   [7:0] grp_nn_accelerator_Pipeline_read_features_fu_339_x_row_4_out;
wire    grp_nn_accelerator_Pipeline_read_features_fu_339_x_row_4_out_ap_vld;
wire   [7:0] grp_nn_accelerator_Pipeline_read_features_fu_339_x_row_3_out;
wire    grp_nn_accelerator_Pipeline_read_features_fu_339_x_row_3_out_ap_vld;
wire   [7:0] grp_nn_accelerator_Pipeline_read_features_fu_339_x_row_2_out;
wire    grp_nn_accelerator_Pipeline_read_features_fu_339_x_row_2_out_ap_vld;
wire   [7:0] grp_nn_accelerator_Pipeline_read_features_fu_339_x_row_1_out;
wire    grp_nn_accelerator_Pipeline_read_features_fu_339_x_row_1_out_ap_vld;
wire   [7:0] grp_nn_accelerator_Pipeline_read_features_fu_339_x_row_out;
wire    grp_nn_accelerator_Pipeline_read_features_fu_339_x_row_out_ap_vld;
wire   [0:0] grp_nn_accelerator_Pipeline_read_features_fu_339_last_sample_out;
wire    grp_nn_accelerator_Pipeline_read_features_fu_339_last_sample_out_ap_vld;
wire    grp_nn_accelerator_Pipeline_compute_hidden_fu_359_ap_start;
wire    grp_nn_accelerator_Pipeline_compute_hidden_fu_359_ap_done;
wire    grp_nn_accelerator_Pipeline_compute_hidden_fu_359_ap_idle;
wire    grp_nn_accelerator_Pipeline_compute_hidden_fu_359_ap_ready;
wire   [7:0] grp_nn_accelerator_Pipeline_compute_hidden_fu_359_hidden_out_1_out;
wire    grp_nn_accelerator_Pipeline_compute_hidden_fu_359_hidden_out_1_out_ap_vld;
wire   [7:0] grp_nn_accelerator_Pipeline_compute_hidden_fu_359_hidden_out_out;
wire    grp_nn_accelerator_Pipeline_compute_hidden_fu_359_hidden_out_out_ap_vld;
reg    grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_77_1_fu_310_ap_start_reg;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state3;
reg    grp_nn_accelerator_Pipeline_read_output_weights_fu_324_ap_start_reg;
reg    grp_nn_accelerator_Pipeline_read_features_fu_339_ap_start_reg;
wire    ap_CS_fsm_state9;
wire    ap_CS_fsm_state10;
reg    grp_nn_accelerator_Pipeline_compute_hidden_fu_359_ap_start_reg;
wire    ap_CS_fsm_state11;
wire    ap_CS_fsm_state12;
reg    W_hidden_ce1_local;
reg   [2:0] W_hidden_address1_local;
reg    W_hidden_ce0_local;
reg   [2:0] W_hidden_address0_local;
reg    W_hidden_1_ce1_local;
reg   [2:0] W_hidden_1_address1_local;
reg    W_hidden_1_ce0_local;
reg   [2:0] W_hidden_1_address0_local;
wire   [15:0] acc_fu_399_p3;
wire   [16:0] grp_fu_478_p3;
wire   [17:0] grp_fu_485_p3;
wire   [0:0] out_pkt_data_fu_468_p2;
wire   [7:0] grp_fu_478_p0;
wire   [7:0] grp_fu_478_p1;
wire   [15:0] grp_fu_478_p2;
wire    ap_CS_fsm_state15;
wire   [7:0] grp_fu_485_p0;
wire   [7:0] grp_fu_485_p1;
wire   [16:0] grp_fu_485_p2;
reg    grp_fu_485_ce;
reg   [17:0] ap_NS_fsm;
wire    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
reg    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
reg    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
reg    ap_ST_fsm_state17_blk;
wire    regslice_both_M_AXIS_V_data_V_U_apdone_blk;
reg    ap_block_state18;
reg    ap_ST_fsm_state18_blk;
wire    regslice_both_S_AXIS_V_data_V_U_apdone_blk;
wire   [31:0] S_AXIS_TDATA_int_regslice;
wire    S_AXIS_TVALID_int_regslice;
reg    S_AXIS_TREADY_int_regslice;
wire    regslice_both_S_AXIS_V_data_V_U_ack_in;
wire    regslice_both_S_AXIS_V_keep_V_U_apdone_blk;
wire   [3:0] S_AXIS_TKEEP_int_regslice;
wire    regslice_both_S_AXIS_V_keep_V_U_vld_out;
wire    regslice_both_S_AXIS_V_keep_V_U_ack_in;
wire    regslice_both_S_AXIS_V_strb_V_U_apdone_blk;
wire   [3:0] S_AXIS_TSTRB_int_regslice;
wire    regslice_both_S_AXIS_V_strb_V_U_vld_out;
wire    regslice_both_S_AXIS_V_strb_V_U_ack_in;
wire    regslice_both_S_AXIS_V_last_V_U_apdone_blk;
wire   [0:0] S_AXIS_TLAST_int_regslice;
wire    regslice_both_S_AXIS_V_last_V_U_vld_out;
wire    regslice_both_S_AXIS_V_last_V_U_ack_in;
wire   [31:0] M_AXIS_TDATA_int_regslice;
reg    M_AXIS_TVALID_int_regslice;
wire    M_AXIS_TREADY_int_regslice;
wire    regslice_both_M_AXIS_V_data_V_U_vld_out;
wire    regslice_both_M_AXIS_V_keep_V_U_apdone_blk;
wire    regslice_both_M_AXIS_V_keep_V_U_ack_in_dummy;
wire    regslice_both_M_AXIS_V_keep_V_U_vld_out;
wire    regslice_both_M_AXIS_V_strb_V_U_apdone_blk;
wire    regslice_both_M_AXIS_V_strb_V_U_ack_in_dummy;
wire    regslice_both_M_AXIS_V_strb_V_U_vld_out;
wire    regslice_both_M_AXIS_V_last_V_U_apdone_blk;
wire    regslice_both_M_AXIS_V_last_V_U_ack_in_dummy;
wire    regslice_both_M_AXIS_V_last_V_U_vld_out;
wire   [15:0] grp_fu_478_p00;
wire   [15:0] grp_fu_485_p00;
wire   [17:0] grp_fu_485_p20;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 18'd1;
#0 grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_77_1_fu_310_ap_start_reg = 1'b0;
#0 grp_nn_accelerator_Pipeline_read_output_weights_fu_324_ap_start_reg = 1'b0;
#0 grp_nn_accelerator_Pipeline_read_features_fu_339_ap_start_reg = 1'b0;
#0 grp_nn_accelerator_Pipeline_compute_hidden_fu_359_ap_start_reg = 1'b0;
end

nn_accelerator_W_hidden_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
W_hidden_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(W_hidden_address0),
    .ce0(W_hidden_ce0),
    .we0(W_hidden_we0),
    .d0(grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_77_1_fu_310_W_hidden_d0),
    .q0(W_hidden_q0),
    .address1(W_hidden_address1_local),
    .ce1(W_hidden_ce1_local),
    .q1(W_hidden_q1)
);

nn_accelerator_W_hidden_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
W_hidden_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(W_hidden_1_address0),
    .ce0(W_hidden_1_ce0),
    .we0(W_hidden_1_we0),
    .d0(grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_77_1_fu_310_W_hidden_1_d0),
    .q0(W_hidden_1_q0),
    .address1(W_hidden_1_address1_local),
    .ce1(W_hidden_1_ce1_local),
    .q1(W_hidden_1_q1)
);

nn_accelerator_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_77_1 grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_77_1_fu_310(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_77_1_fu_310_ap_start),
    .ap_done(grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_77_1_fu_310_ap_done),
    .ap_idle(grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_77_1_fu_310_ap_idle),
    .ap_ready(grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_77_1_fu_310_ap_ready),
    .S_AXIS_TVALID(S_AXIS_TVALID_int_regslice),
    .W_hidden_address0(grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_77_1_fu_310_W_hidden_address0),
    .W_hidden_ce0(grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_77_1_fu_310_W_hidden_ce0),
    .W_hidden_we0(grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_77_1_fu_310_W_hidden_we0),
    .W_hidden_d0(grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_77_1_fu_310_W_hidden_d0),
    .W_hidden_1_address0(grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_77_1_fu_310_W_hidden_1_address0),
    .W_hidden_1_ce0(grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_77_1_fu_310_W_hidden_1_ce0),
    .W_hidden_1_we0(grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_77_1_fu_310_W_hidden_1_we0),
    .W_hidden_1_d0(grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_77_1_fu_310_W_hidden_1_d0),
    .S_AXIS_TDATA(S_AXIS_TDATA_int_regslice),
    .S_AXIS_TREADY(grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_77_1_fu_310_S_AXIS_TREADY),
    .S_AXIS_TKEEP(S_AXIS_TKEEP_int_regslice),
    .S_AXIS_TSTRB(S_AXIS_TSTRB_int_regslice),
    .S_AXIS_TLAST(S_AXIS_TLAST_int_regslice)
);

nn_accelerator_nn_accelerator_Pipeline_read_output_weights grp_nn_accelerator_Pipeline_read_output_weights_fu_324(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_nn_accelerator_Pipeline_read_output_weights_fu_324_ap_start),
    .ap_done(grp_nn_accelerator_Pipeline_read_output_weights_fu_324_ap_done),
    .ap_idle(grp_nn_accelerator_Pipeline_read_output_weights_fu_324_ap_idle),
    .ap_ready(grp_nn_accelerator_Pipeline_read_output_weights_fu_324_ap_ready),
    .S_AXIS_TVALID(S_AXIS_TVALID_int_regslice),
    .S_AXIS_TDATA(S_AXIS_TDATA_int_regslice),
    .S_AXIS_TREADY(grp_nn_accelerator_Pipeline_read_output_weights_fu_324_S_AXIS_TREADY),
    .S_AXIS_TKEEP(S_AXIS_TKEEP_int_regslice),
    .S_AXIS_TSTRB(S_AXIS_TSTRB_int_regslice),
    .S_AXIS_TLAST(S_AXIS_TLAST_int_regslice),
    .p_0_0371_1718_out(grp_nn_accelerator_Pipeline_read_output_weights_fu_324_p_0_0371_1718_out),
    .p_0_0371_1718_out_ap_vld(grp_nn_accelerator_Pipeline_read_output_weights_fu_324_p_0_0371_1718_out_ap_vld),
    .p_0_0371716_out(grp_nn_accelerator_Pipeline_read_output_weights_fu_324_p_0_0371716_out),
    .p_0_0371716_out_ap_vld(grp_nn_accelerator_Pipeline_read_output_weights_fu_324_p_0_0371716_out_ap_vld),
    .p_0_0377714_out(grp_nn_accelerator_Pipeline_read_output_weights_fu_324_p_0_0377714_out),
    .p_0_0377714_out_ap_vld(grp_nn_accelerator_Pipeline_read_output_weights_fu_324_p_0_0377714_out_ap_vld)
);

nn_accelerator_nn_accelerator_Pipeline_read_features grp_nn_accelerator_Pipeline_read_features_fu_339(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_nn_accelerator_Pipeline_read_features_fu_339_ap_start),
    .ap_done(grp_nn_accelerator_Pipeline_read_features_fu_339_ap_done),
    .ap_idle(grp_nn_accelerator_Pipeline_read_features_fu_339_ap_idle),
    .ap_ready(grp_nn_accelerator_Pipeline_read_features_fu_339_ap_ready),
    .S_AXIS_TVALID(S_AXIS_TVALID_int_regslice),
    .S_AXIS_TDATA(S_AXIS_TDATA_int_regslice),
    .S_AXIS_TREADY(grp_nn_accelerator_Pipeline_read_features_fu_339_S_AXIS_TREADY),
    .S_AXIS_TKEEP(S_AXIS_TKEEP_int_regslice),
    .S_AXIS_TSTRB(S_AXIS_TSTRB_int_regslice),
    .S_AXIS_TLAST(S_AXIS_TLAST_int_regslice),
    .x_row_6_out(grp_nn_accelerator_Pipeline_read_features_fu_339_x_row_6_out),
    .x_row_6_out_ap_vld(grp_nn_accelerator_Pipeline_read_features_fu_339_x_row_6_out_ap_vld),
    .x_row_5_out(grp_nn_accelerator_Pipeline_read_features_fu_339_x_row_5_out),
    .x_row_5_out_ap_vld(grp_nn_accelerator_Pipeline_read_features_fu_339_x_row_5_out_ap_vld),
    .x_row_4_out(grp_nn_accelerator_Pipeline_read_features_fu_339_x_row_4_out),
    .x_row_4_out_ap_vld(grp_nn_accelerator_Pipeline_read_features_fu_339_x_row_4_out_ap_vld),
    .x_row_3_out(grp_nn_accelerator_Pipeline_read_features_fu_339_x_row_3_out),
    .x_row_3_out_ap_vld(grp_nn_accelerator_Pipeline_read_features_fu_339_x_row_3_out_ap_vld),
    .x_row_2_out(grp_nn_accelerator_Pipeline_read_features_fu_339_x_row_2_out),
    .x_row_2_out_ap_vld(grp_nn_accelerator_Pipeline_read_features_fu_339_x_row_2_out_ap_vld),
    .x_row_1_out(grp_nn_accelerator_Pipeline_read_features_fu_339_x_row_1_out),
    .x_row_1_out_ap_vld(grp_nn_accelerator_Pipeline_read_features_fu_339_x_row_1_out_ap_vld),
    .x_row_out(grp_nn_accelerator_Pipeline_read_features_fu_339_x_row_out),
    .x_row_out_ap_vld(grp_nn_accelerator_Pipeline_read_features_fu_339_x_row_out_ap_vld),
    .last_sample_out(grp_nn_accelerator_Pipeline_read_features_fu_339_last_sample_out),
    .last_sample_out_ap_vld(grp_nn_accelerator_Pipeline_read_features_fu_339_last_sample_out_ap_vld)
);

nn_accelerator_nn_accelerator_Pipeline_compute_hidden grp_nn_accelerator_Pipeline_compute_hidden_fu_359(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_nn_accelerator_Pipeline_compute_hidden_fu_359_ap_start),
    .ap_done(grp_nn_accelerator_Pipeline_compute_hidden_fu_359_ap_done),
    .ap_idle(grp_nn_accelerator_Pipeline_compute_hidden_fu_359_ap_idle),
    .ap_ready(grp_nn_accelerator_Pipeline_compute_hidden_fu_359_ap_ready),
    .W_hidden_1_load(W_hidden_1_load_reg_596),
    .W_hidden_load(W_hidden_load_reg_591),
    .W_hidden_1_load_1(W_hidden_1_load_1_reg_606),
    .W_hidden_load_1(W_hidden_load_1_reg_601),
    .W_hidden_1_load_2(W_hidden_1_load_2_reg_636),
    .W_hidden_load_2(W_hidden_load_2_reg_631),
    .W_hidden_1_load_3(W_hidden_1_load_3_reg_646),
    .W_hidden_load_3(W_hidden_load_3_reg_641),
    .W_hidden_1_load_4(W_hidden_1_load_4_reg_676),
    .W_hidden_load_4(W_hidden_load_4_reg_671),
    .W_hidden_1_load_5(W_hidden_1_load_5_reg_686),
    .W_hidden_load_5(W_hidden_load_5_reg_681),
    .W_hidden_1_load_6(W_hidden_1_load_6_reg_731),
    .W_hidden_load_6(W_hidden_load_6_reg_726),
    .W_hidden_1_load_7(W_hidden_1_load_7_reg_741),
    .W_hidden_load_7(W_hidden_load_7_reg_736),
    .zext_ln137(grp_nn_accelerator_Pipeline_read_features_fu_339_x_row_6_out),
    .x_row_5_cast(grp_nn_accelerator_Pipeline_read_features_fu_339_x_row_5_out),
    .x_row_4_cast(grp_nn_accelerator_Pipeline_read_features_fu_339_x_row_4_out),
    .x_row_3_cast(grp_nn_accelerator_Pipeline_read_features_fu_339_x_row_3_out),
    .x_row_2_cast(grp_nn_accelerator_Pipeline_read_features_fu_339_x_row_2_out),
    .x_row_1_cast(grp_nn_accelerator_Pipeline_read_features_fu_339_x_row_1_out),
    .x_row_cast(grp_nn_accelerator_Pipeline_read_features_fu_339_x_row_out),
    .hidden_out_1_out(grp_nn_accelerator_Pipeline_compute_hidden_fu_359_hidden_out_1_out),
    .hidden_out_1_out_ap_vld(grp_nn_accelerator_Pipeline_compute_hidden_fu_359_hidden_out_1_out_ap_vld),
    .hidden_out_out(grp_nn_accelerator_Pipeline_compute_hidden_fu_359_hidden_out_out),
    .hidden_out_out_ap_vld(grp_nn_accelerator_Pipeline_compute_hidden_fu_359_hidden_out_out_ap_vld)
);

nn_accelerator_mac_muladd_8ns_8ns_16ns_17_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 17 ))
mac_muladd_8ns_8ns_16ns_17_4_1_U61(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_478_p0),
    .din1(grp_fu_478_p1),
    .din2(grp_fu_478_p2),
    .ce(1'b1),
    .dout(grp_fu_478_p3)
);

nn_accelerator_mac_muladd_8ns_8ns_17ns_18_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 17 ),
    .dout_WIDTH( 18 ))
mac_muladd_8ns_8ns_17ns_18_4_1_U62(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_485_p0),
    .din1(grp_fu_485_p1),
    .din2(grp_fu_485_p2),
    .ce(grp_fu_485_ce),
    .dout(grp_fu_485_p3)
);

nn_accelerator_regslice_both #(
    .DataWidth( 32 ))
regslice_both_S_AXIS_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(S_AXIS_TDATA),
    .vld_in(S_AXIS_TVALID),
    .ack_in(regslice_both_S_AXIS_V_data_V_U_ack_in),
    .data_out(S_AXIS_TDATA_int_regslice),
    .vld_out(S_AXIS_TVALID_int_regslice),
    .ack_out(S_AXIS_TREADY_int_regslice),
    .apdone_blk(regslice_both_S_AXIS_V_data_V_U_apdone_blk)
);

nn_accelerator_regslice_both #(
    .DataWidth( 4 ))
regslice_both_S_AXIS_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(S_AXIS_TKEEP),
    .vld_in(S_AXIS_TVALID),
    .ack_in(regslice_both_S_AXIS_V_keep_V_U_ack_in),
    .data_out(S_AXIS_TKEEP_int_regslice),
    .vld_out(regslice_both_S_AXIS_V_keep_V_U_vld_out),
    .ack_out(S_AXIS_TREADY_int_regslice),
    .apdone_blk(regslice_both_S_AXIS_V_keep_V_U_apdone_blk)
);

nn_accelerator_regslice_both #(
    .DataWidth( 4 ))
regslice_both_S_AXIS_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(S_AXIS_TSTRB),
    .vld_in(S_AXIS_TVALID),
    .ack_in(regslice_both_S_AXIS_V_strb_V_U_ack_in),
    .data_out(S_AXIS_TSTRB_int_regslice),
    .vld_out(regslice_both_S_AXIS_V_strb_V_U_vld_out),
    .ack_out(S_AXIS_TREADY_int_regslice),
    .apdone_blk(regslice_both_S_AXIS_V_strb_V_U_apdone_blk)
);

nn_accelerator_regslice_both #(
    .DataWidth( 1 ))
regslice_both_S_AXIS_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(S_AXIS_TLAST),
    .vld_in(S_AXIS_TVALID),
    .ack_in(regslice_both_S_AXIS_V_last_V_U_ack_in),
    .data_out(S_AXIS_TLAST_int_regslice),
    .vld_out(regslice_both_S_AXIS_V_last_V_U_vld_out),
    .ack_out(S_AXIS_TREADY_int_regslice),
    .apdone_blk(regslice_both_S_AXIS_V_last_V_U_apdone_blk)
);

nn_accelerator_regslice_both #(
    .DataWidth( 32 ))
regslice_both_M_AXIS_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(M_AXIS_TDATA_int_regslice),
    .vld_in(M_AXIS_TVALID_int_regslice),
    .ack_in(M_AXIS_TREADY_int_regslice),
    .data_out(M_AXIS_TDATA),
    .vld_out(regslice_both_M_AXIS_V_data_V_U_vld_out),
    .ack_out(M_AXIS_TREADY),
    .apdone_blk(regslice_both_M_AXIS_V_data_V_U_apdone_blk)
);

nn_accelerator_regslice_both #(
    .DataWidth( 4 ))
regslice_both_M_AXIS_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(4'd15),
    .vld_in(M_AXIS_TVALID_int_regslice),
    .ack_in(regslice_both_M_AXIS_V_keep_V_U_ack_in_dummy),
    .data_out(M_AXIS_TKEEP),
    .vld_out(regslice_both_M_AXIS_V_keep_V_U_vld_out),
    .ack_out(M_AXIS_TREADY),
    .apdone_blk(regslice_both_M_AXIS_V_keep_V_U_apdone_blk)
);

nn_accelerator_regslice_both #(
    .DataWidth( 4 ))
regslice_both_M_AXIS_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(4'd15),
    .vld_in(M_AXIS_TVALID_int_regslice),
    .ack_in(regslice_both_M_AXIS_V_strb_V_U_ack_in_dummy),
    .data_out(M_AXIS_TSTRB),
    .vld_out(regslice_both_M_AXIS_V_strb_V_U_vld_out),
    .ack_out(M_AXIS_TREADY),
    .apdone_blk(regslice_both_M_AXIS_V_strb_V_U_apdone_blk)
);

nn_accelerator_regslice_both #(
    .DataWidth( 1 ))
regslice_both_M_AXIS_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_nn_accelerator_Pipeline_read_features_fu_339_last_sample_out),
    .vld_in(M_AXIS_TVALID_int_regslice),
    .ack_in(regslice_both_M_AXIS_V_last_V_U_ack_in_dummy),
    .data_out(M_AXIS_TLAST),
    .vld_out(regslice_both_M_AXIS_V_last_V_U_vld_out),
    .ack_out(M_AXIS_TREADY),
    .apdone_blk(regslice_both_M_AXIS_V_last_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_nn_accelerator_Pipeline_compute_hidden_fu_359_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state11)) begin
            grp_nn_accelerator_Pipeline_compute_hidden_fu_359_ap_start_reg <= 1'b1;
        end else if ((grp_nn_accelerator_Pipeline_compute_hidden_fu_359_ap_ready == 1'b1)) begin
            grp_nn_accelerator_Pipeline_compute_hidden_fu_359_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_nn_accelerator_Pipeline_read_features_fu_339_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state9)) begin
            grp_nn_accelerator_Pipeline_read_features_fu_339_ap_start_reg <= 1'b1;
        end else if ((grp_nn_accelerator_Pipeline_read_features_fu_339_ap_ready == 1'b1)) begin
            grp_nn_accelerator_Pipeline_read_features_fu_339_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_77_1_fu_310_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_77_1_fu_310_ap_start_reg <= 1'b1;
        end else if ((grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_77_1_fu_310_ap_ready == 1'b1)) begin
            grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_77_1_fu_310_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_nn_accelerator_Pipeline_read_output_weights_fu_324_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state4)) begin
            grp_nn_accelerator_Pipeline_read_output_weights_fu_324_ap_start_reg <= 1'b1;
        end else if ((grp_nn_accelerator_Pipeline_read_output_weights_fu_324_ap_ready == 1'b1)) begin
            grp_nn_accelerator_Pipeline_read_output_weights_fu_324_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        W_hidden_1_load_1_reg_606 <= W_hidden_1_q0;
        W_hidden_1_load_reg_596 <= W_hidden_1_q1;
        W_hidden_load_1_reg_601 <= W_hidden_q0;
        W_hidden_load_reg_591 <= W_hidden_q1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        W_hidden_1_load_2_reg_636 <= W_hidden_1_q1;
        W_hidden_1_load_3_reg_646 <= W_hidden_1_q0;
        W_hidden_load_2_reg_631 <= W_hidden_q1;
        W_hidden_load_3_reg_641 <= W_hidden_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        W_hidden_1_load_4_reg_676 <= W_hidden_1_q1;
        W_hidden_1_load_5_reg_686 <= W_hidden_1_q0;
        W_hidden_load_4_reg_671 <= W_hidden_q1;
        W_hidden_load_5_reg_681 <= W_hidden_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        W_hidden_1_load_6_reg_731 <= W_hidden_1_q1;
        W_hidden_1_load_7_reg_741 <= W_hidden_1_q0;
        W_hidden_load_6_reg_726 <= W_hidden_q1;
        W_hidden_load_7_reg_736 <= W_hidden_q0;
        acc_cast_reg_711[15 : 8] <= acc_cast_fu_407_p1[15 : 8];
        p_0_0371716_cast_reg_716[7 : 0] <= p_0_0371716_cast_fu_411_p1[7 : 0];
        p_0_0371_1718_cast_reg_721[7 : 0] <= p_0_0371_1718_cast_fu_415_p1[7 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        last_sample_loc_load_reg_782 <= grp_nn_accelerator_Pipeline_read_features_fu_339_last_sample_out;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state17))) begin
        M_AXIS_TDATA_blk_n = M_AXIS_TREADY_int_regslice;
    end else begin
        M_AXIS_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == M_AXIS_TREADY_int_regslice) & (1'b1 == ap_CS_fsm_state17))) begin
        M_AXIS_TVALID_int_regslice = 1'b1;
    end else begin
        M_AXIS_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        S_AXIS_TREADY_int_regslice = grp_nn_accelerator_Pipeline_read_features_fu_339_S_AXIS_TREADY;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        S_AXIS_TREADY_int_regslice = grp_nn_accelerator_Pipeline_read_output_weights_fu_324_S_AXIS_TREADY;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        S_AXIS_TREADY_int_regslice = grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_77_1_fu_310_S_AXIS_TREADY;
    end else begin
        S_AXIS_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        W_hidden_1_address0 = grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_77_1_fu_310_W_hidden_1_address0;
    end else begin
        W_hidden_1_address0 = W_hidden_1_address0_local;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        W_hidden_1_address0_local = 64'd7;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        W_hidden_1_address0_local = 64'd5;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        W_hidden_1_address0_local = 64'd3;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        W_hidden_1_address0_local = 64'd1;
    end else begin
        W_hidden_1_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        W_hidden_1_address1_local = 64'd6;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        W_hidden_1_address1_local = 64'd4;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        W_hidden_1_address1_local = 64'd2;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        W_hidden_1_address1_local = 64'd0;
    end else begin
        W_hidden_1_address1_local = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        W_hidden_1_ce0 = grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_77_1_fu_310_W_hidden_1_ce0;
    end else begin
        W_hidden_1_ce0 = W_hidden_1_ce0_local;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state7) | ((grp_nn_accelerator_Pipeline_read_output_weights_fu_324_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5)))) begin
        W_hidden_1_ce0_local = 1'b1;
    end else begin
        W_hidden_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state7) | ((grp_nn_accelerator_Pipeline_read_output_weights_fu_324_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5)))) begin
        W_hidden_1_ce1_local = 1'b1;
    end else begin
        W_hidden_1_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        W_hidden_1_we0 = grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_77_1_fu_310_W_hidden_1_we0;
    end else begin
        W_hidden_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        W_hidden_address0 = grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_77_1_fu_310_W_hidden_address0;
    end else begin
        W_hidden_address0 = W_hidden_address0_local;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        W_hidden_address0_local = 64'd7;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        W_hidden_address0_local = 64'd5;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        W_hidden_address0_local = 64'd3;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        W_hidden_address0_local = 64'd1;
    end else begin
        W_hidden_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        W_hidden_address1_local = 64'd6;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        W_hidden_address1_local = 64'd4;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        W_hidden_address1_local = 64'd2;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        W_hidden_address1_local = 64'd0;
    end else begin
        W_hidden_address1_local = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        W_hidden_ce0 = grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_77_1_fu_310_W_hidden_ce0;
    end else begin
        W_hidden_ce0 = W_hidden_ce0_local;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state7) | ((grp_nn_accelerator_Pipeline_read_output_weights_fu_324_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5)))) begin
        W_hidden_ce0_local = 1'b1;
    end else begin
        W_hidden_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state7) | ((grp_nn_accelerator_Pipeline_read_output_weights_fu_324_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5)))) begin
        W_hidden_ce1_local = 1'b1;
    end else begin
        W_hidden_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        W_hidden_we0 = grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_77_1_fu_310_W_hidden_we0;
    end else begin
        W_hidden_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((grp_nn_accelerator_Pipeline_read_features_fu_339_ap_done == 1'b0)) begin
        ap_ST_fsm_state10_blk = 1'b1;
    end else begin
        ap_ST_fsm_state10_blk = 1'b0;
    end
end

assign ap_ST_fsm_state11_blk = 1'b0;

always @ (*) begin
    if ((grp_nn_accelerator_Pipeline_compute_hidden_fu_359_ap_done == 1'b0)) begin
        ap_ST_fsm_state12_blk = 1'b1;
    end else begin
        ap_ST_fsm_state12_blk = 1'b0;
    end
end

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

always @ (*) begin
    if ((1'b0 == M_AXIS_TREADY_int_regslice)) begin
        ap_ST_fsm_state17_blk = 1'b1;
    end else begin
        ap_ST_fsm_state17_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state18)) begin
        ap_ST_fsm_state18_blk = 1'b1;
    end else begin
        ap_ST_fsm_state18_blk = 1'b0;
    end
end

assign ap_ST_fsm_state1_blk = 1'b0;

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_77_1_fu_310_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if ((grp_nn_accelerator_Pipeline_read_output_weights_fu_324_ap_done == 1'b0)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state14) | ((1'b1 == M_AXIS_TREADY_int_regslice) & (1'b1 == ap_CS_fsm_state17)))) begin
        grp_fu_485_ce = 1'b1;
    end else begin
        grp_fu_485_ce = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_77_1_fu_310_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((grp_nn_accelerator_Pipeline_read_output_weights_fu_324_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            if (((grp_nn_accelerator_Pipeline_read_features_fu_339_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            if (((grp_nn_accelerator_Pipeline_compute_hidden_fu_359_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state12))) begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            if (((1'b1 == M_AXIS_TREADY_int_regslice) & (1'b1 == ap_CS_fsm_state17))) begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end
        end
        ap_ST_fsm_state18 : begin
            if (((1'b0 == ap_block_state18) & (1'b1 == ap_CS_fsm_state18) & (last_sample_loc_load_reg_782 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else if (((1'b0 == ap_block_state18) & (1'b1 == ap_CS_fsm_state18) & (last_sample_loc_load_reg_782 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign M_AXIS_TDATA_int_regslice = out_pkt_data_fu_468_p2;

assign M_AXIS_TVALID = regslice_both_M_AXIS_V_data_V_U_vld_out;

assign S_AXIS_TREADY = regslice_both_S_AXIS_V_data_V_U_ack_in;

assign acc_cast_fu_407_p1 = acc_fu_399_p3;

assign acc_fu_399_p3 = {{grp_nn_accelerator_Pipeline_read_output_weights_fu_324_p_0_0377714_out}, {8'd0}};

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state18 = ((regslice_both_M_AXIS_V_data_V_U_apdone_blk == 1'b1) | (1'b0 == M_AXIS_TREADY_int_regslice));
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign grp_fu_478_p0 = grp_fu_478_p00;

assign grp_fu_478_p00 = grp_nn_accelerator_Pipeline_compute_hidden_fu_359_hidden_out_1_out;

assign grp_fu_478_p1 = p_0_0371_1718_cast_reg_721;

assign grp_fu_478_p2 = acc_cast_reg_711;

assign grp_fu_485_p0 = grp_fu_485_p00;

assign grp_fu_485_p00 = grp_nn_accelerator_Pipeline_compute_hidden_fu_359_hidden_out_out;

assign grp_fu_485_p1 = p_0_0371716_cast_reg_716;

assign grp_fu_485_p2 = grp_fu_485_p20;

assign grp_fu_485_p20 = grp_fu_478_p3;

assign grp_nn_accelerator_Pipeline_compute_hidden_fu_359_ap_start = grp_nn_accelerator_Pipeline_compute_hidden_fu_359_ap_start_reg;

assign grp_nn_accelerator_Pipeline_read_features_fu_339_ap_start = grp_nn_accelerator_Pipeline_read_features_fu_339_ap_start_reg;

assign grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_77_1_fu_310_ap_start = grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_77_1_fu_310_ap_start_reg;

assign grp_nn_accelerator_Pipeline_read_output_weights_fu_324_ap_start = grp_nn_accelerator_Pipeline_read_output_weights_fu_324_ap_start_reg;

assign out_pkt_data_fu_468_p2 = ((grp_fu_485_p3 > 18'd33023) ? 1'b1 : 1'b0);

assign p_0_0371716_cast_fu_411_p1 = grp_nn_accelerator_Pipeline_read_output_weights_fu_324_p_0_0371716_out;

assign p_0_0371_1718_cast_fu_415_p1 = grp_nn_accelerator_Pipeline_read_output_weights_fu_324_p_0_0371_1718_out;

always @ (posedge ap_clk) begin
    acc_cast_reg_711[7:0] <= 8'b00000000;
    acc_cast_reg_711[16] <= 1'b0;
    p_0_0371716_cast_reg_716[15:8] <= 8'b00000000;
    p_0_0371_1718_cast_reg_721[15:8] <= 8'b00000000;
end


reg find_kernel_block = 0;
// synthesis translate_off
`include "nn_accelerator_hls_deadlock_kernel_monitor_top.vh"
// synthesis translate_on

endmodule //nn_accelerator

