// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module nn_accelerator_nn_accelerator_Pipeline_compute_hidden (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        W_hidden_1_load,
        W_hidden_load,
        W_hidden_1_load_1,
        W_hidden_load_1,
        W_hidden_1_load_2,
        W_hidden_load_2,
        W_hidden_1_load_3,
        W_hidden_load_3,
        W_hidden_1_load_4,
        W_hidden_load_4,
        W_hidden_1_load_5,
        W_hidden_load_5,
        W_hidden_1_load_6,
        W_hidden_load_6,
        W_hidden_1_load_7,
        W_hidden_load_7,
        zext_ln137,
        x_row_5_cast,
        x_row_4_cast,
        x_row_3_cast,
        x_row_2_cast,
        x_row_1_cast,
        x_row_cast,
        hidden_out_1_out,
        hidden_out_1_out_ap_vld,
        hidden_out_out,
        hidden_out_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [7:0] W_hidden_1_load;
input  [7:0] W_hidden_load;
input  [7:0] W_hidden_1_load_1;
input  [7:0] W_hidden_load_1;
input  [7:0] W_hidden_1_load_2;
input  [7:0] W_hidden_load_2;
input  [7:0] W_hidden_1_load_3;
input  [7:0] W_hidden_load_3;
input  [7:0] W_hidden_1_load_4;
input  [7:0] W_hidden_load_4;
input  [7:0] W_hidden_1_load_5;
input  [7:0] W_hidden_load_5;
input  [7:0] W_hidden_1_load_6;
input  [7:0] W_hidden_load_6;
input  [7:0] W_hidden_1_load_7;
input  [7:0] W_hidden_load_7;
input  [7:0] zext_ln137;
input  [7:0] x_row_5_cast;
input  [7:0] x_row_4_cast;
input  [7:0] x_row_3_cast;
input  [7:0] x_row_2_cast;
input  [7:0] x_row_1_cast;
input  [7:0] x_row_cast;
output  [7:0] hidden_out_1_out;
output   hidden_out_1_out_ap_vld;
output  [7:0] hidden_out_out;
output   hidden_out_out_ap_vld;

reg ap_idle;
reg hidden_out_1_out_ap_vld;
reg hidden_out_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln137_fu_313_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [7:0] sigmoid_lut_address0;
wire   [7:0] sigmoid_lut_q0;
wire    ap_block_pp0_stage0_11001;
wire   [15:0] x_row_cast_cast_fu_277_p1;
reg   [15:0] x_row_cast_cast_reg_699;
wire   [15:0] x_row_3_cast_cast_fu_289_p1;
reg   [15:0] x_row_3_cast_cast_reg_714;
wire   [15:0] x_row_4_cast_cast_fu_293_p1;
reg   [15:0] x_row_4_cast_cast_reg_719;
reg   [0:0] icmp_ln137_reg_734;
reg   [0:0] icmp_ln137_reg_734_pp0_iter1_reg;
reg   [0:0] icmp_ln137_reg_734_pp0_iter2_reg;
wire   [0:0] icmp_ln141_fu_325_p2;
reg   [0:0] icmp_ln141_reg_738;
reg   [0:0] icmp_ln141_reg_738_pp0_iter1_reg;
wire   [0:0] icmp_ln150_fu_379_p2;
reg   [0:0] icmp_ln150_reg_766;
reg   [0:0] icmp_ln150_reg_766_pp0_iter1_reg;
reg   [0:0] icmp_ln150_reg_766_pp0_iter2_reg;
reg   [0:0] icmp_ln150_reg_766_pp0_iter3_reg;
wire   [63:0] zext_ln54_fu_555_p1;
wire    ap_block_pp0_stage0;
reg   [1:0] j_fu_100;
wire   [1:0] add_ln137_fu_319_p2;
wire    ap_loop_init;
reg   [1:0] ap_sig_allocacmp_j_2;
reg   [7:0] hidden_out_fu_104;
wire   [7:0] hidden_out_2_fu_573_p3;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg   [7:0] hidden_out_1_fu_108;
wire   [7:0] hidden_out_3_fu_566_p3;
wire    ap_block_pp0_stage0_01001;
reg    sigmoid_lut_ce0_local;
wire   [7:0] select_ln145_1_fu_331_p3;
wire   [7:0] select_ln145_2_fu_343_p3;
wire   [7:0] select_ln145_5_fu_355_p3;
wire   [7:0] select_ln145_6_fu_367_p3;
wire   [7:0] select_ln141_fu_390_p3;
wire   [15:0] acc_fu_395_p3;
wire   [7:0] select_ln145_fu_407_p3;
wire   [7:0] select_ln145_3_fu_416_p3;
wire   [7:0] select_ln145_4_fu_425_p3;
wire   [7:0] mul_ln145_2_fu_434_p0;
wire   [7:0] mul_ln145_2_fu_434_p1;
wire   [15:0] mul_ln145_2_fu_434_p2;
wire   [7:0] mul_ln145_3_fu_443_p0;
wire   [7:0] mul_ln145_3_fu_443_p1;
wire   [15:0] mul_ln145_3_fu_443_p2;
wire   [7:0] mul_ln145_6_fu_452_p0;
wire   [7:0] mul_ln145_6_fu_452_p1;
wire   [15:0] mul_ln145_6_fu_452_p2;
wire   [16:0] grp_fu_608_p3;
wire   [16:0] grp_fu_618_p3;
wire   [17:0] zext_ln145_15_fu_464_p1;
wire   [17:0] zext_ln145_14_fu_461_p1;
(* use_dsp48 = "no" *) wire   [16:0] add_ln145_7_fu_467_p2;
wire   [17:0] add_ln145_2_fu_471_p2;
wire   [16:0] grp_fu_628_p3;
wire   [16:0] grp_fu_598_p3;
wire   [17:0] zext_ln145_18_fu_488_p1;
wire   [17:0] zext_ln145_17_fu_485_p1;
(* use_dsp48 = "no" *) wire   [16:0] add_ln145_8_fu_491_p2;
wire   [17:0] add_ln145_5_fu_495_p2;
wire   [15:0] trunc_ln145_1_fu_501_p1;
wire   [15:0] trunc_ln145_fu_477_p1;
wire   [18:0] zext_ln145_19_fu_505_p1;
wire   [18:0] zext_ln145_16_fu_481_p1;
wire   [18:0] acc_1_fu_515_p2;
wire   [2:0] tmp_fu_521_p4;
wire   [15:0] add_ln145_6_fu_509_p2;
wire   [0:0] icmp_ln149_fu_531_p2;
wire   [7:0] trunc_ln1_fu_537_p4;
wire   [7:0] idx_fu_547_p3;
wire   [7:0] grp_fu_598_p0;
wire   [7:0] grp_fu_598_p1;
wire   [15:0] grp_fu_598_p2;
wire   [7:0] grp_fu_608_p0;
wire   [7:0] grp_fu_608_p1;
wire   [15:0] grp_fu_608_p2;
wire   [7:0] grp_fu_618_p0;
wire   [7:0] grp_fu_618_p1;
wire   [15:0] grp_fu_618_p2;
wire   [7:0] grp_fu_628_p0;
wire   [7:0] grp_fu_628_p1;
wire   [15:0] grp_fu_628_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [15:0] grp_fu_598_p00;
wire   [15:0] grp_fu_598_p10;
wire   [16:0] grp_fu_598_p20;
wire   [15:0] grp_fu_608_p00;
wire   [15:0] grp_fu_608_p10;
wire   [16:0] grp_fu_608_p20;
wire   [15:0] grp_fu_618_p00;
wire   [15:0] grp_fu_618_p10;
wire   [16:0] grp_fu_618_p20;
wire   [15:0] grp_fu_628_p00;
wire   [15:0] grp_fu_628_p10;
wire   [16:0] grp_fu_628_p20;
wire   [15:0] mul_ln145_2_fu_434_p00;
wire   [15:0] mul_ln145_3_fu_443_p00;
wire   [15:0] mul_ln145_6_fu_452_p00;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 j_fu_100 = 2'd0;
#0 hidden_out_fu_104 = 8'd0;
#0 hidden_out_1_fu_108 = 8'd0;
#0 ap_done_reg = 1'b0;
end

nn_accelerator_nn_accelerator_Pipeline_compute_hidden_sigmoid_lut_ROM_AUTO_1R #(
    .DataWidth( 8 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
sigmoid_lut_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(sigmoid_lut_address0),
    .ce0(sigmoid_lut_ce0_local),
    .q0(sigmoid_lut_q0)
);

nn_accelerator_mul_8ns_8ns_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
mul_8ns_8ns_16_1_1_U26(
    .din0(mul_ln145_2_fu_434_p0),
    .din1(mul_ln145_2_fu_434_p1),
    .dout(mul_ln145_2_fu_434_p2)
);

nn_accelerator_mul_8ns_8ns_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
mul_8ns_8ns_16_1_1_U27(
    .din0(mul_ln145_3_fu_443_p0),
    .din1(mul_ln145_3_fu_443_p1),
    .dout(mul_ln145_3_fu_443_p2)
);

nn_accelerator_mul_8ns_8ns_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
mul_8ns_8ns_16_1_1_U28(
    .din0(mul_ln145_6_fu_452_p0),
    .din1(mul_ln145_6_fu_452_p1),
    .dout(mul_ln145_6_fu_452_p2)
);

nn_accelerator_mac_muladd_8ns_8ns_16ns_17_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 17 ))
mac_muladd_8ns_8ns_16ns_17_4_1_U29(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_598_p0),
    .din1(grp_fu_598_p1),
    .din2(grp_fu_598_p2),
    .ce(1'b1),
    .dout(grp_fu_598_p3)
);

nn_accelerator_mac_muladd_8ns_8ns_16ns_17_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 17 ))
mac_muladd_8ns_8ns_16ns_17_4_1_U30(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_608_p0),
    .din1(grp_fu_608_p1),
    .din2(grp_fu_608_p2),
    .ce(1'b1),
    .dout(grp_fu_608_p3)
);

nn_accelerator_mac_muladd_8ns_8ns_16ns_17_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 17 ))
mac_muladd_8ns_8ns_16ns_17_4_1_U31(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_618_p0),
    .din1(grp_fu_618_p1),
    .din2(grp_fu_618_p2),
    .ce(1'b1),
    .dout(grp_fu_618_p3)
);

nn_accelerator_mac_muladd_8ns_8ns_16ns_17_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 17 ))
mac_muladd_8ns_8ns_16ns_17_4_1_U32(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_628_p0),
    .din1(grp_fu_628_p1),
    .din2(grp_fu_628_p2),
    .ce(1'b1),
    .dout(grp_fu_628_p3)
);

nn_accelerator_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln137_fu_313_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            j_fu_100 <= add_ln137_fu_319_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            j_fu_100 <= 2'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        icmp_ln137_reg_734 <= icmp_ln137_fu_313_p2;
        icmp_ln137_reg_734_pp0_iter1_reg <= icmp_ln137_reg_734;
        icmp_ln141_reg_738 <= icmp_ln141_fu_325_p2;
        icmp_ln141_reg_738_pp0_iter1_reg <= icmp_ln141_reg_738;
        icmp_ln150_reg_766 <= icmp_ln150_fu_379_p2;
        icmp_ln150_reg_766_pp0_iter1_reg <= icmp_ln150_reg_766;
        x_row_3_cast_cast_reg_714[7 : 0] <= x_row_3_cast_cast_fu_289_p1[7 : 0];
        x_row_4_cast_cast_reg_719[7 : 0] <= x_row_4_cast_cast_fu_293_p1[7 : 0];
        x_row_cast_cast_reg_699[7 : 0] <= x_row_cast_cast_fu_277_p1[7 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        icmp_ln137_reg_734_pp0_iter2_reg <= icmp_ln137_reg_734_pp0_iter1_reg;
        icmp_ln150_reg_766_pp0_iter2_reg <= icmp_ln150_reg_766_pp0_iter1_reg;
        icmp_ln150_reg_766_pp0_iter3_reg <= icmp_ln150_reg_766_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        hidden_out_1_fu_108 <= hidden_out_3_fu_566_p3;
        hidden_out_fu_104 <= hidden_out_2_fu_573_p3;
    end
end

always @ (*) begin
    if (((icmp_ln137_fu_313_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_j_2 = 2'd0;
    end else begin
        ap_sig_allocacmp_j_2 = j_fu_100;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1) & (icmp_ln137_reg_734_pp0_iter2_reg == 1'd1))) begin
        hidden_out_1_out_ap_vld = 1'b1;
    end else begin
        hidden_out_1_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1) & (icmp_ln137_reg_734_pp0_iter2_reg == 1'd1))) begin
        hidden_out_out_ap_vld = 1'b1;
    end else begin
        hidden_out_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        sigmoid_lut_ce0_local = 1'b1;
    end else begin
        sigmoid_lut_ce0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign acc_1_fu_515_p2 = (zext_ln145_19_fu_505_p1 + zext_ln145_16_fu_481_p1);

assign acc_fu_395_p3 = {{select_ln141_fu_390_p3}, {8'd0}};

assign add_ln137_fu_319_p2 = (ap_sig_allocacmp_j_2 + 2'd1);

assign add_ln145_2_fu_471_p2 = (zext_ln145_15_fu_464_p1 + zext_ln145_14_fu_461_p1);

assign add_ln145_5_fu_495_p2 = (zext_ln145_18_fu_488_p1 + zext_ln145_17_fu_485_p1);

assign add_ln145_6_fu_509_p2 = (trunc_ln145_1_fu_501_p1 + trunc_ln145_fu_477_p1);

assign add_ln145_7_fu_467_p2 = (grp_fu_618_p3 + grp_fu_608_p3);

assign add_ln145_8_fu_491_p2 = (grp_fu_598_p3 + grp_fu_628_p3);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign grp_fu_598_p0 = grp_fu_598_p00;

assign grp_fu_598_p00 = select_ln145_6_fu_367_p3;

assign grp_fu_598_p1 = grp_fu_598_p10;

assign grp_fu_598_p10 = zext_ln137;

assign grp_fu_598_p2 = grp_fu_598_p20;

assign grp_fu_598_p20 = acc_fu_395_p3;

assign grp_fu_608_p0 = grp_fu_608_p00;

assign grp_fu_608_p00 = select_ln145_5_fu_355_p3;

assign grp_fu_608_p1 = grp_fu_608_p10;

assign grp_fu_608_p10 = x_row_5_cast;

assign grp_fu_608_p2 = grp_fu_608_p20;

assign grp_fu_608_p20 = mul_ln145_2_fu_434_p2;

assign grp_fu_618_p0 = grp_fu_618_p00;

assign grp_fu_618_p00 = select_ln145_2_fu_343_p3;

assign grp_fu_618_p1 = grp_fu_618_p10;

assign grp_fu_618_p10 = x_row_2_cast;

assign grp_fu_618_p2 = grp_fu_618_p20;

assign grp_fu_618_p20 = mul_ln145_3_fu_443_p2;

assign grp_fu_628_p0 = grp_fu_628_p00;

assign grp_fu_628_p00 = select_ln145_1_fu_331_p3;

assign grp_fu_628_p1 = grp_fu_628_p10;

assign grp_fu_628_p10 = x_row_1_cast;

assign grp_fu_628_p2 = grp_fu_628_p20;

assign grp_fu_628_p20 = mul_ln145_6_fu_452_p2;

assign hidden_out_1_out = hidden_out_1_fu_108;

assign hidden_out_2_fu_573_p3 = ((icmp_ln150_reg_766_pp0_iter3_reg[0:0] == 1'b1) ? sigmoid_lut_q0 : hidden_out_fu_104);

assign hidden_out_3_fu_566_p3 = ((icmp_ln150_reg_766_pp0_iter3_reg[0:0] == 1'b1) ? hidden_out_1_fu_108 : sigmoid_lut_q0);

assign hidden_out_out = hidden_out_fu_104;

assign icmp_ln137_fu_313_p2 = ((ap_sig_allocacmp_j_2 == 2'd2) ? 1'b1 : 1'b0);

assign icmp_ln141_fu_325_p2 = ((ap_sig_allocacmp_j_2 == 2'd1) ? 1'b1 : 1'b0);

assign icmp_ln149_fu_531_p2 = ((tmp_fu_521_p4 != 3'd0) ? 1'b1 : 1'b0);

assign icmp_ln150_fu_379_p2 = ((ap_sig_allocacmp_j_2 == 2'd0) ? 1'b1 : 1'b0);

assign idx_fu_547_p3 = ((icmp_ln149_fu_531_p2[0:0] == 1'b1) ? 8'd255 : trunc_ln1_fu_537_p4);

assign mul_ln145_2_fu_434_p0 = mul_ln145_2_fu_434_p00;

assign mul_ln145_2_fu_434_p00 = select_ln145_4_fu_425_p3;

assign mul_ln145_2_fu_434_p1 = x_row_4_cast_cast_reg_719;

assign mul_ln145_3_fu_443_p0 = mul_ln145_3_fu_443_p00;

assign mul_ln145_3_fu_443_p00 = select_ln145_3_fu_416_p3;

assign mul_ln145_3_fu_443_p1 = x_row_3_cast_cast_reg_714;

assign mul_ln145_6_fu_452_p0 = mul_ln145_6_fu_452_p00;

assign mul_ln145_6_fu_452_p00 = select_ln145_fu_407_p3;

assign mul_ln145_6_fu_452_p1 = x_row_cast_cast_reg_699;

assign select_ln141_fu_390_p3 = ((icmp_ln141_reg_738_pp0_iter1_reg[0:0] == 1'b1) ? W_hidden_1_load : W_hidden_load);

assign select_ln145_1_fu_331_p3 = ((icmp_ln141_fu_325_p2[0:0] == 1'b1) ? W_hidden_1_load_2 : W_hidden_load_2);

assign select_ln145_2_fu_343_p3 = ((icmp_ln141_fu_325_p2[0:0] == 1'b1) ? W_hidden_1_load_3 : W_hidden_load_3);

assign select_ln145_3_fu_416_p3 = ((icmp_ln141_reg_738_pp0_iter1_reg[0:0] == 1'b1) ? W_hidden_1_load_4 : W_hidden_load_4);

assign select_ln145_4_fu_425_p3 = ((icmp_ln141_reg_738_pp0_iter1_reg[0:0] == 1'b1) ? W_hidden_1_load_5 : W_hidden_load_5);

assign select_ln145_5_fu_355_p3 = ((icmp_ln141_fu_325_p2[0:0] == 1'b1) ? W_hidden_1_load_6 : W_hidden_load_6);

assign select_ln145_6_fu_367_p3 = ((icmp_ln141_fu_325_p2[0:0] == 1'b1) ? W_hidden_1_load_7 : W_hidden_load_7);

assign select_ln145_fu_407_p3 = ((icmp_ln141_reg_738_pp0_iter1_reg[0:0] == 1'b1) ? W_hidden_1_load_1 : W_hidden_load_1);

assign sigmoid_lut_address0 = zext_ln54_fu_555_p1;

assign tmp_fu_521_p4 = {{acc_1_fu_515_p2[18:16]}};

assign trunc_ln145_1_fu_501_p1 = add_ln145_8_fu_491_p2[15:0];

assign trunc_ln145_fu_477_p1 = add_ln145_7_fu_467_p2[15:0];

assign trunc_ln1_fu_537_p4 = {{add_ln145_6_fu_509_p2[15:8]}};

assign x_row_3_cast_cast_fu_289_p1 = x_row_3_cast;

assign x_row_4_cast_cast_fu_293_p1 = x_row_4_cast;

assign x_row_cast_cast_fu_277_p1 = x_row_cast;

assign zext_ln145_14_fu_461_p1 = grp_fu_608_p3;

assign zext_ln145_15_fu_464_p1 = grp_fu_618_p3;

assign zext_ln145_16_fu_481_p1 = add_ln145_2_fu_471_p2;

assign zext_ln145_17_fu_485_p1 = grp_fu_628_p3;

assign zext_ln145_18_fu_488_p1 = grp_fu_598_p3;

assign zext_ln145_19_fu_505_p1 = add_ln145_5_fu_495_p2;

assign zext_ln54_fu_555_p1 = idx_fu_547_p3;

always @ (posedge ap_clk) begin
    x_row_cast_cast_reg_699[15:8] <= 8'b00000000;
    x_row_3_cast_cast_reg_714[15:8] <= 8'b00000000;
    x_row_4_cast_cast_reg_719[15:8] <= 8'b00000000;
end

endmodule //nn_accelerator_nn_accelerator_Pipeline_compute_hidden
