// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module nn_accelerator_nn_accelerator_Pipeline_read_features (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        S_AXIS_TVALID,
        S_AXIS_TDATA,
        S_AXIS_TREADY,
        S_AXIS_TKEEP,
        S_AXIS_TSTRB,
        S_AXIS_TLAST,
        x_row_6_out,
        x_row_6_out_ap_vld,
        x_row_5_out,
        x_row_5_out_ap_vld,
        x_row_4_out,
        x_row_4_out_ap_vld,
        x_row_3_out,
        x_row_3_out_ap_vld,
        x_row_2_out,
        x_row_2_out_ap_vld,
        x_row_1_out,
        x_row_1_out_ap_vld,
        x_row_out,
        x_row_out_ap_vld,
        last_sample_out,
        last_sample_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   S_AXIS_TVALID;
input  [31:0] S_AXIS_TDATA;
output   S_AXIS_TREADY;
input  [3:0] S_AXIS_TKEEP;
input  [3:0] S_AXIS_TSTRB;
input  [0:0] S_AXIS_TLAST;
output  [7:0] x_row_6_out;
output   x_row_6_out_ap_vld;
output  [7:0] x_row_5_out;
output   x_row_5_out_ap_vld;
output  [7:0] x_row_4_out;
output   x_row_4_out_ap_vld;
output  [7:0] x_row_3_out;
output   x_row_3_out_ap_vld;
output  [7:0] x_row_2_out;
output   x_row_2_out_ap_vld;
output  [7:0] x_row_1_out;
output   x_row_1_out_ap_vld;
output  [7:0] x_row_out;
output   x_row_out_ap_vld;
output  [0:0] last_sample_out;
output   last_sample_out_ap_vld;

reg ap_idle;
reg S_AXIS_TREADY;
reg x_row_6_out_ap_vld;
reg x_row_5_out_ap_vld;
reg x_row_4_out_ap_vld;
reg x_row_3_out_ap_vld;
reg x_row_2_out_ap_vld;
reg x_row_1_out_ap_vld;
reg x_row_out_ap_vld;
reg last_sample_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
reg   [0:0] icmp_ln119_reg_376;
reg    ap_block_state2_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln119_fu_198_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    S_AXIS_TDATA_blk_n;
wire    ap_block_pp0_stage0;
reg   [0:0] last_sample_reg_178;
reg   [2:0] j_1_reg_372;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln127_fu_226_p2;
reg   [0:0] icmp_ln127_reg_380;
wire   [0:0] last_sample_1_fu_289_p2;
wire    ap_loop_init;
reg   [2:0] j_fu_78;
wire   [2:0] add_ln119_fu_204_p2;
reg   [2:0] ap_sig_allocacmp_j_1;
reg   [7:0] x_row_fu_82;
wire   [7:0] x_row_7_fu_245_p1;
reg   [7:0] x_row_1_fu_86;
reg   [7:0] x_row_2_fu_90;
reg   [7:0] x_row_3_fu_94;
reg   [7:0] x_row_4_fu_98;
reg   [7:0] x_row_5_fu_102;
reg   [7:0] x_row_6_fu_106;
reg    ap_block_pp0_stage0_01001;
wire   [0:0] and_ln127_fu_284_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
reg    ap_condition_250;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 j_fu_78 = 3'd0;
#0 x_row_fu_82 = 8'd0;
#0 x_row_1_fu_86 = 8'd0;
#0 x_row_2_fu_90 = 8'd0;
#0 x_row_3_fu_94 = 8'd0;
#0 x_row_4_fu_98 = 8'd0;
#0 x_row_5_fu_102 = 8'd0;
#0 x_row_6_fu_106 = 8'd0;
#0 ap_done_reg = 1'b0;
end

nn_accelerator_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln119_fu_198_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            j_fu_78 <= add_ln119_fu_204_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            j_fu_78 <= 3'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        if ((1'b1 == ap_condition_250)) begin
            last_sample_reg_178 <= last_sample_1_fu_289_p2;
        end else if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            last_sample_reg_178 <= 1'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln119_reg_376 <= icmp_ln119_fu_198_p2;
        icmp_ln127_reg_380 <= icmp_ln127_fu_226_p2;
        j_1_reg_372 <= ap_sig_allocacmp_j_1;
    end
end

always @ (posedge ap_clk) begin
    if (((j_1_reg_372 == 3'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_row_1_fu_86 <= x_row_7_fu_245_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((j_1_reg_372 == 3'd2) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_row_2_fu_90 <= x_row_7_fu_245_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((j_1_reg_372 == 3'd3) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_row_3_fu_94 <= x_row_7_fu_245_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((j_1_reg_372 == 3'd4) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_row_4_fu_98 <= x_row_7_fu_245_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((j_1_reg_372 == 3'd5) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_row_5_fu_102 <= x_row_7_fu_245_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & ((j_1_reg_372 == 3'd6) | (j_1_reg_372 == 3'd7)))) begin
        x_row_6_fu_106 <= x_row_7_fu_245_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((j_1_reg_372 == 3'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_row_fu_82 <= x_row_7_fu_245_p1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln119_reg_376 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        S_AXIS_TDATA_blk_n = S_AXIS_TVALID;
    end else begin
        S_AXIS_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln119_reg_376 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        S_AXIS_TREADY = 1'b1;
    end else begin
        S_AXIS_TREADY = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln119_fu_198_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_j_1 = 3'd0;
    end else begin
        ap_sig_allocacmp_j_1 = j_fu_78;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln119_fu_198_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        last_sample_out_ap_vld = 1'b1;
    end else begin
        last_sample_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln119_fu_198_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_row_1_out_ap_vld = 1'b1;
    end else begin
        x_row_1_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln119_fu_198_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_row_2_out_ap_vld = 1'b1;
    end else begin
        x_row_2_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln119_fu_198_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_row_3_out_ap_vld = 1'b1;
    end else begin
        x_row_3_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln119_fu_198_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_row_4_out_ap_vld = 1'b1;
    end else begin
        x_row_4_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln119_fu_198_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_row_5_out_ap_vld = 1'b1;
    end else begin
        x_row_5_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln119_fu_198_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_row_6_out_ap_vld = 1'b1;
    end else begin
        x_row_6_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln119_fu_198_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_row_out_ap_vld = 1'b1;
    end else begin
        x_row_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln119_fu_204_p2 = (ap_sig_allocacmp_j_1 + 3'd1);

assign and_ln127_fu_284_p2 = (icmp_ln127_reg_380 & S_AXIS_TLAST);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = ((icmp_ln119_reg_376 == 1'd0) & (1'b0 == S_AXIS_TVALID));
end

always @ (*) begin
    ap_condition_250 = ((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln119_reg_376 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign icmp_ln119_fu_198_p2 = ((ap_sig_allocacmp_j_1 == 3'd7) ? 1'b1 : 1'b0);

assign icmp_ln127_fu_226_p2 = ((ap_sig_allocacmp_j_1 == 3'd6) ? 1'b1 : 1'b0);

assign last_sample_1_fu_289_p2 = (last_sample_reg_178 | and_ln127_fu_284_p2);

assign last_sample_out = last_sample_reg_178;

assign x_row_1_out = x_row_1_fu_86;

assign x_row_2_out = x_row_2_fu_90;

assign x_row_3_out = x_row_3_fu_94;

assign x_row_4_out = x_row_4_fu_98;

assign x_row_5_out = x_row_5_fu_102;

assign x_row_6_out = x_row_6_fu_106;

assign x_row_7_fu_245_p1 = S_AXIS_TDATA[7:0];

assign x_row_out = x_row_fu_82;

endmodule //nn_accelerator_nn_accelerator_Pipeline_read_features
