domain_path: C:\Users\dkhar\OneDrive\Documents\GitHub\ee4218\platform\zynqmp_fsbl\zynqmp_fsbl_bsp
app_src_dir: C:\Xilinx\2025.1\Vitis\data\embeddedsw\lib\sw_apps\zynqmp_fsbl
template: zynqmp_fsbl
lang: c
