// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module nn_accelerator_nn_accelerator_Pipeline_read_input_data_VITIS_LOOP_97_3 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        S_AXIS_TVALID,
        X_address0,
        X_ce0,
        X_we0,
        X_d0,
        X_1_address0,
        X_1_ce0,
        X_1_we0,
        X_1_d0,
        X_2_address0,
        X_2_ce0,
        X_2_we0,
        X_2_d0,
        X_3_address0,
        X_3_ce0,
        X_3_we0,
        X_3_d0,
        X_4_address0,
        X_4_ce0,
        X_4_we0,
        X_4_d0,
        X_5_address0,
        X_5_ce0,
        X_5_we0,
        X_5_d0,
        X_6_address0,
        X_6_ce0,
        X_6_we0,
        X_6_d0,
        S_AXIS_TDATA,
        S_AXIS_TREADY,
        S_AXIS_TKEEP,
        S_AXIS_TSTRB,
        S_AXIS_TLAST
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   S_AXIS_TVALID;
output  [5:0] X_address0;
output   X_ce0;
output   X_we0;
output  [7:0] X_d0;
output  [5:0] X_1_address0;
output   X_1_ce0;
output   X_1_we0;
output  [7:0] X_1_d0;
output  [5:0] X_2_address0;
output   X_2_ce0;
output   X_2_we0;
output  [7:0] X_2_d0;
output  [5:0] X_3_address0;
output   X_3_ce0;
output   X_3_we0;
output  [7:0] X_3_d0;
output  [5:0] X_4_address0;
output   X_4_ce0;
output   X_4_we0;
output  [7:0] X_4_d0;
output  [5:0] X_5_address0;
output   X_5_ce0;
output   X_5_we0;
output  [7:0] X_5_d0;
output  [5:0] X_6_address0;
output   X_6_ce0;
output   X_6_we0;
output  [7:0] X_6_d0;
input  [31:0] S_AXIS_TDATA;
output   S_AXIS_TREADY;
input  [3:0] S_AXIS_TKEEP;
input  [3:0] S_AXIS_TSTRB;
input  [0:0] S_AXIS_TLAST;

reg ap_idle;
reg S_AXIS_TREADY;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln96_fu_213_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    S_AXIS_TDATA_blk_n;
wire    ap_block_pp0_stage0_grp1;
wire   [63:0] zext_ln96_fu_264_p1;
reg   [2:0] j_fu_80;
wire   [2:0] add_ln97_fu_306_p2;
reg    ap_block_pp0_stage0_11001_grp1;
wire    ap_loop_init;
reg   [6:0] i_fu_84;
wire   [6:0] select_ln96_fu_256_p3;
reg   [8:0] indvar_flatten6_fu_88;
wire   [8:0] add_ln96_1_fu_219_p2;
reg    ap_block_pp0_stage0_11001;
reg   [8:0] ap_sig_allocacmp_indvar_flatten6_load;
wire    ap_block_pp0_stage0;
reg    X_5_we0_local;
wire   [2:0] select_ln73_fu_248_p3;
wire   [7:0] trunc_ln100_fu_279_p1;
reg    X_5_ce0_local;
reg    X_4_we0_local;
reg    X_4_ce0_local;
reg    X_3_we0_local;
reg    X_3_ce0_local;
reg    X_2_we0_local;
reg    X_2_ce0_local;
reg    X_1_we0_local;
reg    X_1_ce0_local;
reg    X_we0_local;
reg    X_ce0_local;
reg    X_6_we0_local;
reg    X_6_ce0_local;
wire   [0:0] icmp_ln97_fu_242_p2;
wire   [6:0] add_ln96_fu_236_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 j_fu_80 = 3'd0;
#0 i_fu_84 = 7'd0;
#0 indvar_flatten6_fu_88 = 9'd0;
#0 ap_done_reg = 1'b0;
end

nn_accelerator_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            i_fu_84 <= 7'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            i_fu_84 <= select_ln96_fu_256_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln96_fu_213_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten6_fu_88 <= add_ln96_1_fu_219_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten6_fu_88 <= 9'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            j_fu_80 <= 3'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            j_fu_80 <= add_ln97_fu_306_p2;
        end
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        S_AXIS_TDATA_blk_n = S_AXIS_TVALID;
    end else begin
        S_AXIS_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        S_AXIS_TREADY = 1'b1;
    end else begin
        S_AXIS_TREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_1_ce0_local = 1'b1;
    end else begin
        X_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (select_ln73_fu_248_p3 == 3'd1))) begin
        X_1_we0_local = 1'b1;
    end else begin
        X_1_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_2_ce0_local = 1'b1;
    end else begin
        X_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (select_ln73_fu_248_p3 == 3'd2))) begin
        X_2_we0_local = 1'b1;
    end else begin
        X_2_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_3_ce0_local = 1'b1;
    end else begin
        X_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (select_ln73_fu_248_p3 == 3'd3))) begin
        X_3_we0_local = 1'b1;
    end else begin
        X_3_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_4_ce0_local = 1'b1;
    end else begin
        X_4_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (select_ln73_fu_248_p3 == 3'd4))) begin
        X_4_we0_local = 1'b1;
    end else begin
        X_4_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_5_ce0_local = 1'b1;
    end else begin
        X_5_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (select_ln73_fu_248_p3 == 3'd5))) begin
        X_5_we0_local = 1'b1;
    end else begin
        X_5_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_6_ce0_local = 1'b1;
    end else begin
        X_6_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & ((select_ln73_fu_248_p3 == 3'd6) | (select_ln73_fu_248_p3 == 3'd7)))) begin
        X_6_we0_local = 1'b1;
    end else begin
        X_6_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_ce0_local = 1'b1;
    end else begin
        X_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (select_ln73_fu_248_p3 == 3'd0))) begin
        X_we0_local = 1'b1;
    end else begin
        X_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln96_fu_213_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten6_load = 9'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten6_load = indvar_flatten6_fu_88;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign X_1_address0 = zext_ln96_fu_264_p1;

assign X_1_ce0 = X_1_ce0_local;

assign X_1_d0 = trunc_ln100_fu_279_p1;

assign X_1_we0 = X_1_we0_local;

assign X_2_address0 = zext_ln96_fu_264_p1;

assign X_2_ce0 = X_2_ce0_local;

assign X_2_d0 = trunc_ln100_fu_279_p1;

assign X_2_we0 = X_2_we0_local;

assign X_3_address0 = zext_ln96_fu_264_p1;

assign X_3_ce0 = X_3_ce0_local;

assign X_3_d0 = trunc_ln100_fu_279_p1;

assign X_3_we0 = X_3_we0_local;

assign X_4_address0 = zext_ln96_fu_264_p1;

assign X_4_ce0 = X_4_ce0_local;

assign X_4_d0 = trunc_ln100_fu_279_p1;

assign X_4_we0 = X_4_we0_local;

assign X_5_address0 = zext_ln96_fu_264_p1;

assign X_5_ce0 = X_5_ce0_local;

assign X_5_d0 = trunc_ln100_fu_279_p1;

assign X_5_we0 = X_5_we0_local;

assign X_6_address0 = zext_ln96_fu_264_p1;

assign X_6_ce0 = X_6_ce0_local;

assign X_6_d0 = trunc_ln100_fu_279_p1;

assign X_6_we0 = X_6_we0_local;

assign X_address0 = zext_ln96_fu_264_p1;

assign X_ce0 = X_ce0_local;

assign X_d0 = trunc_ln100_fu_279_p1;

assign X_we0 = X_we0_local;

assign add_ln96_1_fu_219_p2 = (ap_sig_allocacmp_indvar_flatten6_load + 9'd1);

assign add_ln96_fu_236_p2 = (i_fu_84 + 7'd1);

assign add_ln97_fu_306_p2 = (select_ln73_fu_248_p3 + 3'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((1'b0 == S_AXIS_TVALID) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_grp1 = ((1'b0 == S_AXIS_TVALID) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

assign ap_block_pp0_stage0_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((1'b0 == S_AXIS_TVALID) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign icmp_ln96_fu_213_p2 = ((ap_sig_allocacmp_indvar_flatten6_load == 9'd448) ? 1'b1 : 1'b0);

assign icmp_ln97_fu_242_p2 = ((j_fu_80 == 3'd7) ? 1'b1 : 1'b0);

assign select_ln73_fu_248_p3 = ((icmp_ln97_fu_242_p2[0:0] == 1'b1) ? 3'd0 : j_fu_80);

assign select_ln96_fu_256_p3 = ((icmp_ln97_fu_242_p2[0:0] == 1'b1) ? add_ln96_fu_236_p2 : i_fu_84);

assign trunc_ln100_fu_279_p1 = S_AXIS_TDATA[7:0];

assign zext_ln96_fu_264_p1 = select_ln96_fu_256_p3;

endmodule //nn_accelerator_nn_accelerator_Pipeline_read_input_data_VITIS_LOOP_97_3
