// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module nn_accelerator_nn_accelerator_Pipeline_hidden_layer_VITIS_LOOP_106_4 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        X_address0,
        X_ce0,
        X_q0,
        X_1_address0,
        X_1_ce0,
        X_1_q0,
        X_2_address0,
        X_2_ce0,
        X_2_q0,
        X_3_address0,
        X_3_ce0,
        X_3_q0,
        X_4_address0,
        X_4_ce0,
        X_4_q0,
        X_5_address0,
        X_5_ce0,
        X_5_q0,
        X_6_address0,
        X_6_ce0,
        X_6_q0,
        hidden_address0,
        hidden_ce0,
        hidden_we0,
        hidden_d0,
        W_hidden_1_load,
        W_hidden_load,
        W_hidden_1_load_1,
        W_hidden_load_1,
        W_hidden_1_load_2,
        W_hidden_load_2,
        W_hidden_1_load_3,
        W_hidden_load_3,
        W_hidden_1_load_4,
        W_hidden_load_4,
        W_hidden_1_load_5,
        W_hidden_load_5,
        W_hidden_1_load_6,
        W_hidden_load_6,
        W_hidden_1_load_7,
        W_hidden_load_7
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [5:0] X_address0;
output   X_ce0;
input  [7:0] X_q0;
output  [5:0] X_1_address0;
output   X_1_ce0;
input  [7:0] X_1_q0;
output  [5:0] X_2_address0;
output   X_2_ce0;
input  [7:0] X_2_q0;
output  [5:0] X_3_address0;
output   X_3_ce0;
input  [7:0] X_3_q0;
output  [5:0] X_4_address0;
output   X_4_ce0;
input  [7:0] X_4_q0;
output  [5:0] X_5_address0;
output   X_5_ce0;
input  [7:0] X_5_q0;
output  [5:0] X_6_address0;
output   X_6_ce0;
input  [7:0] X_6_q0;
output  [6:0] hidden_address0;
output   hidden_ce0;
output   hidden_we0;
output  [7:0] hidden_d0;
input  [7:0] W_hidden_1_load;
input  [7:0] W_hidden_load;
input  [7:0] W_hidden_1_load_1;
input  [7:0] W_hidden_load_1;
input  [7:0] W_hidden_1_load_2;
input  [7:0] W_hidden_load_2;
input  [7:0] W_hidden_1_load_3;
input  [7:0] W_hidden_load_3;
input  [7:0] W_hidden_1_load_4;
input  [7:0] W_hidden_load_4;
input  [7:0] W_hidden_1_load_5;
input  [7:0] W_hidden_load_5;
input  [7:0] W_hidden_1_load_6;
input  [7:0] W_hidden_load_6;
input  [7:0] W_hidden_1_load_7;
input  [7:0] W_hidden_load_7;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln105_fu_342_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [7:0] sigmoid_lut_address0;
wire   [7:0] sigmoid_lut_q0;
wire    ap_block_pp0_stage0_11001;
wire   [0:0] and_ln73_fu_382_p2;
reg   [0:0] and_ln73_reg_734;
reg   [0:0] and_ln73_reg_734_pp0_iter1_reg;
reg   [0:0] and_ln73_reg_734_pp0_iter2_reg;
reg   [0:0] and_ln73_reg_734_pp0_iter3_reg;
reg   [0:0] and_ln73_reg_734_pp0_iter4_reg;
wire   [5:0] trunc_ln105_fu_396_p1;
reg   [5:0] trunc_ln105_reg_747;
reg   [5:0] trunc_ln105_reg_747_pp0_iter1_reg;
reg   [5:0] trunc_ln105_reg_747_pp0_iter2_reg;
reg   [5:0] trunc_ln105_reg_747_pp0_iter3_reg;
reg   [5:0] trunc_ln105_reg_747_pp0_iter4_reg;
wire   [63:0] zext_ln105_fu_400_p1;
reg   [63:0] zext_ln105_reg_752;
reg   [63:0] zext_ln105_reg_752_pp0_iter1_reg;
wire   [15:0] mul_ln111_1_fu_535_p2;
wire   [15:0] mul_ln111_3_fu_541_p2;
wire   [15:0] mul_ln111_5_fu_547_p2;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln55_fu_577_p1;
wire   [63:0] zext_ln116_fu_588_p1;
reg   [1:0] j_fu_98;
wire   [1:0] select_ln106_fu_408_p3;
wire    ap_loop_init;
reg   [1:0] ap_sig_allocacmp_j_load;
reg   [6:0] i_fu_102;
wire   [6:0] select_ln105_fu_388_p3;
reg   [6:0] ap_sig_allocacmp_i_load;
reg   [7:0] indvar_flatten13_fu_106;
wire   [7:0] add_ln105_1_fu_348_p2;
reg   [7:0] ap_sig_allocacmp_indvar_flatten13_load;
reg    X_ce0_local;
reg    X_2_ce0_local;
reg    X_4_ce0_local;
reg    X_6_ce0_local;
reg    X_1_ce0_local;
reg    X_3_ce0_local;
reg    X_5_ce0_local;
reg    sigmoid_lut_ce0_local;
reg    hidden_we0_local;
reg    hidden_ce0_local;
wire   [0:0] icmp_ln106_fu_370_p2;
wire   [0:0] trunc_ln73_fu_360_p1;
wire   [0:0] xor_ln73_fu_376_p2;
wire   [6:0] add_ln105_fu_364_p2;
wire   [7:0] select_ln111_fu_447_p3;
wire   [7:0] select_ln111_2_fu_456_p3;
wire   [7:0] select_ln111_4_fu_465_p3;
wire   [7:0] select_ln111_6_fu_474_p3;
wire   [7:0] select_ln108_fu_495_p3;
wire   [7:0] select_ln111_1_fu_508_p3;
wire   [7:0] select_ln111_3_fu_517_p3;
wire   [7:0] select_ln111_5_fu_526_p3;
wire   [7:0] mul_ln111_1_fu_535_p0;
wire   [7:0] mul_ln111_1_fu_535_p1;
wire   [7:0] mul_ln111_3_fu_541_p0;
wire   [7:0] mul_ln111_3_fu_541_p1;
wire   [7:0] mul_ln111_5_fu_547_p0;
wire   [7:0] mul_ln111_5_fu_547_p1;
wire   [15:0] grp_fu_611_p3;
wire   [15:0] grp_fu_620_p3;
wire   [15:0] grp_fu_593_p3;
wire   [15:0] grp_fu_602_p3;
(* use_dsp48 = "no" *) wire   [15:0] add_ln111_5_fu_557_p2;
(* use_dsp48 = "no" *) wire   [15:0] add_ln111_2_fu_553_p2;
wire   [15:0] acc_fu_561_p2;
wire   [7:0] acc_7_fu_567_p4;
wire   [6:0] add_ln_fu_582_p3;
wire   [7:0] grp_fu_593_p0;
wire   [7:0] grp_fu_593_p1;
wire   [7:0] grp_fu_602_p0;
wire   [7:0] grp_fu_602_p1;
wire   [7:0] grp_fu_611_p0;
wire   [7:0] grp_fu_611_p1;
wire   [7:0] grp_fu_620_p0;
wire   [7:0] grp_fu_620_p1;
wire   [15:0] grp_fu_620_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [15:0] grp_fu_593_p00;
wire   [15:0] grp_fu_593_p10;
wire   [15:0] grp_fu_602_p00;
wire   [15:0] grp_fu_602_p10;
wire   [15:0] grp_fu_611_p00;
wire   [15:0] grp_fu_611_p10;
wire   [15:0] grp_fu_620_p00;
wire   [15:0] grp_fu_620_p10;
wire   [15:0] mul_ln111_1_fu_535_p00;
wire   [15:0] mul_ln111_1_fu_535_p10;
wire   [15:0] mul_ln111_3_fu_541_p00;
wire   [15:0] mul_ln111_3_fu_541_p10;
wire   [15:0] mul_ln111_5_fu_547_p00;
wire   [15:0] mul_ln111_5_fu_547_p10;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 j_fu_98 = 2'd0;
#0 i_fu_102 = 7'd0;
#0 indvar_flatten13_fu_106 = 8'd0;
#0 ap_done_reg = 1'b0;
end

nn_accelerator_nn_accelerator_Pipeline_hidden_layer_VITIS_LOOP_106_4_sigmoid_lut_ROM_AUTO_1R #(
    .DataWidth( 8 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
sigmoid_lut_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(sigmoid_lut_address0),
    .ce0(sigmoid_lut_ce0_local),
    .q0(sigmoid_lut_q0)
);

nn_accelerator_mul_8ns_8ns_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
mul_8ns_8ns_16_1_1_U25(
    .din0(mul_ln111_1_fu_535_p0),
    .din1(mul_ln111_1_fu_535_p1),
    .dout(mul_ln111_1_fu_535_p2)
);

nn_accelerator_mul_8ns_8ns_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
mul_8ns_8ns_16_1_1_U26(
    .din0(mul_ln111_3_fu_541_p0),
    .din1(mul_ln111_3_fu_541_p1),
    .dout(mul_ln111_3_fu_541_p2)
);

nn_accelerator_mul_8ns_8ns_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
mul_8ns_8ns_16_1_1_U27(
    .din0(mul_ln111_5_fu_547_p0),
    .din1(mul_ln111_5_fu_547_p1),
    .dout(mul_ln111_5_fu_547_p2)
);

nn_accelerator_mac_muladd_8ns_8ns_16ns_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
mac_muladd_8ns_8ns_16ns_16_4_1_U28(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_593_p0),
    .din1(grp_fu_593_p1),
    .din2(mul_ln111_1_fu_535_p2),
    .ce(1'b1),
    .dout(grp_fu_593_p3)
);

nn_accelerator_mac_muladd_8ns_8ns_16ns_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
mac_muladd_8ns_8ns_16ns_16_4_1_U29(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_602_p0),
    .din1(grp_fu_602_p1),
    .din2(mul_ln111_3_fu_541_p2),
    .ce(1'b1),
    .dout(grp_fu_602_p3)
);

nn_accelerator_mac_muladd_8ns_8ns_16ns_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
mac_muladd_8ns_8ns_16ns_16_4_1_U30(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_611_p0),
    .din1(grp_fu_611_p1),
    .din2(mul_ln111_5_fu_547_p2),
    .ce(1'b1),
    .dout(grp_fu_611_p3)
);

nn_accelerator_mac_muladd_8ns_8ns_16ns_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
mac_muladd_8ns_8ns_16ns_16_4_1_U31(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_620_p0),
    .din1(grp_fu_620_p1),
    .din2(grp_fu_620_p2),
    .ce(1'b1),
    .dout(grp_fu_620_p3)
);

nn_accelerator_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter4_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln105_fu_342_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_fu_102 <= select_ln105_fu_388_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_102 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln105_fu_342_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten13_fu_106 <= add_ln105_1_fu_348_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten13_fu_106 <= 8'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln105_fu_342_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            j_fu_98 <= select_ln106_fu_408_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            j_fu_98 <= 2'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        and_ln73_reg_734 <= and_ln73_fu_382_p2;
        and_ln73_reg_734_pp0_iter1_reg <= and_ln73_reg_734;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        trunc_ln105_reg_747 <= trunc_ln105_fu_396_p1;
        trunc_ln105_reg_747_pp0_iter1_reg <= trunc_ln105_reg_747;
        zext_ln105_reg_752[6 : 0] <= zext_ln105_fu_400_p1[6 : 0];
        zext_ln105_reg_752_pp0_iter1_reg[6 : 0] <= zext_ln105_reg_752[6 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        and_ln73_reg_734_pp0_iter2_reg <= and_ln73_reg_734_pp0_iter1_reg;
        and_ln73_reg_734_pp0_iter3_reg <= and_ln73_reg_734_pp0_iter2_reg;
        and_ln73_reg_734_pp0_iter4_reg <= and_ln73_reg_734_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        trunc_ln105_reg_747_pp0_iter2_reg <= trunc_ln105_reg_747_pp0_iter1_reg;
        trunc_ln105_reg_747_pp0_iter3_reg <= trunc_ln105_reg_747_pp0_iter2_reg;
        trunc_ln105_reg_747_pp0_iter4_reg <= trunc_ln105_reg_747_pp0_iter3_reg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        X_1_ce0_local = 1'b1;
    end else begin
        X_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_2_ce0_local = 1'b1;
    end else begin
        X_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        X_3_ce0_local = 1'b1;
    end else begin
        X_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_4_ce0_local = 1'b1;
    end else begin
        X_4_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        X_5_ce0_local = 1'b1;
    end else begin
        X_5_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_6_ce0_local = 1'b1;
    end else begin
        X_6_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_ce0_local = 1'b1;
    end else begin
        X_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln105_fu_342_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter4_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_i_load = 7'd0;
    end else begin
        ap_sig_allocacmp_i_load = i_fu_102;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten13_load = 8'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten13_load = indvar_flatten13_fu_106;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_j_load = 2'd0;
    end else begin
        ap_sig_allocacmp_j_load = j_fu_98;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        hidden_ce0_local = 1'b1;
    end else begin
        hidden_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        hidden_we0_local = 1'b1;
    end else begin
        hidden_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        sigmoid_lut_ce0_local = 1'b1;
    end else begin
        sigmoid_lut_ce0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign X_1_address0 = zext_ln105_reg_752_pp0_iter1_reg;

assign X_1_ce0 = X_1_ce0_local;

assign X_2_address0 = zext_ln105_fu_400_p1;

assign X_2_ce0 = X_2_ce0_local;

assign X_3_address0 = zext_ln105_reg_752_pp0_iter1_reg;

assign X_3_ce0 = X_3_ce0_local;

assign X_4_address0 = zext_ln105_fu_400_p1;

assign X_4_ce0 = X_4_ce0_local;

assign X_5_address0 = zext_ln105_reg_752_pp0_iter1_reg;

assign X_5_ce0 = X_5_ce0_local;

assign X_6_address0 = zext_ln105_fu_400_p1;

assign X_6_ce0 = X_6_ce0_local;

assign X_address0 = zext_ln105_fu_400_p1;

assign X_ce0 = X_ce0_local;

assign acc_7_fu_567_p4 = {{acc_fu_561_p2[15:8]}};

assign acc_fu_561_p2 = (add_ln111_5_fu_557_p2 + add_ln111_2_fu_553_p2);

assign add_ln105_1_fu_348_p2 = (ap_sig_allocacmp_indvar_flatten13_load + 8'd1);

assign add_ln105_fu_364_p2 = (ap_sig_allocacmp_i_load + 7'd1);

assign add_ln111_2_fu_553_p2 = (grp_fu_611_p3 + grp_fu_620_p3);

assign add_ln111_5_fu_557_p2 = (grp_fu_593_p3 + grp_fu_602_p3);

assign add_ln_fu_582_p3 = {{trunc_ln105_reg_747_pp0_iter4_reg}, {and_ln73_reg_734_pp0_iter4_reg}};

assign and_ln73_fu_382_p2 = (xor_ln73_fu_376_p2 & trunc_ln73_fu_360_p1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign grp_fu_593_p0 = grp_fu_593_p00;

assign grp_fu_593_p00 = select_ln111_6_fu_474_p3;

assign grp_fu_593_p1 = grp_fu_593_p10;

assign grp_fu_593_p10 = X_6_q0;

assign grp_fu_602_p0 = grp_fu_602_p00;

assign grp_fu_602_p00 = select_ln111_4_fu_465_p3;

assign grp_fu_602_p1 = grp_fu_602_p10;

assign grp_fu_602_p10 = X_4_q0;

assign grp_fu_611_p0 = grp_fu_611_p00;

assign grp_fu_611_p00 = select_ln111_2_fu_456_p3;

assign grp_fu_611_p1 = grp_fu_611_p10;

assign grp_fu_611_p10 = X_2_q0;

assign grp_fu_620_p0 = grp_fu_620_p00;

assign grp_fu_620_p00 = select_ln111_fu_447_p3;

assign grp_fu_620_p1 = grp_fu_620_p10;

assign grp_fu_620_p10 = X_q0;

assign grp_fu_620_p2 = {{select_ln108_fu_495_p3}, {8'd0}};

assign hidden_address0 = zext_ln116_fu_588_p1;

assign hidden_ce0 = hidden_ce0_local;

assign hidden_d0 = sigmoid_lut_q0;

assign hidden_we0 = hidden_we0_local;

assign icmp_ln105_fu_342_p2 = ((ap_sig_allocacmp_indvar_flatten13_load == 8'd128) ? 1'b1 : 1'b0);

assign icmp_ln106_fu_370_p2 = ((ap_sig_allocacmp_j_load == 2'd2) ? 1'b1 : 1'b0);

assign mul_ln111_1_fu_535_p0 = mul_ln111_1_fu_535_p00;

assign mul_ln111_1_fu_535_p00 = select_ln111_5_fu_526_p3;

assign mul_ln111_1_fu_535_p1 = mul_ln111_1_fu_535_p10;

assign mul_ln111_1_fu_535_p10 = X_5_q0;

assign mul_ln111_3_fu_541_p0 = mul_ln111_3_fu_541_p00;

assign mul_ln111_3_fu_541_p00 = select_ln111_3_fu_517_p3;

assign mul_ln111_3_fu_541_p1 = mul_ln111_3_fu_541_p10;

assign mul_ln111_3_fu_541_p10 = X_3_q0;

assign mul_ln111_5_fu_547_p0 = mul_ln111_5_fu_547_p00;

assign mul_ln111_5_fu_547_p00 = select_ln111_1_fu_508_p3;

assign mul_ln111_5_fu_547_p1 = mul_ln111_5_fu_547_p10;

assign mul_ln111_5_fu_547_p10 = X_1_q0;

assign select_ln105_fu_388_p3 = ((icmp_ln106_fu_370_p2[0:0] == 1'b1) ? add_ln105_fu_364_p2 : ap_sig_allocacmp_i_load);

assign select_ln106_fu_408_p3 = ((and_ln73_fu_382_p2[0:0] == 1'b1) ? 2'd2 : 2'd1);

assign select_ln108_fu_495_p3 = ((and_ln73_reg_734_pp0_iter2_reg[0:0] == 1'b1) ? W_hidden_1_load : W_hidden_load);

assign select_ln111_1_fu_508_p3 = ((and_ln73_reg_734_pp0_iter2_reg[0:0] == 1'b1) ? W_hidden_1_load_2 : W_hidden_load_2);

assign select_ln111_2_fu_456_p3 = ((and_ln73_reg_734[0:0] == 1'b1) ? W_hidden_1_load_3 : W_hidden_load_3);

assign select_ln111_3_fu_517_p3 = ((and_ln73_reg_734_pp0_iter2_reg[0:0] == 1'b1) ? W_hidden_1_load_4 : W_hidden_load_4);

assign select_ln111_4_fu_465_p3 = ((and_ln73_reg_734[0:0] == 1'b1) ? W_hidden_1_load_5 : W_hidden_load_5);

assign select_ln111_5_fu_526_p3 = ((and_ln73_reg_734_pp0_iter2_reg[0:0] == 1'b1) ? W_hidden_1_load_6 : W_hidden_load_6);

assign select_ln111_6_fu_474_p3 = ((and_ln73_reg_734[0:0] == 1'b1) ? W_hidden_1_load_7 : W_hidden_load_7);

assign select_ln111_fu_447_p3 = ((and_ln73_reg_734[0:0] == 1'b1) ? W_hidden_1_load_1 : W_hidden_load_1);

assign sigmoid_lut_address0 = zext_ln55_fu_577_p1;

assign trunc_ln105_fu_396_p1 = select_ln105_fu_388_p3[5:0];

assign trunc_ln73_fu_360_p1 = ap_sig_allocacmp_j_load[0:0];

assign xor_ln73_fu_376_p2 = (icmp_ln106_fu_370_p2 ^ 1'd1);

assign zext_ln105_fu_400_p1 = select_ln105_fu_388_p3;

assign zext_ln116_fu_588_p1 = add_ln_fu_582_p3;

assign zext_ln55_fu_577_p1 = acc_7_fu_567_p4;

always @ (posedge ap_clk) begin
    zext_ln105_reg_752[63:7] <= 57'b000000000000000000000000000000000000000000000000000000000;
    zext_ln105_reg_752_pp0_iter1_reg[63:7] <= 57'b000000000000000000000000000000000000000000000000000000000;
end

endmodule //nn_accelerator_nn_accelerator_Pipeline_hidden_layer_VITIS_LOOP_106_4
