// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="nn_accelerator_nn_accelerator,hls_ip_2025_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xck26-sfvc784-2LV-c,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=3.620000,HLS_SYN_LAT=756,HLS_SYN_TPT=none,HLS_SYN_MEM=2,HLS_SYN_DSP=0,HLS_SYN_FF=646,HLS_SYN_LUT=1707,HLS_VERSION=2025_1}" *)

module nn_accelerator (
        ap_clk,
        ap_rst_n,
        S_AXIS_TDATA,
        S_AXIS_TVALID,
        S_AXIS_TREADY,
        S_AXIS_TKEEP,
        S_AXIS_TSTRB,
        S_AXIS_TLAST,
        M_AXIS_TDATA,
        M_AXIS_TVALID,
        M_AXIS_TREADY,
        M_AXIS_TKEEP,
        M_AXIS_TSTRB,
        M_AXIS_TLAST
);

parameter    ap_ST_fsm_state1 = 14'd1;
parameter    ap_ST_fsm_state2 = 14'd2;
parameter    ap_ST_fsm_state3 = 14'd4;
parameter    ap_ST_fsm_state4 = 14'd8;
parameter    ap_ST_fsm_state5 = 14'd16;
parameter    ap_ST_fsm_state6 = 14'd32;
parameter    ap_ST_fsm_state7 = 14'd64;
parameter    ap_ST_fsm_state8 = 14'd128;
parameter    ap_ST_fsm_state9 = 14'd256;
parameter    ap_ST_fsm_state10 = 14'd512;
parameter    ap_ST_fsm_state11 = 14'd1024;
parameter    ap_ST_fsm_state12 = 14'd2048;
parameter    ap_ST_fsm_state13 = 14'd4096;
parameter    ap_ST_fsm_state14 = 14'd8192;

input   ap_clk;
input   ap_rst_n;
input  [31:0] S_AXIS_TDATA;
input   S_AXIS_TVALID;
output   S_AXIS_TREADY;
input  [3:0] S_AXIS_TKEEP;
input  [3:0] S_AXIS_TSTRB;
input  [0:0] S_AXIS_TLAST;
output  [31:0] M_AXIS_TDATA;
output   M_AXIS_TVALID;
input   M_AXIS_TREADY;
output  [3:0] M_AXIS_TKEEP;
output  [3:0] M_AXIS_TSTRB;
output  [0:0] M_AXIS_TLAST;

 reg    ap_rst_n_inv;
(* fsm_encoding = "none" *) reg   [13:0] ap_CS_fsm;
wire    ap_CS_fsm_state4;
reg   [7:0] W_hidden_load_reg_444;
wire    ap_CS_fsm_state5;
reg   [7:0] W_hidden_1_load_reg_449;
reg   [7:0] W_hidden_load_1_reg_454;
reg   [7:0] W_hidden_1_load_1_reg_459;
reg   [7:0] W_hidden_load_2_reg_484;
wire    ap_CS_fsm_state6;
reg   [7:0] W_hidden_1_load_2_reg_489;
reg   [7:0] W_hidden_load_3_reg_494;
reg   [7:0] W_hidden_1_load_3_reg_499;
reg   [7:0] W_hidden_load_4_reg_524;
wire    ap_CS_fsm_state7;
reg   [7:0] W_hidden_1_load_4_reg_529;
reg   [7:0] W_hidden_load_5_reg_534;
reg   [7:0] W_hidden_1_load_5_reg_539;
reg   [7:0] W_hidden_load_6_reg_564;
wire    ap_CS_fsm_state8;
reg   [7:0] W_hidden_1_load_6_reg_569;
reg   [7:0] W_hidden_load_7_reg_574;
reg   [7:0] W_hidden_1_load_7_reg_579;
wire   [15:0] acc_fu_397_p3;
reg   [15:0] acc_reg_590;
wire    ap_CS_fsm_state10;
reg   [5:0] X_address0;
reg    X_ce0;
reg    X_we0;
wire   [7:0] X_q0;
reg   [5:0] X_1_address0;
reg    X_1_ce0;
reg    X_1_we0;
wire   [7:0] X_1_q0;
reg   [5:0] X_2_address0;
reg    X_2_ce0;
reg    X_2_we0;
wire   [7:0] X_2_q0;
reg   [5:0] X_3_address0;
reg    X_3_ce0;
reg    X_3_we0;
wire   [7:0] X_3_q0;
reg   [5:0] X_4_address0;
reg    X_4_ce0;
reg    X_4_we0;
wire   [7:0] X_4_q0;
reg   [5:0] X_5_address0;
reg    X_5_ce0;
reg    X_5_we0;
wire   [7:0] X_5_q0;
reg   [5:0] X_6_address0;
reg    X_6_ce0;
reg    X_6_we0;
wire   [7:0] X_6_q0;
reg   [2:0] W_hidden_address0;
reg    W_hidden_ce0;
reg    W_hidden_we0;
wire   [7:0] W_hidden_q0;
wire   [7:0] W_hidden_q1;
reg   [2:0] W_hidden_1_address0;
reg    W_hidden_1_ce0;
reg    W_hidden_1_we0;
wire   [7:0] W_hidden_1_q0;
wire   [7:0] W_hidden_1_q1;
reg   [6:0] hidden_address0;
reg    hidden_ce0;
reg    hidden_we0;
wire   [7:0] hidden_q0;
reg    hidden_ce1;
wire   [7:0] hidden_q1;
reg   [5:0] output_data_address0;
reg    output_data_ce0;
reg    output_data_we0;
wire   [0:0] output_data_q0;
wire    grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_79_1_fu_282_ap_start;
wire    grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_79_1_fu_282_ap_done;
wire    grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_79_1_fu_282_ap_idle;
wire    grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_79_1_fu_282_ap_ready;
wire   [2:0] grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_79_1_fu_282_W_hidden_address0;
wire    grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_79_1_fu_282_W_hidden_ce0;
wire    grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_79_1_fu_282_W_hidden_we0;
wire   [7:0] grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_79_1_fu_282_W_hidden_d0;
wire   [2:0] grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_79_1_fu_282_W_hidden_1_address0;
wire    grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_79_1_fu_282_W_hidden_1_ce0;
wire    grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_79_1_fu_282_W_hidden_1_we0;
wire   [7:0] grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_79_1_fu_282_W_hidden_1_d0;
wire    grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_79_1_fu_282_S_AXIS_TREADY;
wire    grp_nn_accelerator_Pipeline_read_output_weights_fu_296_ap_start;
wire    grp_nn_accelerator_Pipeline_read_output_weights_fu_296_ap_done;
wire    grp_nn_accelerator_Pipeline_read_output_weights_fu_296_ap_idle;
wire    grp_nn_accelerator_Pipeline_read_output_weights_fu_296_ap_ready;
wire    grp_nn_accelerator_Pipeline_read_output_weights_fu_296_S_AXIS_TREADY;
wire   [7:0] grp_nn_accelerator_Pipeline_read_output_weights_fu_296_p_0_0388_1750_out;
wire    grp_nn_accelerator_Pipeline_read_output_weights_fu_296_p_0_0388_1750_out_ap_vld;
wire   [7:0] grp_nn_accelerator_Pipeline_read_output_weights_fu_296_p_0_0388748_out;
wire    grp_nn_accelerator_Pipeline_read_output_weights_fu_296_p_0_0388748_out_ap_vld;
wire   [7:0] grp_nn_accelerator_Pipeline_read_output_weights_fu_296_p_0_0396746_out;
wire    grp_nn_accelerator_Pipeline_read_output_weights_fu_296_p_0_0396746_out_ap_vld;
wire    grp_nn_accelerator_Pipeline_read_input_data_VITIS_LOOP_97_3_fu_311_ap_start;
wire    grp_nn_accelerator_Pipeline_read_input_data_VITIS_LOOP_97_3_fu_311_ap_done;
wire    grp_nn_accelerator_Pipeline_read_input_data_VITIS_LOOP_97_3_fu_311_ap_idle;
wire    grp_nn_accelerator_Pipeline_read_input_data_VITIS_LOOP_97_3_fu_311_ap_ready;
wire   [5:0] grp_nn_accelerator_Pipeline_read_input_data_VITIS_LOOP_97_3_fu_311_X_address0;
wire    grp_nn_accelerator_Pipeline_read_input_data_VITIS_LOOP_97_3_fu_311_X_ce0;
wire    grp_nn_accelerator_Pipeline_read_input_data_VITIS_LOOP_97_3_fu_311_X_we0;
wire   [7:0] grp_nn_accelerator_Pipeline_read_input_data_VITIS_LOOP_97_3_fu_311_X_d0;
wire   [5:0] grp_nn_accelerator_Pipeline_read_input_data_VITIS_LOOP_97_3_fu_311_X_1_address0;
wire    grp_nn_accelerator_Pipeline_read_input_data_VITIS_LOOP_97_3_fu_311_X_1_ce0;
wire    grp_nn_accelerator_Pipeline_read_input_data_VITIS_LOOP_97_3_fu_311_X_1_we0;
wire   [7:0] grp_nn_accelerator_Pipeline_read_input_data_VITIS_LOOP_97_3_fu_311_X_1_d0;
wire   [5:0] grp_nn_accelerator_Pipeline_read_input_data_VITIS_LOOP_97_3_fu_311_X_2_address0;
wire    grp_nn_accelerator_Pipeline_read_input_data_VITIS_LOOP_97_3_fu_311_X_2_ce0;
wire    grp_nn_accelerator_Pipeline_read_input_data_VITIS_LOOP_97_3_fu_311_X_2_we0;
wire   [7:0] grp_nn_accelerator_Pipeline_read_input_data_VITIS_LOOP_97_3_fu_311_X_2_d0;
wire   [5:0] grp_nn_accelerator_Pipeline_read_input_data_VITIS_LOOP_97_3_fu_311_X_3_address0;
wire    grp_nn_accelerator_Pipeline_read_input_data_VITIS_LOOP_97_3_fu_311_X_3_ce0;
wire    grp_nn_accelerator_Pipeline_read_input_data_VITIS_LOOP_97_3_fu_311_X_3_we0;
wire   [7:0] grp_nn_accelerator_Pipeline_read_input_data_VITIS_LOOP_97_3_fu_311_X_3_d0;
wire   [5:0] grp_nn_accelerator_Pipeline_read_input_data_VITIS_LOOP_97_3_fu_311_X_4_address0;
wire    grp_nn_accelerator_Pipeline_read_input_data_VITIS_LOOP_97_3_fu_311_X_4_ce0;
wire    grp_nn_accelerator_Pipeline_read_input_data_VITIS_LOOP_97_3_fu_311_X_4_we0;
wire   [7:0] grp_nn_accelerator_Pipeline_read_input_data_VITIS_LOOP_97_3_fu_311_X_4_d0;
wire   [5:0] grp_nn_accelerator_Pipeline_read_input_data_VITIS_LOOP_97_3_fu_311_X_5_address0;
wire    grp_nn_accelerator_Pipeline_read_input_data_VITIS_LOOP_97_3_fu_311_X_5_ce0;
wire    grp_nn_accelerator_Pipeline_read_input_data_VITIS_LOOP_97_3_fu_311_X_5_we0;
wire   [7:0] grp_nn_accelerator_Pipeline_read_input_data_VITIS_LOOP_97_3_fu_311_X_5_d0;
wire   [5:0] grp_nn_accelerator_Pipeline_read_input_data_VITIS_LOOP_97_3_fu_311_X_6_address0;
wire    grp_nn_accelerator_Pipeline_read_input_data_VITIS_LOOP_97_3_fu_311_X_6_ce0;
wire    grp_nn_accelerator_Pipeline_read_input_data_VITIS_LOOP_97_3_fu_311_X_6_we0;
wire   [7:0] grp_nn_accelerator_Pipeline_read_input_data_VITIS_LOOP_97_3_fu_311_X_6_d0;
wire    grp_nn_accelerator_Pipeline_read_input_data_VITIS_LOOP_97_3_fu_311_S_AXIS_TREADY;
wire    grp_nn_accelerator_Pipeline_hidden_layer_VITIS_LOOP_106_4_fu_330_ap_start;
wire    grp_nn_accelerator_Pipeline_hidden_layer_VITIS_LOOP_106_4_fu_330_ap_done;
wire    grp_nn_accelerator_Pipeline_hidden_layer_VITIS_LOOP_106_4_fu_330_ap_idle;
wire    grp_nn_accelerator_Pipeline_hidden_layer_VITIS_LOOP_106_4_fu_330_ap_ready;
wire   [5:0] grp_nn_accelerator_Pipeline_hidden_layer_VITIS_LOOP_106_4_fu_330_X_address0;
wire    grp_nn_accelerator_Pipeline_hidden_layer_VITIS_LOOP_106_4_fu_330_X_ce0;
wire   [5:0] grp_nn_accelerator_Pipeline_hidden_layer_VITIS_LOOP_106_4_fu_330_X_1_address0;
wire    grp_nn_accelerator_Pipeline_hidden_layer_VITIS_LOOP_106_4_fu_330_X_1_ce0;
wire   [5:0] grp_nn_accelerator_Pipeline_hidden_layer_VITIS_LOOP_106_4_fu_330_X_2_address0;
wire    grp_nn_accelerator_Pipeline_hidden_layer_VITIS_LOOP_106_4_fu_330_X_2_ce0;
wire   [5:0] grp_nn_accelerator_Pipeline_hidden_layer_VITIS_LOOP_106_4_fu_330_X_3_address0;
wire    grp_nn_accelerator_Pipeline_hidden_layer_VITIS_LOOP_106_4_fu_330_X_3_ce0;
wire   [5:0] grp_nn_accelerator_Pipeline_hidden_layer_VITIS_LOOP_106_4_fu_330_X_4_address0;
wire    grp_nn_accelerator_Pipeline_hidden_layer_VITIS_LOOP_106_4_fu_330_X_4_ce0;
wire   [5:0] grp_nn_accelerator_Pipeline_hidden_layer_VITIS_LOOP_106_4_fu_330_X_5_address0;
wire    grp_nn_accelerator_Pipeline_hidden_layer_VITIS_LOOP_106_4_fu_330_X_5_ce0;
wire   [5:0] grp_nn_accelerator_Pipeline_hidden_layer_VITIS_LOOP_106_4_fu_330_X_6_address0;
wire    grp_nn_accelerator_Pipeline_hidden_layer_VITIS_LOOP_106_4_fu_330_X_6_ce0;
wire   [6:0] grp_nn_accelerator_Pipeline_hidden_layer_VITIS_LOOP_106_4_fu_330_hidden_address0;
wire    grp_nn_accelerator_Pipeline_hidden_layer_VITIS_LOOP_106_4_fu_330_hidden_ce0;
wire    grp_nn_accelerator_Pipeline_hidden_layer_VITIS_LOOP_106_4_fu_330_hidden_we0;
wire   [7:0] grp_nn_accelerator_Pipeline_hidden_layer_VITIS_LOOP_106_4_fu_330_hidden_d0;
wire    grp_nn_accelerator_Pipeline_output_layer_fu_364_ap_start;
wire    grp_nn_accelerator_Pipeline_output_layer_fu_364_ap_done;
wire    grp_nn_accelerator_Pipeline_output_layer_fu_364_ap_idle;
wire    grp_nn_accelerator_Pipeline_output_layer_fu_364_ap_ready;
wire   [6:0] grp_nn_accelerator_Pipeline_output_layer_fu_364_hidden_address0;
wire    grp_nn_accelerator_Pipeline_output_layer_fu_364_hidden_ce0;
wire   [6:0] grp_nn_accelerator_Pipeline_output_layer_fu_364_hidden_address1;
wire    grp_nn_accelerator_Pipeline_output_layer_fu_364_hidden_ce1;
wire   [5:0] grp_nn_accelerator_Pipeline_output_layer_fu_364_output_data_address0;
wire    grp_nn_accelerator_Pipeline_output_layer_fu_364_output_data_ce0;
wire    grp_nn_accelerator_Pipeline_output_layer_fu_364_output_data_we0;
wire   [0:0] grp_nn_accelerator_Pipeline_output_layer_fu_364_output_data_d0;
wire    grp_nn_accelerator_Pipeline_write_output_data_fu_373_ap_start;
wire    grp_nn_accelerator_Pipeline_write_output_data_fu_373_ap_done;
wire    grp_nn_accelerator_Pipeline_write_output_data_fu_373_ap_idle;
wire    grp_nn_accelerator_Pipeline_write_output_data_fu_373_ap_ready;
wire    grp_nn_accelerator_Pipeline_write_output_data_fu_373_M_AXIS_TREADY;
wire   [5:0] grp_nn_accelerator_Pipeline_write_output_data_fu_373_output_data_address0;
wire    grp_nn_accelerator_Pipeline_write_output_data_fu_373_output_data_ce0;
wire   [31:0] grp_nn_accelerator_Pipeline_write_output_data_fu_373_M_AXIS_TDATA;
wire    grp_nn_accelerator_Pipeline_write_output_data_fu_373_M_AXIS_TVALID;
wire   [3:0] grp_nn_accelerator_Pipeline_write_output_data_fu_373_M_AXIS_TKEEP;
wire   [3:0] grp_nn_accelerator_Pipeline_write_output_data_fu_373_M_AXIS_TSTRB;
wire   [0:0] grp_nn_accelerator_Pipeline_write_output_data_fu_373_M_AXIS_TLAST;
reg    grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_79_1_fu_282_ap_start_reg;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state3;
reg    grp_nn_accelerator_Pipeline_read_output_weights_fu_296_ap_start_reg;
reg    grp_nn_accelerator_Pipeline_read_input_data_VITIS_LOOP_97_3_fu_311_ap_start_reg;
reg    grp_nn_accelerator_Pipeline_hidden_layer_VITIS_LOOP_106_4_fu_330_ap_start_reg;
wire    ap_CS_fsm_state9;
reg    grp_nn_accelerator_Pipeline_output_layer_fu_364_ap_start_reg;
wire    ap_CS_fsm_state11;
reg    grp_nn_accelerator_Pipeline_write_output_data_fu_373_ap_start_reg;
wire    ap_CS_fsm_state12;
wire    ap_CS_fsm_state13;
reg   [31:0] M_AXIS_TDATA_reg;
reg   [3:0] M_AXIS_TKEEP_reg;
reg   [3:0] M_AXIS_TSTRB_reg;
reg   [0:0] M_AXIS_TLAST_reg;
reg    W_hidden_ce1_local;
reg   [2:0] W_hidden_address1_local;
reg    W_hidden_ce0_local;
reg   [2:0] W_hidden_address0_local;
reg    W_hidden_1_ce1_local;
reg   [2:0] W_hidden_1_address1_local;
reg    W_hidden_1_ce0_local;
reg   [2:0] W_hidden_1_address0_local;
reg   [13:0] ap_NS_fsm;
wire    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
reg    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
reg    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
reg    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
reg    ap_ST_fsm_state13_blk;
reg    ap_ST_fsm_state14_blk;
wire    regslice_both_M_AXIS_V_data_V_U_apdone_blk;
wire    ap_CS_fsm_state14;
wire    regslice_both_S_AXIS_V_data_V_U_apdone_blk;
wire   [31:0] S_AXIS_TDATA_int_regslice;
wire    S_AXIS_TVALID_int_regslice;
reg    S_AXIS_TREADY_int_regslice;
wire    regslice_both_S_AXIS_V_data_V_U_ack_in;
wire    regslice_both_S_AXIS_V_keep_V_U_apdone_blk;
wire   [3:0] S_AXIS_TKEEP_int_regslice;
wire    regslice_both_S_AXIS_V_keep_V_U_vld_out;
wire    regslice_both_S_AXIS_V_keep_V_U_ack_in;
wire    regslice_both_S_AXIS_V_strb_V_U_apdone_blk;
wire   [3:0] S_AXIS_TSTRB_int_regslice;
wire    regslice_both_S_AXIS_V_strb_V_U_vld_out;
wire    regslice_both_S_AXIS_V_strb_V_U_ack_in;
wire    regslice_both_S_AXIS_V_last_V_U_apdone_blk;
wire   [0:0] S_AXIS_TLAST_int_regslice;
wire    regslice_both_S_AXIS_V_last_V_U_vld_out;
wire    regslice_both_S_AXIS_V_last_V_U_ack_in;
reg   [31:0] M_AXIS_TDATA_int_regslice;
wire    M_AXIS_TVALID_int_regslice;
wire    M_AXIS_TREADY_int_regslice;
wire    regslice_both_M_AXIS_V_data_V_U_vld_out;
wire    regslice_both_M_AXIS_V_keep_V_U_apdone_blk;
reg   [3:0] M_AXIS_TKEEP_int_regslice;
wire    regslice_both_M_AXIS_V_keep_V_U_ack_in_dummy;
wire    regslice_both_M_AXIS_V_keep_V_U_vld_out;
wire    regslice_both_M_AXIS_V_strb_V_U_apdone_blk;
reg   [3:0] M_AXIS_TSTRB_int_regslice;
wire    regslice_both_M_AXIS_V_strb_V_U_ack_in_dummy;
wire    regslice_both_M_AXIS_V_strb_V_U_vld_out;
wire    regslice_both_M_AXIS_V_last_V_U_apdone_blk;
reg   [0:0] M_AXIS_TLAST_int_regslice;
wire    regslice_both_M_AXIS_V_last_V_U_ack_in_dummy;
wire    regslice_both_M_AXIS_V_last_V_U_vld_out;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 14'd1;
#0 grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_79_1_fu_282_ap_start_reg = 1'b0;
#0 grp_nn_accelerator_Pipeline_read_output_weights_fu_296_ap_start_reg = 1'b0;
#0 grp_nn_accelerator_Pipeline_read_input_data_VITIS_LOOP_97_3_fu_311_ap_start_reg = 1'b0;
#0 grp_nn_accelerator_Pipeline_hidden_layer_VITIS_LOOP_106_4_fu_330_ap_start_reg = 1'b0;
#0 grp_nn_accelerator_Pipeline_output_layer_fu_364_ap_start_reg = 1'b0;
#0 grp_nn_accelerator_Pipeline_write_output_data_fu_373_ap_start_reg = 1'b0;
end

nn_accelerator_X_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
X_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(X_address0),
    .ce0(X_ce0),
    .we0(X_we0),
    .d0(grp_nn_accelerator_Pipeline_read_input_data_VITIS_LOOP_97_3_fu_311_X_d0),
    .q0(X_q0)
);

nn_accelerator_X_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
X_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(X_1_address0),
    .ce0(X_1_ce0),
    .we0(X_1_we0),
    .d0(grp_nn_accelerator_Pipeline_read_input_data_VITIS_LOOP_97_3_fu_311_X_1_d0),
    .q0(X_1_q0)
);

nn_accelerator_X_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
X_2_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(X_2_address0),
    .ce0(X_2_ce0),
    .we0(X_2_we0),
    .d0(grp_nn_accelerator_Pipeline_read_input_data_VITIS_LOOP_97_3_fu_311_X_2_d0),
    .q0(X_2_q0)
);

nn_accelerator_X_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
X_3_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(X_3_address0),
    .ce0(X_3_ce0),
    .we0(X_3_we0),
    .d0(grp_nn_accelerator_Pipeline_read_input_data_VITIS_LOOP_97_3_fu_311_X_3_d0),
    .q0(X_3_q0)
);

nn_accelerator_X_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
X_4_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(X_4_address0),
    .ce0(X_4_ce0),
    .we0(X_4_we0),
    .d0(grp_nn_accelerator_Pipeline_read_input_data_VITIS_LOOP_97_3_fu_311_X_4_d0),
    .q0(X_4_q0)
);

nn_accelerator_X_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
X_5_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(X_5_address0),
    .ce0(X_5_ce0),
    .we0(X_5_we0),
    .d0(grp_nn_accelerator_Pipeline_read_input_data_VITIS_LOOP_97_3_fu_311_X_5_d0),
    .q0(X_5_q0)
);

nn_accelerator_X_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
X_6_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(X_6_address0),
    .ce0(X_6_ce0),
    .we0(X_6_we0),
    .d0(grp_nn_accelerator_Pipeline_read_input_data_VITIS_LOOP_97_3_fu_311_X_6_d0),
    .q0(X_6_q0)
);

nn_accelerator_W_hidden_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
W_hidden_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(W_hidden_address0),
    .ce0(W_hidden_ce0),
    .we0(W_hidden_we0),
    .d0(grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_79_1_fu_282_W_hidden_d0),
    .q0(W_hidden_q0),
    .address1(W_hidden_address1_local),
    .ce1(W_hidden_ce1_local),
    .q1(W_hidden_q1)
);

nn_accelerator_W_hidden_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
W_hidden_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(W_hidden_1_address0),
    .ce0(W_hidden_1_ce0),
    .we0(W_hidden_1_we0),
    .d0(grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_79_1_fu_282_W_hidden_1_d0),
    .q0(W_hidden_1_q0),
    .address1(W_hidden_1_address1_local),
    .ce1(W_hidden_1_ce1_local),
    .q1(W_hidden_1_q1)
);

nn_accelerator_hidden_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 128 ),
    .AddressWidth( 7 ))
hidden_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(hidden_address0),
    .ce0(hidden_ce0),
    .we0(hidden_we0),
    .d0(grp_nn_accelerator_Pipeline_hidden_layer_VITIS_LOOP_106_4_fu_330_hidden_d0),
    .q0(hidden_q0),
    .address1(grp_nn_accelerator_Pipeline_output_layer_fu_364_hidden_address1),
    .ce1(hidden_ce1),
    .q1(hidden_q1)
);

nn_accelerator_output_data_RAM_AUTO_1R1W #(
    .DataWidth( 1 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
output_data_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(output_data_address0),
    .ce0(output_data_ce0),
    .we0(output_data_we0),
    .d0(grp_nn_accelerator_Pipeline_output_layer_fu_364_output_data_d0),
    .q0(output_data_q0)
);

nn_accelerator_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_79_1 grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_79_1_fu_282(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_79_1_fu_282_ap_start),
    .ap_done(grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_79_1_fu_282_ap_done),
    .ap_idle(grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_79_1_fu_282_ap_idle),
    .ap_ready(grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_79_1_fu_282_ap_ready),
    .S_AXIS_TVALID(S_AXIS_TVALID_int_regslice),
    .W_hidden_address0(grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_79_1_fu_282_W_hidden_address0),
    .W_hidden_ce0(grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_79_1_fu_282_W_hidden_ce0),
    .W_hidden_we0(grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_79_1_fu_282_W_hidden_we0),
    .W_hidden_d0(grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_79_1_fu_282_W_hidden_d0),
    .W_hidden_1_address0(grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_79_1_fu_282_W_hidden_1_address0),
    .W_hidden_1_ce0(grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_79_1_fu_282_W_hidden_1_ce0),
    .W_hidden_1_we0(grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_79_1_fu_282_W_hidden_1_we0),
    .W_hidden_1_d0(grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_79_1_fu_282_W_hidden_1_d0),
    .S_AXIS_TDATA(S_AXIS_TDATA_int_regslice),
    .S_AXIS_TREADY(grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_79_1_fu_282_S_AXIS_TREADY),
    .S_AXIS_TKEEP(S_AXIS_TKEEP_int_regslice),
    .S_AXIS_TSTRB(S_AXIS_TSTRB_int_regslice),
    .S_AXIS_TLAST(S_AXIS_TLAST_int_regslice)
);

nn_accelerator_nn_accelerator_Pipeline_read_output_weights grp_nn_accelerator_Pipeline_read_output_weights_fu_296(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_nn_accelerator_Pipeline_read_output_weights_fu_296_ap_start),
    .ap_done(grp_nn_accelerator_Pipeline_read_output_weights_fu_296_ap_done),
    .ap_idle(grp_nn_accelerator_Pipeline_read_output_weights_fu_296_ap_idle),
    .ap_ready(grp_nn_accelerator_Pipeline_read_output_weights_fu_296_ap_ready),
    .S_AXIS_TVALID(S_AXIS_TVALID_int_regslice),
    .S_AXIS_TDATA(S_AXIS_TDATA_int_regslice),
    .S_AXIS_TREADY(grp_nn_accelerator_Pipeline_read_output_weights_fu_296_S_AXIS_TREADY),
    .S_AXIS_TKEEP(S_AXIS_TKEEP_int_regslice),
    .S_AXIS_TSTRB(S_AXIS_TSTRB_int_regslice),
    .S_AXIS_TLAST(S_AXIS_TLAST_int_regslice),
    .p_0_0388_1750_out(grp_nn_accelerator_Pipeline_read_output_weights_fu_296_p_0_0388_1750_out),
    .p_0_0388_1750_out_ap_vld(grp_nn_accelerator_Pipeline_read_output_weights_fu_296_p_0_0388_1750_out_ap_vld),
    .p_0_0388748_out(grp_nn_accelerator_Pipeline_read_output_weights_fu_296_p_0_0388748_out),
    .p_0_0388748_out_ap_vld(grp_nn_accelerator_Pipeline_read_output_weights_fu_296_p_0_0388748_out_ap_vld),
    .p_0_0396746_out(grp_nn_accelerator_Pipeline_read_output_weights_fu_296_p_0_0396746_out),
    .p_0_0396746_out_ap_vld(grp_nn_accelerator_Pipeline_read_output_weights_fu_296_p_0_0396746_out_ap_vld)
);

nn_accelerator_nn_accelerator_Pipeline_read_input_data_VITIS_LOOP_97_3 grp_nn_accelerator_Pipeline_read_input_data_VITIS_LOOP_97_3_fu_311(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_nn_accelerator_Pipeline_read_input_data_VITIS_LOOP_97_3_fu_311_ap_start),
    .ap_done(grp_nn_accelerator_Pipeline_read_input_data_VITIS_LOOP_97_3_fu_311_ap_done),
    .ap_idle(grp_nn_accelerator_Pipeline_read_input_data_VITIS_LOOP_97_3_fu_311_ap_idle),
    .ap_ready(grp_nn_accelerator_Pipeline_read_input_data_VITIS_LOOP_97_3_fu_311_ap_ready),
    .S_AXIS_TVALID(S_AXIS_TVALID_int_regslice),
    .X_address0(grp_nn_accelerator_Pipeline_read_input_data_VITIS_LOOP_97_3_fu_311_X_address0),
    .X_ce0(grp_nn_accelerator_Pipeline_read_input_data_VITIS_LOOP_97_3_fu_311_X_ce0),
    .X_we0(grp_nn_accelerator_Pipeline_read_input_data_VITIS_LOOP_97_3_fu_311_X_we0),
    .X_d0(grp_nn_accelerator_Pipeline_read_input_data_VITIS_LOOP_97_3_fu_311_X_d0),
    .X_1_address0(grp_nn_accelerator_Pipeline_read_input_data_VITIS_LOOP_97_3_fu_311_X_1_address0),
    .X_1_ce0(grp_nn_accelerator_Pipeline_read_input_data_VITIS_LOOP_97_3_fu_311_X_1_ce0),
    .X_1_we0(grp_nn_accelerator_Pipeline_read_input_data_VITIS_LOOP_97_3_fu_311_X_1_we0),
    .X_1_d0(grp_nn_accelerator_Pipeline_read_input_data_VITIS_LOOP_97_3_fu_311_X_1_d0),
    .X_2_address0(grp_nn_accelerator_Pipeline_read_input_data_VITIS_LOOP_97_3_fu_311_X_2_address0),
    .X_2_ce0(grp_nn_accelerator_Pipeline_read_input_data_VITIS_LOOP_97_3_fu_311_X_2_ce0),
    .X_2_we0(grp_nn_accelerator_Pipeline_read_input_data_VITIS_LOOP_97_3_fu_311_X_2_we0),
    .X_2_d0(grp_nn_accelerator_Pipeline_read_input_data_VITIS_LOOP_97_3_fu_311_X_2_d0),
    .X_3_address0(grp_nn_accelerator_Pipeline_read_input_data_VITIS_LOOP_97_3_fu_311_X_3_address0),
    .X_3_ce0(grp_nn_accelerator_Pipeline_read_input_data_VITIS_LOOP_97_3_fu_311_X_3_ce0),
    .X_3_we0(grp_nn_accelerator_Pipeline_read_input_data_VITIS_LOOP_97_3_fu_311_X_3_we0),
    .X_3_d0(grp_nn_accelerator_Pipeline_read_input_data_VITIS_LOOP_97_3_fu_311_X_3_d0),
    .X_4_address0(grp_nn_accelerator_Pipeline_read_input_data_VITIS_LOOP_97_3_fu_311_X_4_address0),
    .X_4_ce0(grp_nn_accelerator_Pipeline_read_input_data_VITIS_LOOP_97_3_fu_311_X_4_ce0),
    .X_4_we0(grp_nn_accelerator_Pipeline_read_input_data_VITIS_LOOP_97_3_fu_311_X_4_we0),
    .X_4_d0(grp_nn_accelerator_Pipeline_read_input_data_VITIS_LOOP_97_3_fu_311_X_4_d0),
    .X_5_address0(grp_nn_accelerator_Pipeline_read_input_data_VITIS_LOOP_97_3_fu_311_X_5_address0),
    .X_5_ce0(grp_nn_accelerator_Pipeline_read_input_data_VITIS_LOOP_97_3_fu_311_X_5_ce0),
    .X_5_we0(grp_nn_accelerator_Pipeline_read_input_data_VITIS_LOOP_97_3_fu_311_X_5_we0),
    .X_5_d0(grp_nn_accelerator_Pipeline_read_input_data_VITIS_LOOP_97_3_fu_311_X_5_d0),
    .X_6_address0(grp_nn_accelerator_Pipeline_read_input_data_VITIS_LOOP_97_3_fu_311_X_6_address0),
    .X_6_ce0(grp_nn_accelerator_Pipeline_read_input_data_VITIS_LOOP_97_3_fu_311_X_6_ce0),
    .X_6_we0(grp_nn_accelerator_Pipeline_read_input_data_VITIS_LOOP_97_3_fu_311_X_6_we0),
    .X_6_d0(grp_nn_accelerator_Pipeline_read_input_data_VITIS_LOOP_97_3_fu_311_X_6_d0),
    .S_AXIS_TDATA(S_AXIS_TDATA_int_regslice),
    .S_AXIS_TREADY(grp_nn_accelerator_Pipeline_read_input_data_VITIS_LOOP_97_3_fu_311_S_AXIS_TREADY),
    .S_AXIS_TKEEP(S_AXIS_TKEEP_int_regslice),
    .S_AXIS_TSTRB(S_AXIS_TSTRB_int_regslice),
    .S_AXIS_TLAST(S_AXIS_TLAST_int_regslice)
);

nn_accelerator_nn_accelerator_Pipeline_hidden_layer_VITIS_LOOP_106_4 grp_nn_accelerator_Pipeline_hidden_layer_VITIS_LOOP_106_4_fu_330(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_nn_accelerator_Pipeline_hidden_layer_VITIS_LOOP_106_4_fu_330_ap_start),
    .ap_done(grp_nn_accelerator_Pipeline_hidden_layer_VITIS_LOOP_106_4_fu_330_ap_done),
    .ap_idle(grp_nn_accelerator_Pipeline_hidden_layer_VITIS_LOOP_106_4_fu_330_ap_idle),
    .ap_ready(grp_nn_accelerator_Pipeline_hidden_layer_VITIS_LOOP_106_4_fu_330_ap_ready),
    .X_address0(grp_nn_accelerator_Pipeline_hidden_layer_VITIS_LOOP_106_4_fu_330_X_address0),
    .X_ce0(grp_nn_accelerator_Pipeline_hidden_layer_VITIS_LOOP_106_4_fu_330_X_ce0),
    .X_q0(X_q0),
    .X_1_address0(grp_nn_accelerator_Pipeline_hidden_layer_VITIS_LOOP_106_4_fu_330_X_1_address0),
    .X_1_ce0(grp_nn_accelerator_Pipeline_hidden_layer_VITIS_LOOP_106_4_fu_330_X_1_ce0),
    .X_1_q0(X_1_q0),
    .X_2_address0(grp_nn_accelerator_Pipeline_hidden_layer_VITIS_LOOP_106_4_fu_330_X_2_address0),
    .X_2_ce0(grp_nn_accelerator_Pipeline_hidden_layer_VITIS_LOOP_106_4_fu_330_X_2_ce0),
    .X_2_q0(X_2_q0),
    .X_3_address0(grp_nn_accelerator_Pipeline_hidden_layer_VITIS_LOOP_106_4_fu_330_X_3_address0),
    .X_3_ce0(grp_nn_accelerator_Pipeline_hidden_layer_VITIS_LOOP_106_4_fu_330_X_3_ce0),
    .X_3_q0(X_3_q0),
    .X_4_address0(grp_nn_accelerator_Pipeline_hidden_layer_VITIS_LOOP_106_4_fu_330_X_4_address0),
    .X_4_ce0(grp_nn_accelerator_Pipeline_hidden_layer_VITIS_LOOP_106_4_fu_330_X_4_ce0),
    .X_4_q0(X_4_q0),
    .X_5_address0(grp_nn_accelerator_Pipeline_hidden_layer_VITIS_LOOP_106_4_fu_330_X_5_address0),
    .X_5_ce0(grp_nn_accelerator_Pipeline_hidden_layer_VITIS_LOOP_106_4_fu_330_X_5_ce0),
    .X_5_q0(X_5_q0),
    .X_6_address0(grp_nn_accelerator_Pipeline_hidden_layer_VITIS_LOOP_106_4_fu_330_X_6_address0),
    .X_6_ce0(grp_nn_accelerator_Pipeline_hidden_layer_VITIS_LOOP_106_4_fu_330_X_6_ce0),
    .X_6_q0(X_6_q0),
    .hidden_address0(grp_nn_accelerator_Pipeline_hidden_layer_VITIS_LOOP_106_4_fu_330_hidden_address0),
    .hidden_ce0(grp_nn_accelerator_Pipeline_hidden_layer_VITIS_LOOP_106_4_fu_330_hidden_ce0),
    .hidden_we0(grp_nn_accelerator_Pipeline_hidden_layer_VITIS_LOOP_106_4_fu_330_hidden_we0),
    .hidden_d0(grp_nn_accelerator_Pipeline_hidden_layer_VITIS_LOOP_106_4_fu_330_hidden_d0),
    .W_hidden_1_load(W_hidden_1_load_reg_449),
    .W_hidden_load(W_hidden_load_reg_444),
    .W_hidden_1_load_1(W_hidden_1_load_1_reg_459),
    .W_hidden_load_1(W_hidden_load_1_reg_454),
    .W_hidden_1_load_2(W_hidden_1_load_2_reg_489),
    .W_hidden_load_2(W_hidden_load_2_reg_484),
    .W_hidden_1_load_3(W_hidden_1_load_3_reg_499),
    .W_hidden_load_3(W_hidden_load_3_reg_494),
    .W_hidden_1_load_4(W_hidden_1_load_4_reg_529),
    .W_hidden_load_4(W_hidden_load_4_reg_524),
    .W_hidden_1_load_5(W_hidden_1_load_5_reg_539),
    .W_hidden_load_5(W_hidden_load_5_reg_534),
    .W_hidden_1_load_6(W_hidden_1_load_6_reg_569),
    .W_hidden_load_6(W_hidden_load_6_reg_564),
    .W_hidden_1_load_7(W_hidden_1_load_7_reg_579),
    .W_hidden_load_7(W_hidden_load_7_reg_574)
);

nn_accelerator_nn_accelerator_Pipeline_output_layer grp_nn_accelerator_Pipeline_output_layer_fu_364(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_nn_accelerator_Pipeline_output_layer_fu_364_ap_start),
    .ap_done(grp_nn_accelerator_Pipeline_output_layer_fu_364_ap_done),
    .ap_idle(grp_nn_accelerator_Pipeline_output_layer_fu_364_ap_idle),
    .ap_ready(grp_nn_accelerator_Pipeline_output_layer_fu_364_ap_ready),
    .hidden_address0(grp_nn_accelerator_Pipeline_output_layer_fu_364_hidden_address0),
    .hidden_ce0(grp_nn_accelerator_Pipeline_output_layer_fu_364_hidden_ce0),
    .hidden_q0(hidden_q0),
    .hidden_address1(grp_nn_accelerator_Pipeline_output_layer_fu_364_hidden_address1),
    .hidden_ce1(grp_nn_accelerator_Pipeline_output_layer_fu_364_hidden_ce1),
    .hidden_q1(hidden_q1),
    .output_data_address0(grp_nn_accelerator_Pipeline_output_layer_fu_364_output_data_address0),
    .output_data_ce0(grp_nn_accelerator_Pipeline_output_layer_fu_364_output_data_ce0),
    .output_data_we0(grp_nn_accelerator_Pipeline_output_layer_fu_364_output_data_we0),
    .output_data_d0(grp_nn_accelerator_Pipeline_output_layer_fu_364_output_data_d0),
    .conv3_i_i85(grp_nn_accelerator_Pipeline_read_output_weights_fu_296_p_0_0388748_out),
    .conv3_i_i85_1(grp_nn_accelerator_Pipeline_read_output_weights_fu_296_p_0_0388_1750_out),
    .acc(acc_reg_590)
);

nn_accelerator_nn_accelerator_Pipeline_write_output_data grp_nn_accelerator_Pipeline_write_output_data_fu_373(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_nn_accelerator_Pipeline_write_output_data_fu_373_ap_start),
    .ap_done(grp_nn_accelerator_Pipeline_write_output_data_fu_373_ap_done),
    .ap_idle(grp_nn_accelerator_Pipeline_write_output_data_fu_373_ap_idle),
    .ap_ready(grp_nn_accelerator_Pipeline_write_output_data_fu_373_ap_ready),
    .M_AXIS_TREADY(grp_nn_accelerator_Pipeline_write_output_data_fu_373_M_AXIS_TREADY),
    .output_data_address0(grp_nn_accelerator_Pipeline_write_output_data_fu_373_output_data_address0),
    .output_data_ce0(grp_nn_accelerator_Pipeline_write_output_data_fu_373_output_data_ce0),
    .output_data_q0(output_data_q0),
    .M_AXIS_TDATA(grp_nn_accelerator_Pipeline_write_output_data_fu_373_M_AXIS_TDATA),
    .M_AXIS_TVALID(grp_nn_accelerator_Pipeline_write_output_data_fu_373_M_AXIS_TVALID),
    .M_AXIS_TKEEP(grp_nn_accelerator_Pipeline_write_output_data_fu_373_M_AXIS_TKEEP),
    .M_AXIS_TSTRB(grp_nn_accelerator_Pipeline_write_output_data_fu_373_M_AXIS_TSTRB),
    .M_AXIS_TLAST(grp_nn_accelerator_Pipeline_write_output_data_fu_373_M_AXIS_TLAST)
);

nn_accelerator_regslice_both #(
    .DataWidth( 32 ))
regslice_both_S_AXIS_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(S_AXIS_TDATA),
    .vld_in(S_AXIS_TVALID),
    .ack_in(regslice_both_S_AXIS_V_data_V_U_ack_in),
    .data_out(S_AXIS_TDATA_int_regslice),
    .vld_out(S_AXIS_TVALID_int_regslice),
    .ack_out(S_AXIS_TREADY_int_regslice),
    .apdone_blk(regslice_both_S_AXIS_V_data_V_U_apdone_blk)
);

nn_accelerator_regslice_both #(
    .DataWidth( 4 ))
regslice_both_S_AXIS_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(S_AXIS_TKEEP),
    .vld_in(S_AXIS_TVALID),
    .ack_in(regslice_both_S_AXIS_V_keep_V_U_ack_in),
    .data_out(S_AXIS_TKEEP_int_regslice),
    .vld_out(regslice_both_S_AXIS_V_keep_V_U_vld_out),
    .ack_out(S_AXIS_TREADY_int_regslice),
    .apdone_blk(regslice_both_S_AXIS_V_keep_V_U_apdone_blk)
);

nn_accelerator_regslice_both #(
    .DataWidth( 4 ))
regslice_both_S_AXIS_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(S_AXIS_TSTRB),
    .vld_in(S_AXIS_TVALID),
    .ack_in(regslice_both_S_AXIS_V_strb_V_U_ack_in),
    .data_out(S_AXIS_TSTRB_int_regslice),
    .vld_out(regslice_both_S_AXIS_V_strb_V_U_vld_out),
    .ack_out(S_AXIS_TREADY_int_regslice),
    .apdone_blk(regslice_both_S_AXIS_V_strb_V_U_apdone_blk)
);

nn_accelerator_regslice_both #(
    .DataWidth( 1 ))
regslice_both_S_AXIS_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(S_AXIS_TLAST),
    .vld_in(S_AXIS_TVALID),
    .ack_in(regslice_both_S_AXIS_V_last_V_U_ack_in),
    .data_out(S_AXIS_TLAST_int_regslice),
    .vld_out(regslice_both_S_AXIS_V_last_V_U_vld_out),
    .ack_out(S_AXIS_TREADY_int_regslice),
    .apdone_blk(regslice_both_S_AXIS_V_last_V_U_apdone_blk)
);

nn_accelerator_regslice_both #(
    .DataWidth( 32 ))
regslice_both_M_AXIS_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(M_AXIS_TDATA_int_regslice),
    .vld_in(grp_nn_accelerator_Pipeline_write_output_data_fu_373_M_AXIS_TVALID),
    .ack_in(M_AXIS_TREADY_int_regslice),
    .data_out(M_AXIS_TDATA),
    .vld_out(regslice_both_M_AXIS_V_data_V_U_vld_out),
    .ack_out(M_AXIS_TREADY),
    .apdone_blk(regslice_both_M_AXIS_V_data_V_U_apdone_blk)
);

nn_accelerator_regslice_both #(
    .DataWidth( 4 ))
regslice_both_M_AXIS_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(M_AXIS_TKEEP_int_regslice),
    .vld_in(grp_nn_accelerator_Pipeline_write_output_data_fu_373_M_AXIS_TVALID),
    .ack_in(regslice_both_M_AXIS_V_keep_V_U_ack_in_dummy),
    .data_out(M_AXIS_TKEEP),
    .vld_out(regslice_both_M_AXIS_V_keep_V_U_vld_out),
    .ack_out(M_AXIS_TREADY),
    .apdone_blk(regslice_both_M_AXIS_V_keep_V_U_apdone_blk)
);

nn_accelerator_regslice_both #(
    .DataWidth( 4 ))
regslice_both_M_AXIS_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(M_AXIS_TSTRB_int_regslice),
    .vld_in(grp_nn_accelerator_Pipeline_write_output_data_fu_373_M_AXIS_TVALID),
    .ack_in(regslice_both_M_AXIS_V_strb_V_U_ack_in_dummy),
    .data_out(M_AXIS_TSTRB),
    .vld_out(regslice_both_M_AXIS_V_strb_V_U_vld_out),
    .ack_out(M_AXIS_TREADY),
    .apdone_blk(regslice_both_M_AXIS_V_strb_V_U_apdone_blk)
);

nn_accelerator_regslice_both #(
    .DataWidth( 1 ))
regslice_both_M_AXIS_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(M_AXIS_TLAST_int_regslice),
    .vld_in(grp_nn_accelerator_Pipeline_write_output_data_fu_373_M_AXIS_TVALID),
    .ack_in(regslice_both_M_AXIS_V_last_V_U_ack_in_dummy),
    .data_out(M_AXIS_TLAST),
    .vld_out(regslice_both_M_AXIS_V_last_V_U_vld_out),
    .ack_out(M_AXIS_TREADY),
    .apdone_blk(regslice_both_M_AXIS_V_last_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_nn_accelerator_Pipeline_hidden_layer_VITIS_LOOP_106_4_fu_330_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state8)) begin
            grp_nn_accelerator_Pipeline_hidden_layer_VITIS_LOOP_106_4_fu_330_ap_start_reg <= 1'b1;
        end else if ((grp_nn_accelerator_Pipeline_hidden_layer_VITIS_LOOP_106_4_fu_330_ap_ready == 1'b1)) begin
            grp_nn_accelerator_Pipeline_hidden_layer_VITIS_LOOP_106_4_fu_330_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_nn_accelerator_Pipeline_output_layer_fu_364_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state10)) begin
            grp_nn_accelerator_Pipeline_output_layer_fu_364_ap_start_reg <= 1'b1;
        end else if ((grp_nn_accelerator_Pipeline_output_layer_fu_364_ap_ready == 1'b1)) begin
            grp_nn_accelerator_Pipeline_output_layer_fu_364_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_79_1_fu_282_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_79_1_fu_282_ap_start_reg <= 1'b1;
        end else if ((grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_79_1_fu_282_ap_ready == 1'b1)) begin
            grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_79_1_fu_282_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_nn_accelerator_Pipeline_read_input_data_VITIS_LOOP_97_3_fu_311_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state6)) begin
            grp_nn_accelerator_Pipeline_read_input_data_VITIS_LOOP_97_3_fu_311_ap_start_reg <= 1'b1;
        end else if ((grp_nn_accelerator_Pipeline_read_input_data_VITIS_LOOP_97_3_fu_311_ap_ready == 1'b1)) begin
            grp_nn_accelerator_Pipeline_read_input_data_VITIS_LOOP_97_3_fu_311_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_nn_accelerator_Pipeline_read_output_weights_fu_296_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state4)) begin
            grp_nn_accelerator_Pipeline_read_output_weights_fu_296_ap_start_reg <= 1'b1;
        end else if ((grp_nn_accelerator_Pipeline_read_output_weights_fu_296_ap_ready == 1'b1)) begin
            grp_nn_accelerator_Pipeline_read_output_weights_fu_296_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_nn_accelerator_Pipeline_write_output_data_fu_373_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state12)) begin
            grp_nn_accelerator_Pipeline_write_output_data_fu_373_ap_start_reg <= 1'b1;
        end else if ((grp_nn_accelerator_Pipeline_write_output_data_fu_373_ap_ready == 1'b1)) begin
            grp_nn_accelerator_Pipeline_write_output_data_fu_373_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((grp_nn_accelerator_Pipeline_write_output_data_fu_373_M_AXIS_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state13))) begin
        M_AXIS_TDATA_reg <= grp_nn_accelerator_Pipeline_write_output_data_fu_373_M_AXIS_TDATA;
        M_AXIS_TKEEP_reg <= grp_nn_accelerator_Pipeline_write_output_data_fu_373_M_AXIS_TKEEP;
        M_AXIS_TLAST_reg <= grp_nn_accelerator_Pipeline_write_output_data_fu_373_M_AXIS_TLAST;
        M_AXIS_TSTRB_reg <= grp_nn_accelerator_Pipeline_write_output_data_fu_373_M_AXIS_TSTRB;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        W_hidden_1_load_1_reg_459 <= W_hidden_1_q0;
        W_hidden_1_load_reg_449 <= W_hidden_1_q1;
        W_hidden_load_1_reg_454 <= W_hidden_q0;
        W_hidden_load_reg_444 <= W_hidden_q1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        W_hidden_1_load_2_reg_489 <= W_hidden_1_q1;
        W_hidden_1_load_3_reg_499 <= W_hidden_1_q0;
        W_hidden_load_2_reg_484 <= W_hidden_q1;
        W_hidden_load_3_reg_494 <= W_hidden_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        W_hidden_1_load_4_reg_529 <= W_hidden_1_q1;
        W_hidden_1_load_5_reg_539 <= W_hidden_1_q0;
        W_hidden_load_4_reg_524 <= W_hidden_q1;
        W_hidden_load_5_reg_534 <= W_hidden_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        W_hidden_1_load_6_reg_569 <= W_hidden_1_q1;
        W_hidden_1_load_7_reg_579 <= W_hidden_1_q0;
        W_hidden_load_6_reg_564 <= W_hidden_q1;
        W_hidden_load_7_reg_574 <= W_hidden_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        acc_reg_590[15 : 8] <= acc_fu_397_p3[15 : 8];
    end
end

always @ (*) begin
    if (((grp_nn_accelerator_Pipeline_write_output_data_fu_373_M_AXIS_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state13))) begin
        M_AXIS_TDATA_int_regslice = grp_nn_accelerator_Pipeline_write_output_data_fu_373_M_AXIS_TDATA;
    end else begin
        M_AXIS_TDATA_int_regslice = M_AXIS_TDATA_reg;
    end
end

always @ (*) begin
    if (((grp_nn_accelerator_Pipeline_write_output_data_fu_373_M_AXIS_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state13))) begin
        M_AXIS_TKEEP_int_regslice = grp_nn_accelerator_Pipeline_write_output_data_fu_373_M_AXIS_TKEEP;
    end else begin
        M_AXIS_TKEEP_int_regslice = M_AXIS_TKEEP_reg;
    end
end

always @ (*) begin
    if (((grp_nn_accelerator_Pipeline_write_output_data_fu_373_M_AXIS_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state13))) begin
        M_AXIS_TLAST_int_regslice = grp_nn_accelerator_Pipeline_write_output_data_fu_373_M_AXIS_TLAST;
    end else begin
        M_AXIS_TLAST_int_regslice = M_AXIS_TLAST_reg;
    end
end

always @ (*) begin
    if (((grp_nn_accelerator_Pipeline_write_output_data_fu_373_M_AXIS_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state13))) begin
        M_AXIS_TSTRB_int_regslice = grp_nn_accelerator_Pipeline_write_output_data_fu_373_M_AXIS_TSTRB;
    end else begin
        M_AXIS_TSTRB_int_regslice = M_AXIS_TSTRB_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        S_AXIS_TREADY_int_regslice = grp_nn_accelerator_Pipeline_read_input_data_VITIS_LOOP_97_3_fu_311_S_AXIS_TREADY;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        S_AXIS_TREADY_int_regslice = grp_nn_accelerator_Pipeline_read_output_weights_fu_296_S_AXIS_TREADY;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        S_AXIS_TREADY_int_regslice = grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_79_1_fu_282_S_AXIS_TREADY;
    end else begin
        S_AXIS_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        W_hidden_1_address0 = grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_79_1_fu_282_W_hidden_1_address0;
    end else begin
        W_hidden_1_address0 = W_hidden_1_address0_local;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        W_hidden_1_address0_local = 64'd7;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        W_hidden_1_address0_local = 64'd5;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        W_hidden_1_address0_local = 64'd3;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        W_hidden_1_address0_local = 64'd1;
    end else begin
        W_hidden_1_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        W_hidden_1_address1_local = 64'd6;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        W_hidden_1_address1_local = 64'd4;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        W_hidden_1_address1_local = 64'd2;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        W_hidden_1_address1_local = 64'd0;
    end else begin
        W_hidden_1_address1_local = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        W_hidden_1_ce0 = grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_79_1_fu_282_W_hidden_1_ce0;
    end else begin
        W_hidden_1_ce0 = W_hidden_1_ce0_local;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state4) | ((grp_nn_accelerator_Pipeline_read_input_data_VITIS_LOOP_97_3_fu_311_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state7)) | ((grp_nn_accelerator_Pipeline_read_output_weights_fu_296_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5)))) begin
        W_hidden_1_ce0_local = 1'b1;
    end else begin
        W_hidden_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state4) | ((grp_nn_accelerator_Pipeline_read_input_data_VITIS_LOOP_97_3_fu_311_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state7)) | ((grp_nn_accelerator_Pipeline_read_output_weights_fu_296_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5)))) begin
        W_hidden_1_ce1_local = 1'b1;
    end else begin
        W_hidden_1_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        W_hidden_1_we0 = grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_79_1_fu_282_W_hidden_1_we0;
    end else begin
        W_hidden_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        W_hidden_address0 = grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_79_1_fu_282_W_hidden_address0;
    end else begin
        W_hidden_address0 = W_hidden_address0_local;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        W_hidden_address0_local = 64'd7;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        W_hidden_address0_local = 64'd5;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        W_hidden_address0_local = 64'd3;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        W_hidden_address0_local = 64'd1;
    end else begin
        W_hidden_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        W_hidden_address1_local = 64'd6;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        W_hidden_address1_local = 64'd4;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        W_hidden_address1_local = 64'd2;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        W_hidden_address1_local = 64'd0;
    end else begin
        W_hidden_address1_local = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        W_hidden_ce0 = grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_79_1_fu_282_W_hidden_ce0;
    end else begin
        W_hidden_ce0 = W_hidden_ce0_local;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state4) | ((grp_nn_accelerator_Pipeline_read_input_data_VITIS_LOOP_97_3_fu_311_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state7)) | ((grp_nn_accelerator_Pipeline_read_output_weights_fu_296_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5)))) begin
        W_hidden_ce0_local = 1'b1;
    end else begin
        W_hidden_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state4) | ((grp_nn_accelerator_Pipeline_read_input_data_VITIS_LOOP_97_3_fu_311_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state7)) | ((grp_nn_accelerator_Pipeline_read_output_weights_fu_296_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5)))) begin
        W_hidden_ce1_local = 1'b1;
    end else begin
        W_hidden_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        W_hidden_we0 = grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_79_1_fu_282_W_hidden_we0;
    end else begin
        W_hidden_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        X_1_address0 = grp_nn_accelerator_Pipeline_hidden_layer_VITIS_LOOP_106_4_fu_330_X_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        X_1_address0 = grp_nn_accelerator_Pipeline_read_input_data_VITIS_LOOP_97_3_fu_311_X_1_address0;
    end else begin
        X_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        X_1_ce0 = grp_nn_accelerator_Pipeline_hidden_layer_VITIS_LOOP_106_4_fu_330_X_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        X_1_ce0 = grp_nn_accelerator_Pipeline_read_input_data_VITIS_LOOP_97_3_fu_311_X_1_ce0;
    end else begin
        X_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        X_1_we0 = grp_nn_accelerator_Pipeline_read_input_data_VITIS_LOOP_97_3_fu_311_X_1_we0;
    end else begin
        X_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        X_2_address0 = grp_nn_accelerator_Pipeline_hidden_layer_VITIS_LOOP_106_4_fu_330_X_2_address0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        X_2_address0 = grp_nn_accelerator_Pipeline_read_input_data_VITIS_LOOP_97_3_fu_311_X_2_address0;
    end else begin
        X_2_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        X_2_ce0 = grp_nn_accelerator_Pipeline_hidden_layer_VITIS_LOOP_106_4_fu_330_X_2_ce0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        X_2_ce0 = grp_nn_accelerator_Pipeline_read_input_data_VITIS_LOOP_97_3_fu_311_X_2_ce0;
    end else begin
        X_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        X_2_we0 = grp_nn_accelerator_Pipeline_read_input_data_VITIS_LOOP_97_3_fu_311_X_2_we0;
    end else begin
        X_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        X_3_address0 = grp_nn_accelerator_Pipeline_hidden_layer_VITIS_LOOP_106_4_fu_330_X_3_address0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        X_3_address0 = grp_nn_accelerator_Pipeline_read_input_data_VITIS_LOOP_97_3_fu_311_X_3_address0;
    end else begin
        X_3_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        X_3_ce0 = grp_nn_accelerator_Pipeline_hidden_layer_VITIS_LOOP_106_4_fu_330_X_3_ce0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        X_3_ce0 = grp_nn_accelerator_Pipeline_read_input_data_VITIS_LOOP_97_3_fu_311_X_3_ce0;
    end else begin
        X_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        X_3_we0 = grp_nn_accelerator_Pipeline_read_input_data_VITIS_LOOP_97_3_fu_311_X_3_we0;
    end else begin
        X_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        X_4_address0 = grp_nn_accelerator_Pipeline_hidden_layer_VITIS_LOOP_106_4_fu_330_X_4_address0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        X_4_address0 = grp_nn_accelerator_Pipeline_read_input_data_VITIS_LOOP_97_3_fu_311_X_4_address0;
    end else begin
        X_4_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        X_4_ce0 = grp_nn_accelerator_Pipeline_hidden_layer_VITIS_LOOP_106_4_fu_330_X_4_ce0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        X_4_ce0 = grp_nn_accelerator_Pipeline_read_input_data_VITIS_LOOP_97_3_fu_311_X_4_ce0;
    end else begin
        X_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        X_4_we0 = grp_nn_accelerator_Pipeline_read_input_data_VITIS_LOOP_97_3_fu_311_X_4_we0;
    end else begin
        X_4_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        X_5_address0 = grp_nn_accelerator_Pipeline_hidden_layer_VITIS_LOOP_106_4_fu_330_X_5_address0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        X_5_address0 = grp_nn_accelerator_Pipeline_read_input_data_VITIS_LOOP_97_3_fu_311_X_5_address0;
    end else begin
        X_5_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        X_5_ce0 = grp_nn_accelerator_Pipeline_hidden_layer_VITIS_LOOP_106_4_fu_330_X_5_ce0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        X_5_ce0 = grp_nn_accelerator_Pipeline_read_input_data_VITIS_LOOP_97_3_fu_311_X_5_ce0;
    end else begin
        X_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        X_5_we0 = grp_nn_accelerator_Pipeline_read_input_data_VITIS_LOOP_97_3_fu_311_X_5_we0;
    end else begin
        X_5_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        X_6_address0 = grp_nn_accelerator_Pipeline_hidden_layer_VITIS_LOOP_106_4_fu_330_X_6_address0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        X_6_address0 = grp_nn_accelerator_Pipeline_read_input_data_VITIS_LOOP_97_3_fu_311_X_6_address0;
    end else begin
        X_6_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        X_6_ce0 = grp_nn_accelerator_Pipeline_hidden_layer_VITIS_LOOP_106_4_fu_330_X_6_ce0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        X_6_ce0 = grp_nn_accelerator_Pipeline_read_input_data_VITIS_LOOP_97_3_fu_311_X_6_ce0;
    end else begin
        X_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        X_6_we0 = grp_nn_accelerator_Pipeline_read_input_data_VITIS_LOOP_97_3_fu_311_X_6_we0;
    end else begin
        X_6_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        X_address0 = grp_nn_accelerator_Pipeline_hidden_layer_VITIS_LOOP_106_4_fu_330_X_address0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        X_address0 = grp_nn_accelerator_Pipeline_read_input_data_VITIS_LOOP_97_3_fu_311_X_address0;
    end else begin
        X_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        X_ce0 = grp_nn_accelerator_Pipeline_hidden_layer_VITIS_LOOP_106_4_fu_330_X_ce0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        X_ce0 = grp_nn_accelerator_Pipeline_read_input_data_VITIS_LOOP_97_3_fu_311_X_ce0;
    end else begin
        X_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        X_we0 = grp_nn_accelerator_Pipeline_read_input_data_VITIS_LOOP_97_3_fu_311_X_we0;
    end else begin
        X_we0 = 1'b0;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

always @ (*) begin
    if ((grp_nn_accelerator_Pipeline_output_layer_fu_364_ap_done == 1'b0)) begin
        ap_ST_fsm_state11_blk = 1'b1;
    end else begin
        ap_ST_fsm_state11_blk = 1'b0;
    end
end

assign ap_ST_fsm_state12_blk = 1'b0;

always @ (*) begin
    if ((grp_nn_accelerator_Pipeline_write_output_data_fu_373_ap_done == 1'b0)) begin
        ap_ST_fsm_state13_blk = 1'b1;
    end else begin
        ap_ST_fsm_state13_blk = 1'b0;
    end
end

always @ (*) begin
    if ((regslice_both_M_AXIS_V_data_V_U_apdone_blk == 1'b1)) begin
        ap_ST_fsm_state14_blk = 1'b1;
    end else begin
        ap_ST_fsm_state14_blk = 1'b0;
    end
end

assign ap_ST_fsm_state1_blk = 1'b0;

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_79_1_fu_282_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if ((grp_nn_accelerator_Pipeline_read_output_weights_fu_296_ap_done == 1'b0)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

assign ap_ST_fsm_state6_blk = 1'b0;

always @ (*) begin
    if ((grp_nn_accelerator_Pipeline_read_input_data_VITIS_LOOP_97_3_fu_311_ap_done == 1'b0)) begin
        ap_ST_fsm_state7_blk = 1'b1;
    end else begin
        ap_ST_fsm_state7_blk = 1'b0;
    end
end

assign ap_ST_fsm_state8_blk = 1'b0;

always @ (*) begin
    if ((grp_nn_accelerator_Pipeline_hidden_layer_VITIS_LOOP_106_4_fu_330_ap_done == 1'b0)) begin
        ap_ST_fsm_state9_blk = 1'b1;
    end else begin
        ap_ST_fsm_state9_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        hidden_address0 = grp_nn_accelerator_Pipeline_output_layer_fu_364_hidden_address0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        hidden_address0 = grp_nn_accelerator_Pipeline_hidden_layer_VITIS_LOOP_106_4_fu_330_hidden_address0;
    end else begin
        hidden_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        hidden_ce0 = grp_nn_accelerator_Pipeline_output_layer_fu_364_hidden_ce0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        hidden_ce0 = grp_nn_accelerator_Pipeline_hidden_layer_VITIS_LOOP_106_4_fu_330_hidden_ce0;
    end else begin
        hidden_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        hidden_ce1 = grp_nn_accelerator_Pipeline_output_layer_fu_364_hidden_ce1;
    end else begin
        hidden_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        hidden_we0 = grp_nn_accelerator_Pipeline_hidden_layer_VITIS_LOOP_106_4_fu_330_hidden_we0;
    end else begin
        hidden_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        output_data_address0 = grp_nn_accelerator_Pipeline_write_output_data_fu_373_output_data_address0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        output_data_address0 = grp_nn_accelerator_Pipeline_output_layer_fu_364_output_data_address0;
    end else begin
        output_data_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        output_data_ce0 = grp_nn_accelerator_Pipeline_write_output_data_fu_373_output_data_ce0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        output_data_ce0 = grp_nn_accelerator_Pipeline_output_layer_fu_364_output_data_ce0;
    end else begin
        output_data_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        output_data_we0 = grp_nn_accelerator_Pipeline_output_layer_fu_364_output_data_we0;
    end else begin
        output_data_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_79_1_fu_282_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((grp_nn_accelerator_Pipeline_read_output_weights_fu_296_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            if (((grp_nn_accelerator_Pipeline_read_input_data_VITIS_LOOP_97_3_fu_311_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            if (((grp_nn_accelerator_Pipeline_hidden_layer_VITIS_LOOP_106_4_fu_330_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            if (((grp_nn_accelerator_Pipeline_output_layer_fu_364_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            if (((grp_nn_accelerator_Pipeline_write_output_data_fu_373_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state13))) begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end
        end
        ap_ST_fsm_state14 : begin
            if (((regslice_both_M_AXIS_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state14))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign M_AXIS_TVALID = regslice_both_M_AXIS_V_data_V_U_vld_out;

assign M_AXIS_TVALID_int_regslice = grp_nn_accelerator_Pipeline_write_output_data_fu_373_M_AXIS_TVALID;

assign S_AXIS_TREADY = regslice_both_S_AXIS_V_data_V_U_ack_in;

assign acc_fu_397_p3 = {{grp_nn_accelerator_Pipeline_read_output_weights_fu_296_p_0_0396746_out}, {8'd0}};

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign grp_nn_accelerator_Pipeline_hidden_layer_VITIS_LOOP_106_4_fu_330_ap_start = grp_nn_accelerator_Pipeline_hidden_layer_VITIS_LOOP_106_4_fu_330_ap_start_reg;

assign grp_nn_accelerator_Pipeline_output_layer_fu_364_ap_start = grp_nn_accelerator_Pipeline_output_layer_fu_364_ap_start_reg;

assign grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_79_1_fu_282_ap_start = grp_nn_accelerator_Pipeline_read_hidden_weights_VITIS_LOOP_79_1_fu_282_ap_start_reg;

assign grp_nn_accelerator_Pipeline_read_input_data_VITIS_LOOP_97_3_fu_311_ap_start = grp_nn_accelerator_Pipeline_read_input_data_VITIS_LOOP_97_3_fu_311_ap_start_reg;

assign grp_nn_accelerator_Pipeline_read_output_weights_fu_296_ap_start = grp_nn_accelerator_Pipeline_read_output_weights_fu_296_ap_start_reg;

assign grp_nn_accelerator_Pipeline_write_output_data_fu_373_M_AXIS_TREADY = (ap_CS_fsm_state13 & M_AXIS_TREADY_int_regslice);

assign grp_nn_accelerator_Pipeline_write_output_data_fu_373_ap_start = grp_nn_accelerator_Pipeline_write_output_data_fu_373_ap_start_reg;

always @ (posedge ap_clk) begin
    acc_reg_590[7:0] <= 8'b00000000;
end


reg find_kernel_block = 0;
// synthesis translate_off
`include "nn_accelerator_hls_deadlock_kernel_monitor_top.vh"
// synthesis translate_on

endmodule //nn_accelerator

