// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module nn_accelerator_nn_accelerator_Pipeline_output_layer (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        hidden_address0,
        hidden_ce0,
        hidden_q0,
        hidden_address1,
        hidden_ce1,
        hidden_q1,
        output_data_address0,
        output_data_ce0,
        output_data_we0,
        output_data_d0,
        conv3_i_i85,
        conv3_i_i85_1,
        acc
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [6:0] hidden_address0;
output   hidden_ce0;
input  [7:0] hidden_q0;
output  [6:0] hidden_address1;
output   hidden_ce1;
input  [7:0] hidden_q1;
output  [5:0] output_data_address0;
output   output_data_ce0;
output   output_data_we0;
output  [0:0] output_data_d0;
input  [7:0] conv3_i_i85;
input  [7:0] conv3_i_i85_1;
input  [15:0] acc;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln121_fu_132_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire   [15:0] conv3_i_i85_1_cast_fu_116_p1;
reg   [15:0] conv3_i_i85_1_cast_reg_254;
wire   [15:0] conv3_i_i85_cast_fu_120_p1;
reg   [15:0] conv3_i_i85_cast_reg_259;
reg   [6:0] i_2_reg_264;
reg   [6:0] i_2_reg_264_pp0_iter1_reg;
reg   [6:0] i_2_reg_264_pp0_iter2_reg;
reg   [6:0] i_2_reg_264_pp0_iter3_reg;
reg   [6:0] i_2_reg_264_pp0_iter4_reg;
wire   [15:0] grp_fu_227_p3;
wire   [63:0] zext_ln127_3_fu_156_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln127_2_fu_171_p1;
wire   [63:0] zext_ln121_fu_184_p1;
reg   [6:0] i_fu_56;
wire   [6:0] add_ln121_fu_138_p2;
wire    ap_loop_init;
reg   [6:0] ap_sig_allocacmp_i_2;
reg    hidden_ce1_local;
reg    hidden_ce0_local;
reg    output_data_we0_local;
wire   [0:0] or_ln134_fu_220_p2;
reg    output_data_ce0_local;
wire   [5:0] trunc_ln121_fu_144_p1;
wire   [6:0] tmp_2_fu_148_p3;
wire   [6:0] shl_ln127_fu_166_p2;
wire   [15:0] grp_fu_233_p3;
wire   [0:0] icmp_ln132_fu_197_p2;
wire   [7:0] trunc_ln2_fu_188_p4;
wire   [7:0] acc_2_fu_202_p3;
wire   [0:0] icmp_ln133_fu_214_p2;
wire   [0:0] trunc_ln75_fu_210_p1;
wire   [7:0] grp_fu_227_p0;
wire   [7:0] grp_fu_227_p1;
wire   [7:0] grp_fu_233_p0;
wire   [7:0] grp_fu_233_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [15:0] grp_fu_227_p00;
wire   [15:0] grp_fu_233_p00;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 i_fu_56 = 7'd0;
#0 ap_done_reg = 1'b0;
end

nn_accelerator_mac_muladd_8ns_8ns_16ns_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
mac_muladd_8ns_8ns_16ns_16_4_1_U59(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_227_p0),
    .din1(grp_fu_227_p1),
    .din2(acc),
    .ce(1'b1),
    .dout(grp_fu_227_p3)
);

nn_accelerator_mac_muladd_8ns_8ns_16ns_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
mac_muladd_8ns_8ns_16ns_16_4_1_U60(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_233_p0),
    .din1(grp_fu_233_p1),
    .din2(grp_fu_227_p3),
    .ce(1'b1),
    .dout(grp_fu_233_p3)
);

nn_accelerator_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln121_fu_132_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_fu_56 <= add_ln121_fu_138_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_56 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        conv3_i_i85_1_cast_reg_254[7 : 0] <= conv3_i_i85_1_cast_fu_116_p1[7 : 0];
        conv3_i_i85_cast_reg_259[7 : 0] <= conv3_i_i85_cast_fu_120_p1[7 : 0];
        i_2_reg_264 <= ap_sig_allocacmp_i_2;
        i_2_reg_264_pp0_iter1_reg <= i_2_reg_264;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        i_2_reg_264_pp0_iter2_reg <= i_2_reg_264_pp0_iter1_reg;
        i_2_reg_264_pp0_iter3_reg <= i_2_reg_264_pp0_iter2_reg;
        i_2_reg_264_pp0_iter4_reg <= i_2_reg_264_pp0_iter3_reg;
    end
end

always @ (*) begin
    if (((icmp_ln121_fu_132_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_2 = 7'd0;
    end else begin
        ap_sig_allocacmp_i_2 = i_fu_56;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        hidden_ce0_local = 1'b1;
    end else begin
        hidden_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        hidden_ce1_local = 1'b1;
    end else begin
        hidden_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        output_data_ce0_local = 1'b1;
    end else begin
        output_data_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        output_data_we0_local = 1'b1;
    end else begin
        output_data_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign acc_2_fu_202_p3 = ((icmp_ln132_fu_197_p2[0:0] == 1'b1) ? 8'd0 : trunc_ln2_fu_188_p4);

assign add_ln121_fu_138_p2 = (ap_sig_allocacmp_i_2 + 7'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign conv3_i_i85_1_cast_fu_116_p1 = conv3_i_i85_1;

assign conv3_i_i85_cast_fu_120_p1 = conv3_i_i85;

assign grp_fu_227_p0 = grp_fu_227_p00;

assign grp_fu_227_p00 = hidden_q1;

assign grp_fu_227_p1 = conv3_i_i85_1_cast_reg_254;

assign grp_fu_233_p0 = grp_fu_233_p00;

assign grp_fu_233_p00 = hidden_q0;

assign grp_fu_233_p1 = conv3_i_i85_cast_reg_259;

assign hidden_address0 = zext_ln127_2_fu_171_p1;

assign hidden_address1 = zext_ln127_3_fu_156_p1;

assign hidden_ce0 = hidden_ce0_local;

assign hidden_ce1 = hidden_ce1_local;

assign icmp_ln121_fu_132_p2 = ((ap_sig_allocacmp_i_2 == 7'd64) ? 1'b1 : 1'b0);

assign icmp_ln132_fu_197_p2 = ((grp_fu_233_p3 < 16'd33024) ? 1'b1 : 1'b0);

assign icmp_ln133_fu_214_p2 = ((acc_2_fu_202_p3 > 8'd128) ? 1'b1 : 1'b0);

assign or_ln134_fu_220_p2 = (trunc_ln75_fu_210_p1 | icmp_ln133_fu_214_p2);

assign output_data_address0 = zext_ln121_fu_184_p1;

assign output_data_ce0 = output_data_ce0_local;

assign output_data_d0 = or_ln134_fu_220_p2;

assign output_data_we0 = output_data_we0_local;

assign shl_ln127_fu_166_p2 = i_2_reg_264 << 7'd1;

assign tmp_2_fu_148_p3 = {{trunc_ln121_fu_144_p1}, {1'd1}};

assign trunc_ln121_fu_144_p1 = ap_sig_allocacmp_i_2[5:0];

assign trunc_ln2_fu_188_p4 = {{grp_fu_233_p3[15:8]}};

assign trunc_ln75_fu_210_p1 = acc_2_fu_202_p3[0:0];

assign zext_ln121_fu_184_p1 = i_2_reg_264_pp0_iter4_reg;

assign zext_ln127_2_fu_171_p1 = shl_ln127_fu_166_p2;

assign zext_ln127_3_fu_156_p1 = tmp_2_fu_148_p3;

always @ (posedge ap_clk) begin
    conv3_i_i85_1_cast_reg_254[15:8] <= 8'b00000000;
    conv3_i_i85_cast_reg_259[15:8] <= 8'b00000000;
end

endmodule //nn_accelerator_nn_accelerator_Pipeline_output_layer
